// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetmock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	"github.com/mydecisive/octant/internal/budget/data"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricDataProvider creates a new instance of MockMetricDataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricDataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricDataProvider {
	mock := &MockMetricDataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricDataProvider is an autogenerated mock type for the MetricDataProvider type
type MockMetricDataProvider struct {
	mock.Mock
}

type MockMetricDataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricDataProvider) EXPECT() *MockMetricDataProvider_Expecter {
	return &MockMetricDataProvider_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function for the type MockMetricDataProvider
func (_mock *MockMetricDataProvider) GetLogs(ctx context.Context, input budgetdata.MetricDataInput) ([]*budgetv1alpha.Log, string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []*budgetv1alpha.Log
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetdata.MetricDataInput) ([]*budgetv1alpha.Log, string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetdata.MetricDataInput) []*budgetv1alpha.Log); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*budgetv1alpha.Log)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, budgetdata.MetricDataInput) string); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, budgetdata.MetricDataInput) error); ok {
		r2 = returnFunc(ctx, input)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetricDataProvider_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockMetricDataProvider_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - input budgetdata.MetricDataInput
func (_e *MockMetricDataProvider_Expecter) GetLogs(ctx interface{}, input interface{}) *MockMetricDataProvider_GetLogs_Call {
	return &MockMetricDataProvider_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, input)}
}

func (_c *MockMetricDataProvider_GetLogs_Call) Run(run func(ctx context.Context, input budgetdata.MetricDataInput)) *MockMetricDataProvider_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 budgetdata.MetricDataInput
		if args[1] != nil {
			arg1 = args[1].(budgetdata.MetricDataInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricDataProvider_GetLogs_Call) Return(logs []*budgetv1alpha.Log, s string, err error) *MockMetricDataProvider_GetLogs_Call {
	_c.Call.Return(logs, s, err)
	return _c
}

func (_c *MockMetricDataProvider_GetLogs_Call) RunAndReturn(run func(ctx context.Context, input budgetdata.MetricDataInput) ([]*budgetv1alpha.Log, string, error)) *MockMetricDataProvider_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverall provides a mock function for the type MockMetricDataProvider
func (_mock *MockMetricDataProvider) GetOverall(ctx context.Context, timeframe budgetv1alpha.Timeframe, namespace string) (*budgetv1alpha.Overall, error) {
	ret := _mock.Called(ctx, timeframe, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetOverall")
	}

	var r0 *budgetv1alpha.Overall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetv1alpha.Timeframe, string) (*budgetv1alpha.Overall, error)); ok {
		return returnFunc(ctx, timeframe, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetv1alpha.Timeframe, string) *budgetv1alpha.Overall); ok {
		r0 = returnFunc(ctx, timeframe, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*budgetv1alpha.Overall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, budgetv1alpha.Timeframe, string) error); ok {
		r1 = returnFunc(ctx, timeframe, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricDataProvider_GetOverall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverall'
type MockMetricDataProvider_GetOverall_Call struct {
	*mock.Call
}

// GetOverall is a helper method to define mock.On call
//   - ctx context.Context
//   - timeframe budgetv1alpha.Timeframe
//   - namespace string
func (_e *MockMetricDataProvider_Expecter) GetOverall(ctx interface{}, timeframe interface{}, namespace interface{}) *MockMetricDataProvider_GetOverall_Call {
	return &MockMetricDataProvider_GetOverall_Call{Call: _e.mock.On("GetOverall", ctx, timeframe, namespace)}
}

func (_c *MockMetricDataProvider_GetOverall_Call) Run(run func(ctx context.Context, timeframe budgetv1alpha.Timeframe, namespace string)) *MockMetricDataProvider_GetOverall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 budgetv1alpha.Timeframe
		if args[1] != nil {
			arg1 = args[1].(budgetv1alpha.Timeframe)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricDataProvider_GetOverall_Call) Return(overall *budgetv1alpha.Overall, err error) *MockMetricDataProvider_GetOverall_Call {
	_c.Call.Return(overall, err)
	return _c
}

func (_c *MockMetricDataProvider_GetOverall_Call) RunAndReturn(run func(ctx context.Context, timeframe budgetv1alpha.Timeframe, namespace string) (*budgetv1alpha.Overall, error)) *MockMetricDataProvider_GetOverall_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpans provides a mock function for the type MockMetricDataProvider
func (_mock *MockMetricDataProvider) GetSpans(ctx context.Context, input budgetdata.MetricDataInput) ([]*budgetv1alpha.Span, string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetSpans")
	}

	var r0 []*budgetv1alpha.Span
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetdata.MetricDataInput) ([]*budgetv1alpha.Span, string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, budgetdata.MetricDataInput) []*budgetv1alpha.Span); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*budgetv1alpha.Span)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, budgetdata.MetricDataInput) string); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, budgetdata.MetricDataInput) error); ok {
		r2 = returnFunc(ctx, input)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetricDataProvider_GetSpans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpans'
type MockMetricDataProvider_GetSpans_Call struct {
	*mock.Call
}

// GetSpans is a helper method to define mock.On call
//   - ctx context.Context
//   - input budgetdata.MetricDataInput
func (_e *MockMetricDataProvider_Expecter) GetSpans(ctx interface{}, input interface{}) *MockMetricDataProvider_GetSpans_Call {
	return &MockMetricDataProvider_GetSpans_Call{Call: _e.mock.On("GetSpans", ctx, input)}
}

func (_c *MockMetricDataProvider_GetSpans_Call) Run(run func(ctx context.Context, input budgetdata.MetricDataInput)) *MockMetricDataProvider_GetSpans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 budgetdata.MetricDataInput
		if args[1] != nil {
			arg1 = args[1].(budgetdata.MetricDataInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricDataProvider_GetSpans_Call) Return(spans []*budgetv1alpha.Span, s string, err error) *MockMetricDataProvider_GetSpans_Call {
	_c.Call.Return(spans, s, err)
	return _c
}

func (_c *MockMetricDataProvider_GetSpans_Call) RunAndReturn(run func(ctx context.Context, input budgetdata.MetricDataInput) ([]*budgetv1alpha.Span, string, error)) *MockMetricDataProvider_GetSpans_Call {
	_c.Call.Return(run)
	return _c
}
