// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetfiltermock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	"github.com/mydecisive/octant/internal/budget/filter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingController creates a new instance of MockSettingController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingController {
	mock := &MockSettingController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingController is an autogenerated mock type for the SettingController type
type MockSettingController struct {
	mock.Mock
}

type MockSettingController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingController) EXPECT() *MockSettingController_Expecter {
	return &MockSettingController_Expecter{mock: &_m.Mock}
}

// GetFilter provides a mock function for the type MockSettingController
func (_mock *MockSettingController) GetFilter(filterType budgetv1alpha.FilterType, namespace string, connection string) (*budgetv1alpha.Filter, error) {
	ret := _mock.Called(filterType, namespace, connection)

	if len(ret) == 0 {
		panic("no return value specified for GetFilter")
	}

	var r0 *budgetv1alpha.Filter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.FilterType, string, string) (*budgetv1alpha.Filter, error)); ok {
		return returnFunc(filterType, namespace, connection)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.FilterType, string, string) *budgetv1alpha.Filter); ok {
		r0 = returnFunc(filterType, namespace, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*budgetv1alpha.Filter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(budgetv1alpha.FilterType, string, string) error); ok {
		r1 = returnFunc(filterType, namespace, connection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingController_GetFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilter'
type MockSettingController_GetFilter_Call struct {
	*mock.Call
}

// GetFilter is a helper method to define mock.On call
//   - filterType budgetv1alpha.FilterType
//   - namespace string
//   - connection string
func (_e *MockSettingController_Expecter) GetFilter(filterType interface{}, namespace interface{}, connection interface{}) *MockSettingController_GetFilter_Call {
	return &MockSettingController_GetFilter_Call{Call: _e.mock.On("GetFilter", filterType, namespace, connection)}
}

func (_c *MockSettingController_GetFilter_Call) Run(run func(filterType budgetv1alpha.FilterType, namespace string, connection string)) *MockSettingController_GetFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetv1alpha.FilterType
		if args[0] != nil {
			arg0 = args[0].(budgetv1alpha.FilterType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSettingController_GetFilter_Call) Return(filter *budgetv1alpha.Filter, err error) *MockSettingController_GetFilter_Call {
	_c.Call.Return(filter, err)
	return _c
}

func (_c *MockSettingController_GetFilter_Call) RunAndReturn(run func(filterType budgetv1alpha.FilterType, namespace string, connection string) (*budgetv1alpha.Filter, error)) *MockSettingController_GetFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFilter provides a mock function for the type MockSettingController
func (_mock *MockSettingController) UpdateFilter(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter, out chan budgetfilter.UpdateFilterResult) {
	_mock.Called(ctx, namespace, connection, updates, out)
	return
}

// MockSettingController_UpdateFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFilter'
type MockSettingController_UpdateFilter_Call struct {
	*mock.Call
}

// UpdateFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connection string
//   - updates *budgetv1alpha.Filter
//   - out chan budgetfilter.UpdateFilterResult
func (_e *MockSettingController_Expecter) UpdateFilter(ctx interface{}, namespace interface{}, connection interface{}, updates interface{}, out interface{}) *MockSettingController_UpdateFilter_Call {
	return &MockSettingController_UpdateFilter_Call{Call: _e.mock.On("UpdateFilter", ctx, namespace, connection, updates, out)}
}

func (_c *MockSettingController_UpdateFilter_Call) Run(run func(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter, out chan budgetfilter.UpdateFilterResult)) *MockSettingController_UpdateFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *budgetv1alpha.Filter
		if args[3] != nil {
			arg3 = args[3].(*budgetv1alpha.Filter)
		}
		var arg4 chan budgetfilter.UpdateFilterResult
		if args[4] != nil {
			arg4 = args[4].(chan budgetfilter.UpdateFilterResult)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSettingController_UpdateFilter_Call) Return() *MockSettingController_UpdateFilter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSettingController_UpdateFilter_Call) RunAndReturn(run func(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter, out chan budgetfilter.UpdateFilterResult)) *MockSettingController_UpdateFilter_Call {
	_c.Run(run)
	return _c
}
