// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetfiltermock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingController creates a new instance of MockSettingController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingController {
	mock := &MockSettingController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingController is an autogenerated mock type for the SettingController type
type MockSettingController struct {
	mock.Mock
}

type MockSettingController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingController) EXPECT() *MockSettingController_Expecter {
	return &MockSettingController_Expecter{mock: &_m.Mock}
}

// GetFilter provides a mock function for the type MockSettingController
func (_mock *MockSettingController) GetFilter(filterType budgetv1alpha.FilterType, namespace string, connection string) (*budgetv1alpha.Filter, error) {
	ret := _mock.Called(filterType, namespace, connection)

	if len(ret) == 0 {
		panic("no return value specified for GetFilter")
	}

	var r0 *budgetv1alpha.Filter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.FilterType, string, string) (*budgetv1alpha.Filter, error)); ok {
		return returnFunc(filterType, namespace, connection)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.FilterType, string, string) *budgetv1alpha.Filter); ok {
		r0 = returnFunc(filterType, namespace, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*budgetv1alpha.Filter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(budgetv1alpha.FilterType, string, string) error); ok {
		r1 = returnFunc(filterType, namespace, connection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingController_GetFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilter'
type MockSettingController_GetFilter_Call struct {
	*mock.Call
}

// GetFilter is a helper method to define mock.On call
//   - filterType budgetv1alpha.FilterType
//   - namespace string
//   - connection string
func (_e *MockSettingController_Expecter) GetFilter(filterType interface{}, namespace interface{}, connection interface{}) *MockSettingController_GetFilter_Call {
	return &MockSettingController_GetFilter_Call{Call: _e.mock.On("GetFilter", filterType, namespace, connection)}
}

func (_c *MockSettingController_GetFilter_Call) Run(run func(filterType budgetv1alpha.FilterType, namespace string, connection string)) *MockSettingController_GetFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetv1alpha.FilterType
		if args[0] != nil {
			arg0 = args[0].(budgetv1alpha.FilterType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSettingController_GetFilter_Call) Return(filter *budgetv1alpha.Filter, err error) *MockSettingController_GetFilter_Call {
	_c.Call.Return(filter, err)
	return _c
}

func (_c *MockSettingController_GetFilter_Call) RunAndReturn(run func(filterType budgetv1alpha.FilterType, namespace string, connection string) (*budgetv1alpha.Filter, error)) *MockSettingController_GetFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFilter provides a mock function for the type MockSettingController
func (_mock *MockSettingController) UpdateFilter(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter) error {
	ret := _mock.Called(ctx, namespace, connection, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFilter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *budgetv1alpha.Filter) error); ok {
		r0 = returnFunc(ctx, namespace, connection, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingController_UpdateFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFilter'
type MockSettingController_UpdateFilter_Call struct {
	*mock.Call
}

// UpdateFilter is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connection string
//   - updates *budgetv1alpha.Filter
func (_e *MockSettingController_Expecter) UpdateFilter(ctx interface{}, namespace interface{}, connection interface{}, updates interface{}) *MockSettingController_UpdateFilter_Call {
	return &MockSettingController_UpdateFilter_Call{Call: _e.mock.On("UpdateFilter", ctx, namespace, connection, updates)}
}

func (_c *MockSettingController_UpdateFilter_Call) Run(run func(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter)) *MockSettingController_UpdateFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *budgetv1alpha.Filter
		if args[3] != nil {
			arg3 = args[3].(*budgetv1alpha.Filter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSettingController_UpdateFilter_Call) Return(err error) *MockSettingController_UpdateFilter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingController_UpdateFilter_Call) RunAndReturn(run func(ctx context.Context, namespace string, connection string, updates *budgetv1alpha.Filter) error) *MockSettingController_UpdateFilter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVariableAccessor creates a new instance of MockVariableAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVariableAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVariableAccessor {
	mock := &MockVariableAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVariableAccessor is an autogenerated mock type for the VariableAccessor type
type MockVariableAccessor struct {
	mock.Mock
}

type MockVariableAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVariableAccessor) EXPECT() *MockVariableAccessor_Expecter {
	return &MockVariableAccessor_Expecter{mock: &_m.Mock}
}

// GetVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) GetVariable(namespace string, hubName string, varName string) (string, error) {
	ret := _mock.Called(namespace, hubName, varName)

	if len(ret) == 0 {
		panic("no return value specified for GetVariable")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(namespace, hubName, varName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(namespace, hubName, varName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(namespace, hubName, varName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableAccessor_GetVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariable'
type MockVariableAccessor_GetVariable_Call struct {
	*mock.Call
}

// GetVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
func (_e *MockVariableAccessor_Expecter) GetVariable(namespace interface{}, hubName interface{}, varName interface{}) *MockVariableAccessor_GetVariable_Call {
	return &MockVariableAccessor_GetVariable_Call{Call: _e.mock.On("GetVariable", namespace, hubName, varName)}
}

func (_c *MockVariableAccessor_GetVariable_Call) Run(run func(namespace string, hubName string, varName string)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) Return(s string, err error) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string) (string, error)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) UpdateVariable(namespace string, hubName string, varName string, value any) error {
	ret := _mock.Called(namespace, hubName, varName, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, any) error); ok {
		r0 = returnFunc(namespace, hubName, varName, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVariableAccessor_UpdateVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariable'
type MockVariableAccessor_UpdateVariable_Call struct {
	*mock.Call
}

// UpdateVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
//   - value any
func (_e *MockVariableAccessor_Expecter) UpdateVariable(namespace interface{}, hubName interface{}, varName interface{}, value interface{}) *MockVariableAccessor_UpdateVariable_Call {
	return &MockVariableAccessor_UpdateVariable_Call{Call: _e.mock.On("UpdateVariable", namespace, hubName, varName, value)}
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Run(run func(namespace string, hubName string, varName string, value any)) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Return(err error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string, value any) error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(run)
	return _c
}
