version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - exhaustive
    - godox
    - gomoddirectives # needed for https://argo-cd.readthedocs.io/en/stable/user-guide/import/
    - nlreturn
    - noinlineerr
    - nolintlint
    - prealloc
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - tagalign # Annoying and wrong
    - gomoddirectives # incompatible with our argo import

  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 85
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - paramTypeCombine
        - rangeValCopy
        - whyNoLint
        - unnamedResult
    govet:
      enable-all: true
      disable:
        - fieldalignment
    testifylint:
      enable-all: true
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          exclude: [ "**/*_test.go" ]
          disabled: true
        - name: blank-imports
        - name: cognitive-complexity
          exclude: [ "**/*_test.go" ]
          disabled: true
        - name: cyclomatic
          exclude: [ "**/*_test.go" ]
          disabled: true
        - name: early-return
          arguments:
            - preserveScope
        - name: exported
          disabled: true
        - name: function-length
          exclude: [ "**/*_test.go" ]
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: package-comments
          disabled: true
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: unchecked-type-assertion
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: package-directory-mismatch
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: enforce-switch-style
          disabled: true
        - name: max-public-structs
          disabled: true
          path: api/v1/.*\.go
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: camel
          xml: camel
          toml: camel
          bson: camel
          avro: snake
          mapstructure: kebab
          env: upperSnake
          envconfig: upperSnake
    gosec:
      excludes:
        - G104 # Handled by errcheck
    unused:
      exported-fields-are-used: false
    forbidigo:
      analyze-types: true
      exclude-godoc-examples: false
      forbid:
        - pattern: ^print(ln)?$
          msg: do not commit print statements
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
        - pattern: log.Fatal
          msg: use zap instead
        - pattern: ^os.Exit$
          msg: return errors and exit from main()
        - pattern: zap.Any
          msg: define a MarshalLogObject
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: use zap
            - pkg: "github.com/pkg/errors"
              desc: should be replaced by standard lib errors package
            - pkg: "io/ioutil"
              desc: deprecated
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - cyclop
          - dupl
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - goconst
          - gosec
          - lll
          - maintidx
          - tagliatelle
          - unparam
      - path: internal/mock/.*
        linters:
          - all
      - path: internal/budget/data/db/public/table/.*
        linters:
          - all
      - path: internal/connection/*
        linters:
          - tagliatelle
      - path: internal/integration/*
        linters:
          - tagliatelle
      - path: internal/config/*
        linters:
          - revive
      - path: api/v1/*
        linters:
          - lll
issues:
    max-issues-per-linter: 0
    max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: false
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
