coverage:
  status:
    patch:
      default:
        target: 80%
ignore:
  - "cmd/"
  - "internal/config"
  - "internal/mock"
  - "web/"
  - "internal/test"
  - "internal/mock"
  - "internal/registry"
  - "internal/budget/data/db"
  - "internal/rpc/server.go"
  - "**/*_enumer.go"
