package compression

import (
	"archive/zip"
	"bytes"
	"io"
	"os"
	"testing"
	"time"

	octantv1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/go-faker/faker/v4"
	"github.com/mydecisive/octant/internal/config"
	"github.com/mydecisive/octant/internal/connection"
	connectionmocks "github.com/mydecisive/octant/internal/mock/connection"
	"github.com/mydecisive/octant/internal/telemetry"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func TestConnectionManifestCompressor_CreateCompressed(t *testing.T) {
	t.Parallel()

	generator := connection.NewConnectionManifestGenerator(&config.Configuration{
		ServiceAccountName: faker.Word(),
		CurrentNamespace:   faker.Word(),
	})

	target := NewConnectionManifestCompressor(generator)
	actual, err := target.CreateCompressed(t.Context(), connection.ManifestGeneratorInput{
		Namespace:  faker.Word(),
		Connection: faker.Word(),
		Telemetries: []octantv1alpha.MLTType{
			octantv1alpha.MLTType_MLT_TYPE_METRIC,
		},
		DeploymentType: octantv1alpha.DeploymentType_DEPLOYMENT_TYPE_ARGO_SIDELOAD,
	})
	require.NoError(t, err)
	assert.NotEmpty(t, actual)
}

func TestConnectionManifestCompressor_ToConnectionData(t *testing.T) {
	t.Parallel()

	generator := connection.NewConnectionManifestGenerator(&config.Configuration{
		ServiceAccountName: faker.Word(),
		CurrentNamespace:   faker.Word(),
	})

	tests := []struct {
		des      string
		in       octantv1alpha.DeploymentType
		expected connection.DeploymentType
	}{
		{"json", octantv1alpha.DeploymentType_DEPLOYMENT_TYPE_ARGO_MANIFEST, connection.ArgoManifestsDeploymentType},
		{"yaml", octantv1alpha.DeploymentType_DEPLOYMENT_TYPE_ARGO_SIDELOAD, connection.ArgoSideloadDeploymentType},
	}
	for _, tt := range tests {
		t.Run(tt.des, func(t *testing.T) {
			t.Parallel()
			tel := []octantv1alpha.MLTType{
				octantv1alpha.MLTType_MLT_TYPE_METRIC,
				octantv1alpha.MLTType_MLT_TYPE_LOG,
				octantv1alpha.MLTType_MLT_TYPE_TRACE,
			}
			target := NewConnectionManifestCompressor(generator)
			actual := target.toConnectionData(tel, tt.in)

			assert.Len(t, actual.TelemetryTypes, 3)
			assert.Contains(t, actual.TelemetryTypes, telemetry.Metrics)
			assert.Contains(t, actual.TelemetryTypes, telemetry.Logs)
			assert.Contains(t, actual.TelemetryTypes, telemetry.Traces)
			assert.Len(t, actual.Destinations, 1)
			assert.Equal(t, tt.expected, actual.Deployment.Type)
		})
	}
}

func TestConnectionManifestCompressor_CompressionTest(t *testing.T) {
	t.Parallel()

	expectedFilename := "deployment.yaml"
	expectedContent := []byte("apiVersion: apps/v1\nkind: Deployment\n")

	mockGenerator := connectionmocks.NewMockManifestGenerator(t)
	mockGenerator.EXPECT().CreateExportableArgoManifests(mock.Anything, mock.Anything).Return(
		map[string][]byte{
			expectedFilename: expectedContent,
		}, nil,
	)

	target := NewConnectionManifestCompressor(mockGenerator)
	actualBuf, err := target.CreateCompressed(t.Context(), connection.ManifestGeneratorInput{
		Namespace:      "test-namespace",
		Connection:     "test-connection",
		Telemetries:    []octantv1alpha.MLTType{octantv1alpha.MLTType_MLT_TYPE_METRIC},
		DeploymentType: octantv1alpha.DeploymentType_DEPLOYMENT_TYPE_ARGO_SIDELOAD,
	})

	require.NoError(t, err)
	require.NotNil(t, actualBuf)
	require.Positive(t, actualBuf.Len(), "Buffer should not be empty")

	// Parse the generated bytes as a ZIP archive
	zipReader, err := zip.NewReader(bytes.NewReader(actualBuf.Bytes()), int64(actualBuf.Len()))
	require.NoError(t, err, "The output must be a structurally valid ZIP archive")
	require.Len(t, zipReader.File, 1, "ZIP archive should contain exactly one file")

	// Inspect the file inside the ZIP
	zipFile := zipReader.File[0]
	assert.Equal(t, expectedFilename, zipFile.Name, "Filename should match the mock output")

	// Verify our explicit Windows-compatibility headers
	assert.Equal(t, uint16(0x14), zipFile.ReaderVersion, "ReaderVersion should be 2.0 (20 -> 0x14)")
	// when we `header.SetMode`, the CreatorVersion gets bitwise updated to include the Unix flag (3)
	assert.Equal(t, uint16(0x314), zipFile.CreatorVersion, "CreatorVersion should be UNIX OS (3) + v2.0 (20) -> 0x314")
	assert.Equal(t, uint16(0x800), zipFile.Flags, "Bit 11 (UTF-8) must be set")
	assert.Equal(t, zip.Deflate, zipFile.Method, "Compression method must be Deflate")
	assert.Equal(t, os.FileMode(0o644), zipFile.Mode(), "Permissions should be 0644")

	// Verify timestamp is recent
	minValidTime := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	assert.True(t, zipFile.Modified.After(minValidTime), "Modified time should be recent")

	// Read the decompressed content and verify it matches the mock exactly
	rc, err := zipFile.Open()
	require.NoError(t, err, "Should be able to open the deflated file inside the zip")
	defer rc.Close() // nolint: errcheck

	decompressedContent, err := io.ReadAll(rc)
	require.NoError(t, err, "Should be able to read the deflated contents")
	assert.Equal(t, expectedContent, decompressedContent, "Decompressed content must match original exactly")
}
