//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OctantInstallEvent) DeepCopyInto(out *OctantInstallEvent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OctantInstallEvent.
func (in *OctantInstallEvent) DeepCopy() *OctantInstallEvent {
	if in == nil {
		return nil
	}
	out := new(OctantInstallEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OctantInstallLog) DeepCopyInto(out *OctantInstallLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OctantInstallLog.
func (in *OctantInstallLog) DeepCopy() *OctantInstallLog {
	if in == nil {
		return nil
	}
	out := new(OctantInstallLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OctantInstallLogList) DeepCopyInto(out *OctantInstallLogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OctantInstallLog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OctantInstallLogList.
func (in *OctantInstallLogList) DeepCopy() *OctantInstallLogList {
	if in == nil {
		return nil
	}
	out := new(OctantInstallLogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OctantInstallLogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OctantInstallLogSpec) DeepCopyInto(out *OctantInstallLogSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]OctantInstallEvent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OctantInstallLogSpec.
func (in *OctantInstallLogSpec) DeepCopy() *OctantInstallLogSpec {
	if in == nil {
		return nil
	}
	out := new(OctantInstallLogSpec)
	in.DeepCopyInto(out)
	return out
}
