apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: octant
          containerPort: {{ .Values.deployment.port }}
          protocol: TCP
        env:
          - name: OCTANT_PORT
            value: "{{ .Values.deployment.port }}"
          - name: PROMETHEUS_ENDPOINT
            value: "{{ .Values.deployment.prometheusEndpoint }}"
          - name: OCTANT_SERVICE_ACCOUNT
            value: "{{ .Values.serviceAccount.name }}"
          - name: OCTANT_DEFAULT_LOG_SAMPLING_RATIO
            value: "{{ .Values.clarity.default.logSamplingRatio }}"
          - name: OCTANT_DEFAULT_LOG_INCLUDE_ERR
            value: "{{ .Values.clarity.default.logIncludeErr }}"
          - name: OCTANT_DEFAULT_TRACE_SAMPLING_RATIO
            value: "{{ .Values.clarity.default.traceSamplingRatio }}"
          - name: OCTANT_DEFAULT_TRACE_INCLUDE_ERR
            value: "{{ .Values.clarity.default.traceIncludeErr }}"
          - name: MDAI_VALIDATOR_VERSION
            value: "{{ .Values.validator.version }}"

