apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.services.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  {{- .Values.services.ports | toYaml | nindent 2 }}
  - name: octant-api
    port: 50051
    protocol: TCP
    targetPort: 50051
