// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package integrationmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIntegration creates a new instance of MockIntegration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntegration[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntegration[T] {
	mock := &MockIntegration[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIntegration is an autogenerated mock type for the Integration type
type MockIntegration[T any] struct {
	mock.Mock
}

type MockIntegration_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockIntegration[T]) EXPECT() *MockIntegration_Expecter[T] {
	return &MockIntegration_Expecter[T]{mock: &_m.Mock}
}

// DeleteIntegration provides a mock function for the type MockIntegration
func (_mock *MockIntegration[T]) DeleteIntegration(ctx context.Context, namespace string, integrationName string) error {
	ret := _mock.Called(ctx, namespace, integrationName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIntegration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, integrationName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIntegration_DeleteIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIntegration'
type MockIntegration_DeleteIntegration_Call[T any] struct {
	*mock.Call
}

// DeleteIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - integrationName string
func (_e *MockIntegration_Expecter[T]) DeleteIntegration(ctx interface{}, namespace interface{}, integrationName interface{}) *MockIntegration_DeleteIntegration_Call[T] {
	return &MockIntegration_DeleteIntegration_Call[T]{Call: _e.mock.On("DeleteIntegration", ctx, namespace, integrationName)}
}

func (_c *MockIntegration_DeleteIntegration_Call[T]) Run(run func(ctx context.Context, namespace string, integrationName string)) *MockIntegration_DeleteIntegration_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIntegration_DeleteIntegration_Call[T]) Return(err error) *MockIntegration_DeleteIntegration_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIntegration_DeleteIntegration_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string, integrationName string) error) *MockIntegration_DeleteIntegration_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetIntegrations provides a mock function for the type MockIntegration
func (_mock *MockIntegration[T]) GetIntegrations(ctx context.Context, namespace string) (map[string]T, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetIntegrations")
	}

	var r0 map[string]T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]T, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]T); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIntegration_GetIntegrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntegrations'
type MockIntegration_GetIntegrations_Call[T any] struct {
	*mock.Call
}

// GetIntegrations is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockIntegration_Expecter[T]) GetIntegrations(ctx interface{}, namespace interface{}) *MockIntegration_GetIntegrations_Call[T] {
	return &MockIntegration_GetIntegrations_Call[T]{Call: _e.mock.On("GetIntegrations", ctx, namespace)}
}

func (_c *MockIntegration_GetIntegrations_Call[T]) Run(run func(ctx context.Context, namespace string)) *MockIntegration_GetIntegrations_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIntegration_GetIntegrations_Call[T]) Return(stringToV map[string]T, err error) *MockIntegration_GetIntegrations_Call[T] {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockIntegration_GetIntegrations_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string) (map[string]T, error)) *MockIntegration_GetIntegrations_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SetIntegration provides a mock function for the type MockIntegration
func (_mock *MockIntegration[T]) SetIntegration(ctx context.Context, namespace string, integrationName string, integrationData T) error {
	ret := _mock.Called(ctx, namespace, integrationName, integrationData)

	if len(ret) == 0 {
		panic("no return value specified for SetIntegration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, T) error); ok {
		r0 = returnFunc(ctx, namespace, integrationName, integrationData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIntegration_SetIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIntegration'
type MockIntegration_SetIntegration_Call[T any] struct {
	*mock.Call
}

// SetIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - integrationName string
//   - integrationData T
func (_e *MockIntegration_Expecter[T]) SetIntegration(ctx interface{}, namespace interface{}, integrationName interface{}, integrationData interface{}) *MockIntegration_SetIntegration_Call[T] {
	return &MockIntegration_SetIntegration_Call[T]{Call: _e.mock.On("SetIntegration", ctx, namespace, integrationName, integrationData)}
}

func (_c *MockIntegration_SetIntegration_Call[T]) Run(run func(ctx context.Context, namespace string, integrationName string, integrationData T)) *MockIntegration_SetIntegration_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 T
		if args[3] != nil {
			arg3 = args[3].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIntegration_SetIntegration_Call[T]) Return(err error) *MockIntegration_SetIntegration_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIntegration_SetIntegration_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string, integrationName string, integrationData T) error) *MockIntegration_SetIntegration_Call[T] {
	_c.Call.Return(run)
	return _c
}
