// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetdbmock

import (
	"context"

	"github.com/mydecisive/octant/internal/budget/data/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabaseAccessBuilder creates a new instance of MockDatabaseAccessBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseAccessBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseAccessBuilder {
	mock := &MockDatabaseAccessBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseAccessBuilder is an autogenerated mock type for the DatabaseAccessBuilder type
type MockDatabaseAccessBuilder struct {
	mock.Mock
}

type MockDatabaseAccessBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseAccessBuilder) EXPECT() *MockDatabaseAccessBuilder_Expecter {
	return &MockDatabaseAccessBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockDatabaseAccessBuilder
func (_mock *MockDatabaseAccessBuilder) Build(ctx context.Context, namespace string) (*db.Database, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *db.Database
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*db.Database, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *db.Database); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Database)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseAccessBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockDatabaseAccessBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockDatabaseAccessBuilder_Expecter) Build(ctx interface{}, namespace interface{}) *MockDatabaseAccessBuilder_Build_Call {
	return &MockDatabaseAccessBuilder_Build_Call{Call: _e.mock.On("Build", ctx, namespace)}
}

func (_c *MockDatabaseAccessBuilder_Build_Call) Run(run func(ctx context.Context, namespace string)) *MockDatabaseAccessBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseAccessBuilder_Build_Call) Return(database *db.Database, err error) *MockDatabaseAccessBuilder_Build_Call {
	_c.Call.Return(database, err)
	return _c
}

func (_c *MockDatabaseAccessBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, namespace string) (*db.Database, error)) *MockDatabaseAccessBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
