---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: octant-manager-role
rules:
- apiGroups:
  - octant.mydecisive.ai
  resources:
  - octantinstalllogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
