// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package compressionmock

import (
	"bytes"
	"context"

	"github.com/mydecisive/octant/internal/connection"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManifestCompressor creates a new instance of MockManifestCompressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifestCompressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifestCompressor {
	mock := &MockManifestCompressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifestCompressor is an autogenerated mock type for the ManifestCompressor type
type MockManifestCompressor struct {
	mock.Mock
}

type MockManifestCompressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifestCompressor) EXPECT() *MockManifestCompressor_Expecter {
	return &MockManifestCompressor_Expecter{mock: &_m.Mock}
}

// CreateCompressed provides a mock function for the type MockManifestCompressor
func (_mock *MockManifestCompressor) CreateCompressed(ctx context.Context, input connection.CompressionInput) (*bytes.Buffer, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompressed")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.CompressionInput) (*bytes.Buffer, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.CompressionInput) *bytes.Buffer); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.CompressionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestCompressor_CreateCompressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompressed'
type MockManifestCompressor_CreateCompressed_Call struct {
	*mock.Call
}

// CreateCompressed is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.CompressionInput
func (_e *MockManifestCompressor_Expecter) CreateCompressed(ctx interface{}, input interface{}) *MockManifestCompressor_CreateCompressed_Call {
	return &MockManifestCompressor_CreateCompressed_Call{Call: _e.mock.On("CreateCompressed", ctx, input)}
}

func (_c *MockManifestCompressor_CreateCompressed_Call) Run(run func(ctx context.Context, input connection.CompressionInput)) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.CompressionInput
		if args[1] != nil {
			arg1 = args[1].(connection.CompressionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestCompressor_CreateCompressed_Call) Return(buffer *bytes.Buffer, err error) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockManifestCompressor_CreateCompressed_Call) RunAndReturn(run func(ctx context.Context, input connection.CompressionInput) (*bytes.Buffer, error)) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Return(run)
	return _c
}
