//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ItemsSentByServiceTotal = newItemsSentByServiceTotalTable("public", "items_sent_by_service_total", "")

type itemsSentByServiceTotalTable struct {
	mysql.Table

	// Columns
	Cluster           mysql.ColumnString
	DataType          mysql.ColumnString
	GreptimeRemote    mysql.ColumnString
	GreptimeTimestamp mysql.ColumnString
	GreptimeValue     mysql.ColumnFloat
	Instance          mysql.ColumnString
	Job               mysql.ColumnString
	Prometheus        mysql.ColumnString
	PrometheusReplica mysql.ColumnString
	Service           mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ItemsSentByServiceTotalTable struct {
	itemsSentByServiceTotalTable

	NEW itemsSentByServiceTotalTable
}

// AS creates new ItemsSentByServiceTotalTable with assigned alias
func (a ItemsSentByServiceTotalTable) AS(alias string) *ItemsSentByServiceTotalTable {
	return newItemsSentByServiceTotalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ItemsSentByServiceTotalTable with assigned schema name
func (a ItemsSentByServiceTotalTable) FromSchema(schemaName string) *ItemsSentByServiceTotalTable {
	return newItemsSentByServiceTotalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ItemsSentByServiceTotalTable with assigned table prefix
func (a ItemsSentByServiceTotalTable) WithPrefix(prefix string) *ItemsSentByServiceTotalTable {
	return newItemsSentByServiceTotalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ItemsSentByServiceTotalTable with assigned table suffix
func (a ItemsSentByServiceTotalTable) WithSuffix(suffix string) *ItemsSentByServiceTotalTable {
	return newItemsSentByServiceTotalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newItemsSentByServiceTotalTable(schemaName, tableName, alias string) *ItemsSentByServiceTotalTable {
	return &ItemsSentByServiceTotalTable{
		itemsSentByServiceTotalTable: newItemsSentByServiceTotalTableImpl(schemaName, tableName, alias),
		NEW:                          newItemsSentByServiceTotalTableImpl("", "new", ""),
	}
}

func newItemsSentByServiceTotalTableImpl(schemaName, tableName, alias string) itemsSentByServiceTotalTable {
	var (
		ClusterColumn           = mysql.StringColumn("cluster")
		DataTypeColumn          = mysql.StringColumn("data_type")
		GreptimeRemoteColumn    = mysql.StringColumn("greptime_remote")
		GreptimeTimestampColumn = mysql.StringColumn("greptime_timestamp")
		GreptimeValueColumn     = mysql.FloatColumn("greptime_value")
		InstanceColumn          = mysql.StringColumn("instance")
		JobColumn               = mysql.StringColumn("job")
		PrometheusColumn        = mysql.StringColumn("prometheus")
		PrometheusReplicaColumn = mysql.StringColumn("prometheus_replica")
		ServiceColumn           = mysql.StringColumn("service")
		allColumns              = mysql.ColumnList{ClusterColumn, DataTypeColumn, GreptimeRemoteColumn, GreptimeTimestampColumn, GreptimeValueColumn, InstanceColumn, JobColumn, PrometheusColumn, PrometheusReplicaColumn, ServiceColumn}
		mutableColumns          = mysql.ColumnList{GreptimeTimestampColumn, GreptimeValueColumn}
		defaultColumns          = mysql.ColumnList{}
	)

	return itemsSentByServiceTotalTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Cluster:           ClusterColumn,
		DataType:          DataTypeColumn,
		GreptimeRemote:    GreptimeRemoteColumn,
		GreptimeTimestamp: GreptimeTimestampColumn,
		GreptimeValue:     GreptimeValueColumn,
		Instance:          InstanceColumn,
		Job:               JobColumn,
		Prometheus:        PrometheusColumn,
		PrometheusReplica: PrometheusReplicaColumn,
		Service:           ServiceColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
