//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ReceivedSpanRootCountTotal = newReceivedSpanRootCountTotalTable("public", "received_span_root_count_total", "")

type receivedSpanRootCountTotalTable struct {
	mysql.Table

	// Columns
	Cluster               mysql.ColumnString
	Container             mysql.ColumnString
	Endpoint              mysql.ColumnString
	ExportedJob           mysql.ColumnString
	GreptimeRemote        mysql.ColumnString
	GreptimeTimestamp     mysql.ColumnString
	GreptimeValue         mysql.ColumnFloat
	Instance              mysql.ColumnString
	Job                   mysql.ColumnString
	Namespace             mysql.ColumnString
	OtelScopeName         mysql.ColumnString
	Pod                   mysql.ColumnString
	ProcessRuntimeVersion mysql.ColumnString
	Prometheus            mysql.ColumnString
	PrometheusReplica     mysql.ColumnString
	Service               mysql.ColumnString
	ServiceName           mysql.ColumnString
	SpanName              mysql.ColumnString
	SpanService           mysql.ColumnString
	TelemetrySdkLanguage  mysql.ColumnString
	TelemetrySdkName      mysql.ColumnString
	TelemetrySdkVersion   mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ReceivedSpanRootCountTotalTable struct {
	receivedSpanRootCountTotalTable

	NEW receivedSpanRootCountTotalTable
}

// AS creates new ReceivedSpanRootCountTotalTable with assigned alias
func (a ReceivedSpanRootCountTotalTable) AS(alias string) *ReceivedSpanRootCountTotalTable {
	return newReceivedSpanRootCountTotalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReceivedSpanRootCountTotalTable with assigned schema name
func (a ReceivedSpanRootCountTotalTable) FromSchema(schemaName string) *ReceivedSpanRootCountTotalTable {
	return newReceivedSpanRootCountTotalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReceivedSpanRootCountTotalTable with assigned table prefix
func (a ReceivedSpanRootCountTotalTable) WithPrefix(prefix string) *ReceivedSpanRootCountTotalTable {
	return newReceivedSpanRootCountTotalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReceivedSpanRootCountTotalTable with assigned table suffix
func (a ReceivedSpanRootCountTotalTable) WithSuffix(suffix string) *ReceivedSpanRootCountTotalTable {
	return newReceivedSpanRootCountTotalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReceivedSpanRootCountTotalTable(schemaName, tableName, alias string) *ReceivedSpanRootCountTotalTable {
	return &ReceivedSpanRootCountTotalTable{
		receivedSpanRootCountTotalTable: newReceivedSpanRootCountTotalTableImpl(schemaName, tableName, alias),
		NEW:                             newReceivedSpanRootCountTotalTableImpl("", "new", ""),
	}
}

func newReceivedSpanRootCountTotalTableImpl(schemaName, tableName, alias string) receivedSpanRootCountTotalTable {
	var (
		ClusterColumn               = mysql.StringColumn("cluster")
		ContainerColumn             = mysql.StringColumn("container")
		EndpointColumn              = mysql.StringColumn("endpoint")
		ExportedJobColumn           = mysql.StringColumn("exported_job")
		GreptimeRemoteColumn        = mysql.StringColumn("greptime_remote")
		GreptimeTimestampColumn     = mysql.StringColumn("greptime_timestamp")
		GreptimeValueColumn         = mysql.FloatColumn("greptime_value")
		InstanceColumn              = mysql.StringColumn("instance")
		JobColumn                   = mysql.StringColumn("job")
		NamespaceColumn             = mysql.StringColumn("namespace")
		OtelScopeNameColumn         = mysql.StringColumn("otel_scope_name")
		PodColumn                   = mysql.StringColumn("pod")
		ProcessRuntimeVersionColumn = mysql.StringColumn("process_runtime_version")
		PrometheusColumn            = mysql.StringColumn("prometheus")
		PrometheusReplicaColumn     = mysql.StringColumn("prometheus_replica")
		ServiceColumn               = mysql.StringColumn("service")
		ServiceNameColumn           = mysql.StringColumn("service_name")
		SpanNameColumn              = mysql.StringColumn("span_name")
		SpanServiceColumn           = mysql.StringColumn("span_service")
		TelemetrySdkLanguageColumn  = mysql.StringColumn("telemetry_sdk_language")
		TelemetrySdkNameColumn      = mysql.StringColumn("telemetry_sdk_name")
		TelemetrySdkVersionColumn   = mysql.StringColumn("telemetry_sdk_version")
		allColumns                  = mysql.ColumnList{ClusterColumn, ContainerColumn, EndpointColumn, ExportedJobColumn, GreptimeRemoteColumn, GreptimeTimestampColumn, GreptimeValueColumn, InstanceColumn, JobColumn, NamespaceColumn, OtelScopeNameColumn, PodColumn, ProcessRuntimeVersionColumn, PrometheusColumn, PrometheusReplicaColumn, ServiceColumn, ServiceNameColumn, SpanNameColumn, SpanServiceColumn, TelemetrySdkLanguageColumn, TelemetrySdkNameColumn, TelemetrySdkVersionColumn}
		mutableColumns              = mysql.ColumnList{GreptimeTimestampColumn, GreptimeValueColumn}
		defaultColumns              = mysql.ColumnList{}
	)

	return receivedSpanRootCountTotalTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Cluster:               ClusterColumn,
		Container:             ContainerColumn,
		Endpoint:              EndpointColumn,
		ExportedJob:           ExportedJobColumn,
		GreptimeRemote:        GreptimeRemoteColumn,
		GreptimeTimestamp:     GreptimeTimestampColumn,
		GreptimeValue:         GreptimeValueColumn,
		Instance:              InstanceColumn,
		Job:                   JobColumn,
		Namespace:             NamespaceColumn,
		OtelScopeName:         OtelScopeNameColumn,
		Pod:                   PodColumn,
		ProcessRuntimeVersion: ProcessRuntimeVersionColumn,
		Prometheus:            PrometheusColumn,
		PrometheusReplica:     PrometheusReplicaColumn,
		Service:               ServiceColumn,
		ServiceName:           ServiceNameColumn,
		SpanName:              SpanNameColumn,
		SpanService:           SpanServiceColumn,
		TelemetrySdkLanguage:  TelemetrySdkLanguageColumn,
		TelemetrySdkName:      TelemetrySdkNameColumn,
		TelemetrySdkVersion:   TelemetrySdkVersionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
