//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SentSpanCountTotal = newSentSpanCountTotalTable("public", "sent_span_count_total", "")

type sentSpanCountTotalTable struct {
	mysql.Table

	// Columns
	Cluster               mysql.ColumnString
	Container             mysql.ColumnString
	Endpoint              mysql.ColumnString
	ExportedJob           mysql.ColumnString
	GreptimeRemote        mysql.ColumnString
	GreptimeTimestamp     mysql.ColumnString
	GreptimeValue         mysql.ColumnFloat
	Instance              mysql.ColumnString
	Job                   mysql.ColumnString
	Namespace             mysql.ColumnString
	OtelScopeName         mysql.ColumnString
	Pod                   mysql.ColumnString
	ProcessRuntimeVersion mysql.ColumnString
	Prometheus            mysql.ColumnString
	PrometheusReplica     mysql.ColumnString
	Service               mysql.ColumnString
	ServiceName           mysql.ColumnString
	SpanName              mysql.ColumnString
	SpanService           mysql.ColumnString
	TelemetrySdkLanguage  mysql.ColumnString
	TelemetrySdkName      mysql.ColumnString
	TelemetrySdkVersion   mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type SentSpanCountTotalTable struct {
	sentSpanCountTotalTable

	NEW sentSpanCountTotalTable
}

// AS creates new SentSpanCountTotalTable with assigned alias
func (a SentSpanCountTotalTable) AS(alias string) *SentSpanCountTotalTable {
	return newSentSpanCountTotalTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SentSpanCountTotalTable with assigned schema name
func (a SentSpanCountTotalTable) FromSchema(schemaName string) *SentSpanCountTotalTable {
	return newSentSpanCountTotalTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SentSpanCountTotalTable with assigned table prefix
func (a SentSpanCountTotalTable) WithPrefix(prefix string) *SentSpanCountTotalTable {
	return newSentSpanCountTotalTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SentSpanCountTotalTable with assigned table suffix
func (a SentSpanCountTotalTable) WithSuffix(suffix string) *SentSpanCountTotalTable {
	return newSentSpanCountTotalTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSentSpanCountTotalTable(schemaName, tableName, alias string) *SentSpanCountTotalTable {
	return &SentSpanCountTotalTable{
		sentSpanCountTotalTable: newSentSpanCountTotalTableImpl(schemaName, tableName, alias),
		NEW:                     newSentSpanCountTotalTableImpl("", "new", ""),
	}
}

func newSentSpanCountTotalTableImpl(schemaName, tableName, alias string) sentSpanCountTotalTable {
	var (
		ClusterColumn               = mysql.StringColumn("cluster")
		ContainerColumn             = mysql.StringColumn("container")
		EndpointColumn              = mysql.StringColumn("endpoint")
		ExportedJobColumn           = mysql.StringColumn("exported_job")
		GreptimeRemoteColumn        = mysql.StringColumn("greptime_remote")
		GreptimeTimestampColumn     = mysql.StringColumn("greptime_timestamp")
		GreptimeValueColumn         = mysql.FloatColumn("greptime_value")
		InstanceColumn              = mysql.StringColumn("instance")
		JobColumn                   = mysql.StringColumn("job")
		NamespaceColumn             = mysql.StringColumn("namespace")
		OtelScopeNameColumn         = mysql.StringColumn("otel_scope_name")
		PodColumn                   = mysql.StringColumn("pod")
		ProcessRuntimeVersionColumn = mysql.StringColumn("process_runtime_version")
		PrometheusColumn            = mysql.StringColumn("prometheus")
		PrometheusReplicaColumn     = mysql.StringColumn("prometheus_replica")
		ServiceColumn               = mysql.StringColumn("service")
		ServiceNameColumn           = mysql.StringColumn("service_name")
		SpanNameColumn              = mysql.StringColumn("span_name")
		SpanServiceColumn           = mysql.StringColumn("span_service")
		TelemetrySdkLanguageColumn  = mysql.StringColumn("telemetry_sdk_language")
		TelemetrySdkNameColumn      = mysql.StringColumn("telemetry_sdk_name")
		TelemetrySdkVersionColumn   = mysql.StringColumn("telemetry_sdk_version")
		allColumns                  = mysql.ColumnList{ClusterColumn, ContainerColumn, EndpointColumn, ExportedJobColumn, GreptimeRemoteColumn, GreptimeTimestampColumn, GreptimeValueColumn, InstanceColumn, JobColumn, NamespaceColumn, OtelScopeNameColumn, PodColumn, ProcessRuntimeVersionColumn, PrometheusColumn, PrometheusReplicaColumn, ServiceColumn, ServiceNameColumn, SpanNameColumn, SpanServiceColumn, TelemetrySdkLanguageColumn, TelemetrySdkNameColumn, TelemetrySdkVersionColumn}
		mutableColumns              = mysql.ColumnList{GreptimeTimestampColumn, GreptimeValueColumn}
		defaultColumns              = mysql.ColumnList{}
	)

	return sentSpanCountTotalTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Cluster:               ClusterColumn,
		Container:             ContainerColumn,
		Endpoint:              EndpointColumn,
		ExportedJob:           ExportedJobColumn,
		GreptimeRemote:        GreptimeRemoteColumn,
		GreptimeTimestamp:     GreptimeTimestampColumn,
		GreptimeValue:         GreptimeValueColumn,
		Instance:              InstanceColumn,
		Job:                   JobColumn,
		Namespace:             NamespaceColumn,
		OtelScopeName:         OtelScopeNameColumn,
		Pod:                   PodColumn,
		ProcessRuntimeVersion: ProcessRuntimeVersionColumn,
		Prometheus:            PrometheusColumn,
		PrometheusReplica:     PrometheusReplicaColumn,
		Service:               ServiceColumn,
		ServiceName:           ServiceNameColumn,
		SpanName:              SpanNameColumn,
		SpanService:           SpanServiceColumn,
		TelemetrySdkLanguage:  TelemetrySdkLanguageColumn,
		TelemetrySdkName:      TelemetrySdkNameColumn,
		TelemetrySdkVersion:   TelemetrySdkVersionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
