//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	BytesReceivedByServiceTotal = BytesReceivedByServiceTotal.FromSchema(schema)
	BytesSentByServiceTotal = BytesSentByServiceTotal.FromSchema(schema)
	ItemsReceivedByServiceTotal = ItemsReceivedByServiceTotal.FromSchema(schema)
	ItemsSentByServiceTotal = ItemsSentByServiceTotal.FromSchema(schema)
	ReceivedSpanCountTotal = ReceivedSpanCountTotal.FromSchema(schema)
	ReceivedSpanRootCountTotal = ReceivedSpanRootCountTotal.FromSchema(schema)
	SentSpanCountTotal = SentSpanCountTotal.FromSchema(schema)
	SentSpanRootCountTotal = SentSpanRootCountTotal.FromSchema(schema)
	TraceRootTopology1m = TraceRootTopology1m.FromSchema(schema)
}
