//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var TraceRootTopology1m = newTraceRootTopology1mTable("public", "trace_root_topology_1m", "")

type traceRootTopology1mTable struct {
	mysql.Table

	// Columns
	TimeWindow      mysql.ColumnString
	RootID          mysql.ColumnString
	BreadthSketch   mysql.ColumnBlob
	DepthSketch     mysql.ColumnBlob
	DurationSketch  mysql.ColumnBlob
	TraceCount      mysql.ColumnInteger
	ErrorCountTotal mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type TraceRootTopology1mTable struct {
	traceRootTopology1mTable

	NEW traceRootTopology1mTable
}

// AS creates new TraceRootTopology1mTable with assigned alias
func (a TraceRootTopology1mTable) AS(alias string) *TraceRootTopology1mTable {
	return newTraceRootTopology1mTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TraceRootTopology1mTable with assigned schema name
func (a TraceRootTopology1mTable) FromSchema(schemaName string) *TraceRootTopology1mTable {
	return newTraceRootTopology1mTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TraceRootTopology1mTable with assigned table prefix
func (a TraceRootTopology1mTable) WithPrefix(prefix string) *TraceRootTopology1mTable {
	return newTraceRootTopology1mTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TraceRootTopology1mTable with assigned table suffix
func (a TraceRootTopology1mTable) WithSuffix(suffix string) *TraceRootTopology1mTable {
	return newTraceRootTopology1mTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTraceRootTopology1mTable(schemaName, tableName, alias string) *TraceRootTopology1mTable {
	return &TraceRootTopology1mTable{
		traceRootTopology1mTable: newTraceRootTopology1mTableImpl(schemaName, tableName, alias),
		NEW:                      newTraceRootTopology1mTableImpl("", "new", ""),
	}
}

func newTraceRootTopology1mTableImpl(schemaName, tableName, alias string) traceRootTopology1mTable {
	var (
		TimeWindowColumn      = mysql.StringColumn("time_window")
		RootIDColumn          = mysql.StringColumn("root_id")
		BreadthSketchColumn   = mysql.BlobColumn("breadth_sketch")
		DepthSketchColumn     = mysql.BlobColumn("depth_sketch")
		DurationSketchColumn  = mysql.BlobColumn("duration_sketch")
		TraceCountColumn      = mysql.IntegerColumn("trace_count")
		ErrorCountTotalColumn = mysql.IntegerColumn("error_count_total")
		allColumns            = mysql.ColumnList{TimeWindowColumn, RootIDColumn, BreadthSketchColumn, DepthSketchColumn, DurationSketchColumn, TraceCountColumn, ErrorCountTotalColumn}
		mutableColumns        = mysql.ColumnList{TimeWindowColumn, BreadthSketchColumn, DepthSketchColumn, DurationSketchColumn, TraceCountColumn, ErrorCountTotalColumn}
		defaultColumns        = mysql.ColumnList{}
	)

	return traceRootTopology1mTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TimeWindow:      TimeWindowColumn,
		RootID:          RootIDColumn,
		BreadthSketch:   BreadthSketchColumn,
		DepthSketch:     DepthSketchColumn,
		DurationSketch:  DurationSketchColumn,
		TraceCount:      TraceCountColumn,
		ErrorCountTotal: ErrorCountTotalColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
