package manifest

import (
	"archive/zip"
	"bytes"
	"io"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestZipCompressor_Compress(t *testing.T) {
	t.Parallel()

	expectedFilename := "deployment.yaml"
	expectedContent := []byte("apiVersion: apps/v1\nkind: Deployment\n")
	manifest := map[string][]byte{
		expectedFilename: expectedContent,
	}

	target := NewZipCompressor()
	actualBuf, err := target.Compress(t.Context(), manifest)

	require.NoError(t, err)
	require.NotNil(t, actualBuf)
	require.Positive(t, actualBuf.Len(), "Buffer should not be empty")

	// Parse the generated bytes as a ZIP archive
	zipReader, err := zip.NewReader(bytes.NewReader(actualBuf.Bytes()), int64(actualBuf.Len()))
	require.NoError(t, err, "The output must be a structurally valid ZIP archive")
	require.Len(t, zipReader.File, 1, "ZIP archive should contain exactly one file")

	// Inspect the file inside the ZIP
	zipFile := zipReader.File[0]
	assert.Equal(t, expectedFilename, zipFile.Name, "Filename should match the mock output")

	// Verify our explicit Windows-compatibility headers
	assert.Equal(t, uint16(0x14), zipFile.ReaderVersion, "ReaderVersion should be 2.0 (20 -> 0x14)")
	// when we `header.SetMode`, the CreatorVersion gets bitwise updated to include the Unix flag (3)
	assert.Equal(t, uint16(0x314), zipFile.CreatorVersion, "CreatorVersion should be UNIX OS (3) + v2.0 (20) -> 0x314")
	assert.Equal(t, uint16(0x800), zipFile.Flags, "Bit 11 (UTF-8) must be set")
	assert.Equal(t, zip.Deflate, zipFile.Method, "Compression method must be Deflate")
	assert.Equal(t, os.FileMode(0o644), zipFile.Mode(), "Permissions should be 0644")

	// Verify timestamp is recent
	minValidTime := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	assert.True(t, zipFile.Modified.After(minValidTime), "Modified time should be recent")

	// Read the decompressed content and verify it matches the mock exactly
	rc, err := zipFile.Open()
	require.NoError(t, err, "Should be able to open the deflated file inside the zip")
	defer rc.Close() // nolint: errcheck

	decompressedContent, err := io.ReadAll(rc)
	require.NoError(t, err, "Should be able to read the deflated contents")
	assert.Equal(t, expectedContent, decompressedContent, "Decompressed content must match original exactly")
}
