// Code generated by "enumer -type=Validator -addprefix=validator- -transform=lower -text"; DO NOT EDIT.

package manifest

import (
	"fmt"
	"strings"
)

const _ValidatorName = "validator-telemetry"

var _ValidatorIndex = [...]uint8{0, 19}

const _ValidatorLowerName = "validator-telemetry"

func (i Validator) String() string {
	if i < 0 || i >= Validator(len(_ValidatorIndex)-1) {
		return fmt.Sprintf("Validator(%d)", i)
	}
	return _ValidatorName[_ValidatorIndex[i]:_ValidatorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ValidatorNoOp() {
	var x [1]struct{}
	_ = x[TELEMETRY-(0)]
}

var _ValidatorValues = []Validator{TELEMETRY}

var _ValidatorNameToValueMap = map[string]Validator{
	_ValidatorName[0:19]:      TELEMETRY,
	_ValidatorLowerName[0:19]: TELEMETRY,
}

var _ValidatorNames = []string{
	_ValidatorName[0:19],
}

// ValidatorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ValidatorString(s string) (Validator, error) {
	if val, ok := _ValidatorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ValidatorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Validator values", s)
}

// ValidatorValues returns all values of the enum
func ValidatorValues() []Validator {
	return _ValidatorValues
}

// ValidatorStrings returns a slice of all String values of the enum
func ValidatorStrings() []string {
	strs := make([]string, len(_ValidatorNames))
	copy(strs, _ValidatorNames)
	return strs
}

// IsAValidator returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Validator) IsAValidator() bool {
	for _, v := range _ValidatorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Validator
func (i Validator) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Validator
func (i *Validator) UnmarshalText(text []byte) error {
	var err error
	*i, err = ValidatorString(string(text))
	return err
}
