// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argocdmock

import (
	"context"
	"time"

	"github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/argoproj/argo-cd/v3/pkg/apiclient"
	"github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	"github.com/mydecisive/octant/internal/argocd"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockAPIClient creates a new instance of MockAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClient {
	mock := &MockAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIClient is an autogenerated mock type for the APIClient type
type MockAPIClient struct {
	mock.Mock
}

type MockAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIClient) EXPECT() *MockAPIClient_Expecter {
	return &MockAPIClient_Expecter{mock: &_m.Mock}
}

// AppOperationState provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) AppOperationState(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration, out chan argocd.InstallResult) {
	_mock.Called(ctx, input, interval, timeout, out)
	return
}

// MockAPIClient_AppOperationState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppOperationState'
type MockAPIClient_AppOperationState_Call struct {
	*mock.Call
}

// AppOperationState is a helper method to define mock.On call
//   - ctx context.Context
//   - input argocd.Input
//   - interval time.Duration
//   - timeout time.Duration
//   - out chan argocd.InstallResult
func (_e *MockAPIClient_Expecter) AppOperationState(ctx interface{}, input interface{}, interval interface{}, timeout interface{}, out interface{}) *MockAPIClient_AppOperationState_Call {
	return &MockAPIClient_AppOperationState_Call{Call: _e.mock.On("AppOperationState", ctx, input, interval, timeout, out)}
}

func (_c *MockAPIClient_AppOperationState_Call) Run(run func(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration, out chan argocd.InstallResult)) *MockAPIClient_AppOperationState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.Input
		if args[1] != nil {
			arg1 = args[1].(argocd.Input)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 chan argocd.InstallResult
		if args[4] != nil {
			arg4 = args[4].(chan argocd.InstallResult)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAPIClient_AppOperationState_Call) Return() *MockAPIClient_AppOperationState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAPIClient_AppOperationState_Call) RunAndReturn(run func(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration, out chan argocd.InstallResult)) *MockAPIClient_AppOperationState_Call {
	_c.Run(run)
	return _c
}

// DeleteArgoApp provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) DeleteArgoApp(ctx context.Context, input argocd.Input) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArgoApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.Input) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIClient_DeleteArgoApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteArgoApp'
type MockAPIClient_DeleteArgoApp_Call struct {
	*mock.Call
}

// DeleteArgoApp is a helper method to define mock.On call
//   - ctx context.Context
//   - input argocd.Input
func (_e *MockAPIClient_Expecter) DeleteArgoApp(ctx interface{}, input interface{}) *MockAPIClient_DeleteArgoApp_Call {
	return &MockAPIClient_DeleteArgoApp_Call{Call: _e.mock.On("DeleteArgoApp", ctx, input)}
}

func (_c *MockAPIClient_DeleteArgoApp_Call) Run(run func(ctx context.Context, input argocd.Input)) *MockAPIClient_DeleteArgoApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.Input
		if args[1] != nil {
			arg1 = args[1].(argocd.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIClient_DeleteArgoApp_Call) Return(err error) *MockAPIClient_DeleteArgoApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIClient_DeleteArgoApp_Call) RunAndReturn(run func(ctx context.Context, input argocd.Input) error) *MockAPIClient_DeleteArgoApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppStatus provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) GetAppStatus(ctx context.Context, input argocd.Input) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetAppStatus")
	}

	var r0 octantv1alpha.InstallStatus
	var r1 []*octantv1alpha.ResourceDetails
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.Input) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.Input) octantv1alpha.InstallStatus); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(octantv1alpha.InstallStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, argocd.Input) []*octantv1alpha.ResourceDetails); ok {
		r1 = returnFunc(ctx, input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*octantv1alpha.ResourceDetails)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, argocd.Input) error); ok {
		r2 = returnFunc(ctx, input)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIClient_GetAppStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppStatus'
type MockAPIClient_GetAppStatus_Call struct {
	*mock.Call
}

// GetAppStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input argocd.Input
func (_e *MockAPIClient_Expecter) GetAppStatus(ctx interface{}, input interface{}) *MockAPIClient_GetAppStatus_Call {
	return &MockAPIClient_GetAppStatus_Call{Call: _e.mock.On("GetAppStatus", ctx, input)}
}

func (_c *MockAPIClient_GetAppStatus_Call) Run(run func(ctx context.Context, input argocd.Input)) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.Input
		if args[1] != nil {
			arg1 = args[1].(argocd.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIClient_GetAppStatus_Call) Return(installStatus octantv1alpha.InstallStatus, resourceDetailss []*octantv1alpha.ResourceDetails, err error) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Return(installStatus, resourceDetailss, err)
	return _c
}

func (_c *MockAPIClient_GetAppStatus_Call) RunAndReturn(run func(ctx context.Context, input argocd.Input) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error)) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PushArgoApp provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) PushArgoApp(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application) error {
	ret := _mock.Called(ctx, logger, clientOpts, argoApp)

	if len(ret) == 0 {
		panic("no return value specified for PushArgoApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions, v1alpha1.Application) error); ok {
		r0 = returnFunc(ctx, logger, clientOpts, argoApp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIClient_PushArgoApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushArgoApp'
type MockAPIClient_PushArgoApp_Call struct {
	*mock.Call
}

// PushArgoApp is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
//   - argoApp v1alpha1.Application
func (_e *MockAPIClient_Expecter) PushArgoApp(ctx interface{}, logger interface{}, clientOpts interface{}, argoApp interface{}) *MockAPIClient_PushArgoApp_Call {
	return &MockAPIClient_PushArgoApp_Call{Call: _e.mock.On("PushArgoApp", ctx, logger, clientOpts, argoApp)}
}

func (_c *MockAPIClient_PushArgoApp_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application)) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		var arg3 v1alpha1.Application
		if args[3] != nil {
			arg3 = args[3].(v1alpha1.Application)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIClient_PushArgoApp_Call) Return(err error) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIClient_PushArgoApp_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application) error) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Return(run)
	return _c
}

// SyncApplication provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) SyncApplication(ctx context.Context, input argocd.Input, manifests []string, prune bool) error {
	ret := _mock.Called(ctx, input, manifests, prune)

	if len(ret) == 0 {
		panic("no return value specified for SyncApplication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.Input, []string, bool) error); ok {
		r0 = returnFunc(ctx, input, manifests, prune)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIClient_SyncApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncApplication'
type MockAPIClient_SyncApplication_Call struct {
	*mock.Call
}

// SyncApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - input argocd.Input
//   - manifests []string
//   - prune bool
func (_e *MockAPIClient_Expecter) SyncApplication(ctx interface{}, input interface{}, manifests interface{}, prune interface{}) *MockAPIClient_SyncApplication_Call {
	return &MockAPIClient_SyncApplication_Call{Call: _e.mock.On("SyncApplication", ctx, input, manifests, prune)}
}

func (_c *MockAPIClient_SyncApplication_Call) Run(run func(ctx context.Context, input argocd.Input, manifests []string, prune bool)) *MockAPIClient_SyncApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.Input
		if args[1] != nil {
			arg1 = args[1].(argocd.Input)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIClient_SyncApplication_Call) Return(err error) *MockAPIClient_SyncApplication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIClient_SyncApplication_Call) RunAndReturn(run func(ctx context.Context, input argocd.Input, manifests []string, prune bool) error) *MockAPIClient_SyncApplication_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) TestConnection(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (bool, error) {
	ret := _mock.Called(ctx, logger, clientOpts)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) (bool, error)); ok {
		return returnFunc(ctx, logger, clientOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) bool); ok {
		r0 = returnFunc(ctx, logger, clientOpts)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) error); ok {
		r1 = returnFunc(ctx, logger, clientOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIClient_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockAPIClient_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
func (_e *MockAPIClient_Expecter) TestConnection(ctx interface{}, logger interface{}, clientOpts interface{}) *MockAPIClient_TestConnection_Call {
	return &MockAPIClient_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, logger, clientOpts)}
}

func (_c *MockAPIClient_TestConnection_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions)) *MockAPIClient_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) Return(b bool, err error) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (bool, error)) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForAppOperation provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) WaitForAppOperation(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration) error {
	ret := _mock.Called(ctx, input, interval, timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForAppOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, argocd.Input, time.Duration, time.Duration) error); ok {
		r0 = returnFunc(ctx, input, interval, timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIClient_WaitForAppOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForAppOperation'
type MockAPIClient_WaitForAppOperation_Call struct {
	*mock.Call
}

// WaitForAppOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - input argocd.Input
//   - interval time.Duration
//   - timeout time.Duration
func (_e *MockAPIClient_Expecter) WaitForAppOperation(ctx interface{}, input interface{}, interval interface{}, timeout interface{}) *MockAPIClient_WaitForAppOperation_Call {
	return &MockAPIClient_WaitForAppOperation_Call{Call: _e.mock.On("WaitForAppOperation", ctx, input, interval, timeout)}
}

func (_c *MockAPIClient_WaitForAppOperation_Call) Run(run func(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration)) *MockAPIClient_WaitForAppOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 argocd.Input
		if args[1] != nil {
			arg1 = args[1].(argocd.Input)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIClient_WaitForAppOperation_Call) Return(err error) *MockAPIClient_WaitForAppOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIClient_WaitForAppOperation_Call) RunAndReturn(run func(ctx context.Context, input argocd.Input, interval time.Duration, timeout time.Duration) error) *MockAPIClient_WaitForAppOperation_Call {
	_c.Call.Return(run)
	return _c
}
