// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argocdmock

import (
	"context"

	"github.com/argoproj/argo-cd/v3/pkg/apiclient"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockAPIClient creates a new instance of MockAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClient {
	mock := &MockAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIClient is an autogenerated mock type for the APIClient type
type MockAPIClient struct {
	mock.Mock
}

type MockAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIClient) EXPECT() *MockAPIClient_Expecter {
	return &MockAPIClient_Expecter{mock: &_m.Mock}
}

// TestConnection provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) TestConnection(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) bool {
	ret := _mock.Called(ctx, logger, clientOpts)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) bool); ok {
		r0 = returnFunc(ctx, logger, clientOpts)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAPIClient_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockAPIClient_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
func (_e *MockAPIClient_Expecter) TestConnection(ctx interface{}, logger interface{}, clientOpts interface{}) *MockAPIClient_TestConnection_Call {
	return &MockAPIClient_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, logger, clientOpts)}
}

func (_c *MockAPIClient_TestConnection_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions)) *MockAPIClient_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) Return(b bool) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) bool) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
