// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argocdmock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/argoproj/argo-cd/v3/pkg/apiclient"
	"github.com/argoproj/argo-cd/v3/pkg/apis/application/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockAPIClient creates a new instance of MockAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClient {
	mock := &MockAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIClient is an autogenerated mock type for the APIClient type
type MockAPIClient struct {
	mock.Mock
}

type MockAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIClient) EXPECT() *MockAPIClient_Expecter {
	return &MockAPIClient_Expecter{mock: &_m.Mock}
}

// GetAppStatus provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) GetAppStatus(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error) {
	ret := _mock.Called(ctx, logger, clientOpts)

	if len(ret) == 0 {
		panic("no return value specified for GetAppStatus")
	}

	var r0 octantv1alpha.InstallStatus
	var r1 []*octantv1alpha.ResourceDetails
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error)); ok {
		return returnFunc(ctx, logger, clientOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) octantv1alpha.InstallStatus); ok {
		r0 = returnFunc(ctx, logger, clientOpts)
	} else {
		r0 = ret.Get(0).(octantv1alpha.InstallStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) []*octantv1alpha.ResourceDetails); ok {
		r1 = returnFunc(ctx, logger, clientOpts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*octantv1alpha.ResourceDetails)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) error); ok {
		r2 = returnFunc(ctx, logger, clientOpts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAPIClient_GetAppStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppStatus'
type MockAPIClient_GetAppStatus_Call struct {
	*mock.Call
}

// GetAppStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
func (_e *MockAPIClient_Expecter) GetAppStatus(ctx interface{}, logger interface{}, clientOpts interface{}) *MockAPIClient_GetAppStatus_Call {
	return &MockAPIClient_GetAppStatus_Call{Call: _e.mock.On("GetAppStatus", ctx, logger, clientOpts)}
}

func (_c *MockAPIClient_GetAppStatus_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions)) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIClient_GetAppStatus_Call) Return(installStatus octantv1alpha.InstallStatus, resourceDetailss []*octantv1alpha.ResourceDetails, err error) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Return(installStatus, resourceDetailss, err)
	return _c
}

func (_c *MockAPIClient_GetAppStatus_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (octantv1alpha.InstallStatus, []*octantv1alpha.ResourceDetails, error)) *MockAPIClient_GetAppStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PushArgoApp provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) PushArgoApp(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application) error {
	ret := _mock.Called(ctx, logger, clientOpts, argoApp)

	if len(ret) == 0 {
		panic("no return value specified for PushArgoApp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions, v1alpha1.Application) error); ok {
		r0 = returnFunc(ctx, logger, clientOpts, argoApp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIClient_PushArgoApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushArgoApp'
type MockAPIClient_PushArgoApp_Call struct {
	*mock.Call
}

// PushArgoApp is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
//   - argoApp v1alpha1.Application
func (_e *MockAPIClient_Expecter) PushArgoApp(ctx interface{}, logger interface{}, clientOpts interface{}, argoApp interface{}) *MockAPIClient_PushArgoApp_Call {
	return &MockAPIClient_PushArgoApp_Call{Call: _e.mock.On("PushArgoApp", ctx, logger, clientOpts, argoApp)}
}

func (_c *MockAPIClient_PushArgoApp_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application)) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		var arg3 v1alpha1.Application
		if args[3] != nil {
			arg3 = args[3].(v1alpha1.Application)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAPIClient_PushArgoApp_Call) Return(err error) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIClient_PushArgoApp_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions, argoApp v1alpha1.Application) error) *MockAPIClient_PushArgoApp_Call {
	_c.Call.Return(run)
	return _c
}

// TestConnection provides a mock function for the type MockAPIClient
func (_mock *MockAPIClient) TestConnection(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (bool, error) {
	ret := _mock.Called(ctx, logger, clientOpts)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) (bool, error)); ok {
		return returnFunc(ctx, logger, clientOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) bool); ok {
		r0 = returnFunc(ctx, logger, clientOpts)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *zap.Logger, *apiclient.ClientOptions) error); ok {
		r1 = returnFunc(ctx, logger, clientOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIClient_TestConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestConnection'
type MockAPIClient_TestConnection_Call struct {
	*mock.Call
}

// TestConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - clientOpts *apiclient.ClientOptions
func (_e *MockAPIClient_Expecter) TestConnection(ctx interface{}, logger interface{}, clientOpts interface{}) *MockAPIClient_TestConnection_Call {
	return &MockAPIClient_TestConnection_Call{Call: _e.mock.On("TestConnection", ctx, logger, clientOpts)}
}

func (_c *MockAPIClient_TestConnection_Call) Run(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions)) *MockAPIClient_TestConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 *apiclient.ClientOptions
		if args[2] != nil {
			arg2 = args[2].(*apiclient.ClientOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) Return(b bool, err error) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAPIClient_TestConnection_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, clientOpts *apiclient.ClientOptions) (bool, error)) *MockAPIClient_TestConnection_Call {
	_c.Call.Return(run)
	return _c
}
