serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "octant"
  integrationSecretNames:
    - "mdai-datadog-integration"
    - "mdai-argocd-integration"

deployment:
  name: octant
  replicas: 1
  ports:
    - name: octant-ui
      containerPort: 5678
      protocol: TCP
#    - name: octant-api
#      containerPort: 50051
#      protocol: TCP
  tolerations: []
  nodeSelector: {}
  affinity: {}
  annotations: {}
  prometheusEndpoint: "http://kube-prometheus-stack-prometheus:9090"

image:
  repository: ghcr.io/mydecisive/octant
  # tag: latest

services:
  name: octant
  ports:
    - name: octant-ui
      port: 5678
      protocol: TCP
      targetPort: 5678
#    - name: octant-api
#      port: 50051
#      protocol: TCP
#      targetPort: 50051
  type: ClusterIP
