// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package manifestmock

import (
	"bytes"
	"context"

	"github.com/mydecisive/octant/internal/connection/manifest/data"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockCompressor creates a new instance of MockCompressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompressor {
	mock := &MockCompressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompressor is an autogenerated mock type for the Compressor type
type MockCompressor struct {
	mock.Mock
}

type MockCompressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompressor) EXPECT() *MockCompressor_Expecter {
	return &MockCompressor_Expecter{mock: &_m.Mock}
}

// Compress provides a mock function for the type MockCompressor
func (_mock *MockCompressor) Compress(ctx context.Context, manifests map[string][]byte) (*bytes.Buffer, error) {
	ret := _mock.Called(ctx, manifests)

	if len(ret) == 0 {
		panic("no return value specified for Compress")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string][]byte) (*bytes.Buffer, error)); ok {
		return returnFunc(ctx, manifests)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string][]byte) *bytes.Buffer); ok {
		r0 = returnFunc(ctx, manifests)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string][]byte) error); ok {
		r1 = returnFunc(ctx, manifests)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompressor_Compress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compress'
type MockCompressor_Compress_Call struct {
	*mock.Call
}

// Compress is a helper method to define mock.On call
//   - ctx context.Context
//   - manifests map[string][]byte
func (_e *MockCompressor_Expecter) Compress(ctx interface{}, manifests interface{}) *MockCompressor_Compress_Call {
	return &MockCompressor_Compress_Call{Call: _e.mock.On("Compress", ctx, manifests)}
}

func (_c *MockCompressor_Compress_Call) Run(run func(ctx context.Context, manifests map[string][]byte)) *MockCompressor_Compress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string][]byte
		if args[1] != nil {
			arg1 = args[1].(map[string][]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompressor_Compress_Call) Return(buffer *bytes.Buffer, err error) *MockCompressor_Compress_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockCompressor_Compress_Call) RunAndReturn(run func(ctx context.Context, manifests map[string][]byte) (*bytes.Buffer, error)) *MockCompressor_Compress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// LoadCertManager provides a mock function for the type MockManager
func (_mock *MockManager) LoadCertManager(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData) error {
	ret := _mock.Called(ctx, input, data)

	if len(ret) == 0 {
		panic("no return value specified for LoadCertManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ManagerInput, manifestdata.AppTemplateData) error); ok {
		r0 = returnFunc(ctx, input, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_LoadCertManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCertManager'
type MockManager_LoadCertManager_Call struct {
	*mock.Call
}

// LoadCertManager is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.ManagerInput
//   - data manifestdata.AppTemplateData
func (_e *MockManager_Expecter) LoadCertManager(ctx interface{}, input interface{}, data interface{}) *MockManager_LoadCertManager_Call {
	return &MockManager_LoadCertManager_Call{Call: _e.mock.On("LoadCertManager", ctx, input, data)}
}

func (_c *MockManager_LoadCertManager_Call) Run(run func(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData)) *MockManager_LoadCertManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.ManagerInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.ManagerInput)
		}
		var arg2 manifestdata.AppTemplateData
		if args[2] != nil {
			arg2 = args[2].(manifestdata.AppTemplateData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_LoadCertManager_Call) Return(err error) *MockManager_LoadCertManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_LoadCertManager_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData) error) *MockManager_LoadCertManager_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConnection provides a mock function for the type MockManager
func (_mock *MockManager) LoadConnection(ctx context.Context, logger *zap.Logger, input manifestdata.ConnectionInput) error {
	ret := _mock.Called(ctx, logger, input)

	if len(ret) == 0 {
		panic("no return value specified for LoadConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, manifestdata.ConnectionInput) error); ok {
		r0 = returnFunc(ctx, logger, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_LoadConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConnection'
type MockManager_LoadConnection_Call struct {
	*mock.Call
}

// LoadConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - input manifestdata.ConnectionInput
func (_e *MockManager_Expecter) LoadConnection(ctx interface{}, logger interface{}, input interface{}) *MockManager_LoadConnection_Call {
	return &MockManager_LoadConnection_Call{Call: _e.mock.On("LoadConnection", ctx, logger, input)}
}

func (_c *MockManager_LoadConnection_Call) Run(run func(ctx context.Context, logger *zap.Logger, input manifestdata.ConnectionInput)) *MockManager_LoadConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 manifestdata.ConnectionInput
		if args[2] != nil {
			arg2 = args[2].(manifestdata.ConnectionInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_LoadConnection_Call) Return(err error) *MockManager_LoadConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_LoadConnection_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, input manifestdata.ConnectionInput) error) *MockManager_LoadConnection_Call {
	_c.Call.Return(run)
	return _c
}

// LoadMDAI provides a mock function for the type MockManager
func (_mock *MockManager) LoadMDAI(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData) error {
	ret := _mock.Called(ctx, input, data)

	if len(ret) == 0 {
		panic("no return value specified for LoadMDAI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ManagerInput, manifestdata.AppTemplateData) error); ok {
		r0 = returnFunc(ctx, input, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_LoadMDAI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadMDAI'
type MockManager_LoadMDAI_Call struct {
	*mock.Call
}

// LoadMDAI is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.ManagerInput
//   - data manifestdata.AppTemplateData
func (_e *MockManager_Expecter) LoadMDAI(ctx interface{}, input interface{}, data interface{}) *MockManager_LoadMDAI_Call {
	return &MockManager_LoadMDAI_Call{Call: _e.mock.On("LoadMDAI", ctx, input, data)}
}

func (_c *MockManager_LoadMDAI_Call) Run(run func(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData)) *MockManager_LoadMDAI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.ManagerInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.ManagerInput)
		}
		var arg2 manifestdata.AppTemplateData
		if args[2] != nil {
			arg2 = args[2].(manifestdata.AppTemplateData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_LoadMDAI_Call) Return(err error) *MockManager_LoadMDAI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_LoadMDAI_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.ManagerInput, data manifestdata.AppTemplateData) error) *MockManager_LoadMDAI_Call {
	_c.Call.Return(run)
	return _c
}

// LoadValidator provides a mock function for the type MockManager
func (_mock *MockManager) LoadValidator(ctx context.Context, logger *zap.Logger, input manifestdata.ValidatorInput) error {
	ret := _mock.Called(ctx, logger, input)

	if len(ret) == 0 {
		panic("no return value specified for LoadValidator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *zap.Logger, manifestdata.ValidatorInput) error); ok {
		r0 = returnFunc(ctx, logger, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_LoadValidator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadValidator'
type MockManager_LoadValidator_Call struct {
	*mock.Call
}

// LoadValidator is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *zap.Logger
//   - input manifestdata.ValidatorInput
func (_e *MockManager_Expecter) LoadValidator(ctx interface{}, logger interface{}, input interface{}) *MockManager_LoadValidator_Call {
	return &MockManager_LoadValidator_Call{Call: _e.mock.On("LoadValidator", ctx, logger, input)}
}

func (_c *MockManager_LoadValidator_Call) Run(run func(ctx context.Context, logger *zap.Logger, input manifestdata.ValidatorInput)) *MockManager_LoadValidator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *zap.Logger
		if args[1] != nil {
			arg1 = args[1].(*zap.Logger)
		}
		var arg2 manifestdata.ValidatorInput
		if args[2] != nil {
			arg2 = args[2].(manifestdata.ValidatorInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_LoadValidator_Call) Return(err error) *MockManager_LoadValidator_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_LoadValidator_Call) RunAndReturn(run func(ctx context.Context, logger *zap.Logger, input manifestdata.ValidatorInput) error) *MockManager_LoadValidator_Call {
	_c.Call.Return(run)
	return _c
}

// Unload provides a mock function for the type MockManager
func (_mock *MockManager) Unload(ctx context.Context, input manifestdata.ManagerInput, apps []manifestdata.App) error {
	ret := _mock.Called(ctx, input, apps)

	if len(ret) == 0 {
		panic("no return value specified for Unload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ManagerInput, []manifestdata.App) error); ok {
		r0 = returnFunc(ctx, input, apps)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Unload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unload'
type MockManager_Unload_Call struct {
	*mock.Call
}

// Unload is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.ManagerInput
//   - apps []manifestdata.App
func (_e *MockManager_Expecter) Unload(ctx interface{}, input interface{}, apps interface{}) *MockManager_Unload_Call {
	return &MockManager_Unload_Call{Call: _e.mock.On("Unload", ctx, input, apps)}
}

func (_c *MockManager_Unload_Call) Run(run func(ctx context.Context, input manifestdata.ManagerInput, apps []manifestdata.App)) *MockManager_Unload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.ManagerInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.ManagerInput)
		}
		var arg2 []manifestdata.App
		if args[2] != nil {
			arg2 = args[2].([]manifestdata.App)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_Unload_Call) Return(err error) *MockManager_Unload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Unload_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.ManagerInput, apps []manifestdata.App) error) *MockManager_Unload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockGenerator
func (_mock *MockGenerator) All(ctx context.Context, input manifestdata.AllInput, format manifestdata.OutputFormat) (map[string][]byte, error) {
	ret := _mock.Called(ctx, input, format)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.AllInput, manifestdata.OutputFormat) (map[string][]byte, error)); ok {
		return returnFunc(ctx, input, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.AllInput, manifestdata.OutputFormat) map[string][]byte); ok {
		r0 = returnFunc(ctx, input, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifestdata.AllInput, manifestdata.OutputFormat) error); ok {
		r1 = returnFunc(ctx, input, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockGenerator_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.AllInput
//   - format manifestdata.OutputFormat
func (_e *MockGenerator_Expecter) All(ctx interface{}, input interface{}, format interface{}) *MockGenerator_All_Call {
	return &MockGenerator_All_Call{Call: _e.mock.On("All", ctx, input, format)}
}

func (_c *MockGenerator_All_Call) Run(run func(ctx context.Context, input manifestdata.AllInput, format manifestdata.OutputFormat)) *MockGenerator_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.AllInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.AllInput)
		}
		var arg2 manifestdata.OutputFormat
		if args[2] != nil {
			arg2 = args[2].(manifestdata.OutputFormat)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenerator_All_Call) Return(stringToBytes map[string][]byte, err error) *MockGenerator_All_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockGenerator_All_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.AllInput, format manifestdata.OutputFormat) (map[string][]byte, error)) *MockGenerator_All_Call {
	_c.Call.Return(run)
	return _c
}

// App provides a mock function for the type MockGenerator
func (_mock *MockGenerator) App(app manifestdata.App, data manifestdata.AppTemplateData, format manifestdata.OutputFormat) ([][]byte, error) {
	ret := _mock.Called(app, data, format)

	if len(ret) == 0 {
		panic("no return value specified for App")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(manifestdata.App, manifestdata.AppTemplateData, manifestdata.OutputFormat) ([][]byte, error)); ok {
		return returnFunc(app, data, format)
	}
	if returnFunc, ok := ret.Get(0).(func(manifestdata.App, manifestdata.AppTemplateData, manifestdata.OutputFormat) [][]byte); ok {
		r0 = returnFunc(app, data, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(manifestdata.App, manifestdata.AppTemplateData, manifestdata.OutputFormat) error); ok {
		r1 = returnFunc(app, data, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_App_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'App'
type MockGenerator_App_Call struct {
	*mock.Call
}

// App is a helper method to define mock.On call
//   - app manifestdata.App
//   - data manifestdata.AppTemplateData
//   - format manifestdata.OutputFormat
func (_e *MockGenerator_Expecter) App(app interface{}, data interface{}, format interface{}) *MockGenerator_App_Call {
	return &MockGenerator_App_Call{Call: _e.mock.On("App", app, data, format)}
}

func (_c *MockGenerator_App_Call) Run(run func(app manifestdata.App, data manifestdata.AppTemplateData, format manifestdata.OutputFormat)) *MockGenerator_App_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.App
		if args[0] != nil {
			arg0 = args[0].(manifestdata.App)
		}
		var arg1 manifestdata.AppTemplateData
		if args[1] != nil {
			arg1 = args[1].(manifestdata.AppTemplateData)
		}
		var arg2 manifestdata.OutputFormat
		if args[2] != nil {
			arg2 = args[2].(manifestdata.OutputFormat)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenerator_App_Call) Return(bytess [][]byte, err error) *MockGenerator_App_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockGenerator_App_Call) RunAndReturn(run func(app manifestdata.App, data manifestdata.AppTemplateData, format manifestdata.OutputFormat) ([][]byte, error)) *MockGenerator_App_Call {
	_c.Call.Return(run)
	return _c
}

// Connections provides a mock function for the type MockGenerator
func (_mock *MockGenerator) Connections(ctx context.Context, input manifestdata.ConnectionInput, format manifestdata.OutputFormat) (map[string][]byte, error) {
	ret := _mock.Called(ctx, input, format)

	if len(ret) == 0 {
		panic("no return value specified for Connections")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ConnectionInput, manifestdata.OutputFormat) (map[string][]byte, error)); ok {
		return returnFunc(ctx, input, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ConnectionInput, manifestdata.OutputFormat) map[string][]byte); ok {
		r0 = returnFunc(ctx, input, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifestdata.ConnectionInput, manifestdata.OutputFormat) error); ok {
		r1 = returnFunc(ctx, input, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_Connections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connections'
type MockGenerator_Connections_Call struct {
	*mock.Call
}

// Connections is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.ConnectionInput
//   - format manifestdata.OutputFormat
func (_e *MockGenerator_Expecter) Connections(ctx interface{}, input interface{}, format interface{}) *MockGenerator_Connections_Call {
	return &MockGenerator_Connections_Call{Call: _e.mock.On("Connections", ctx, input, format)}
}

func (_c *MockGenerator_Connections_Call) Run(run func(ctx context.Context, input manifestdata.ConnectionInput, format manifestdata.OutputFormat)) *MockGenerator_Connections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.ConnectionInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.ConnectionInput)
		}
		var arg2 manifestdata.OutputFormat
		if args[2] != nil {
			arg2 = args[2].(manifestdata.OutputFormat)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGenerator_Connections_Call) Return(stringToBytes map[string][]byte, err error) *MockGenerator_Connections_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockGenerator_Connections_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.ConnectionInput, format manifestdata.OutputFormat) (map[string][]byte, error)) *MockGenerator_Connections_Call {
	_c.Call.Return(run)
	return _c
}

// Validators provides a mock function for the type MockGenerator
func (_mock *MockGenerator) Validators(input manifestdata.ValidatorInput, format manifestdata.OutputFormat) (map[string][]byte, error) {
	ret := _mock.Called(input, format)

	if len(ret) == 0 {
		panic("no return value specified for Validators")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(manifestdata.ValidatorInput, manifestdata.OutputFormat) (map[string][]byte, error)); ok {
		return returnFunc(input, format)
	}
	if returnFunc, ok := ret.Get(0).(func(manifestdata.ValidatorInput, manifestdata.OutputFormat) map[string][]byte); ok {
		r0 = returnFunc(input, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(manifestdata.ValidatorInput, manifestdata.OutputFormat) error); ok {
		r1 = returnFunc(input, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_Validators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validators'
type MockGenerator_Validators_Call struct {
	*mock.Call
}

// Validators is a helper method to define mock.On call
//   - input manifestdata.ValidatorInput
//   - format manifestdata.OutputFormat
func (_e *MockGenerator_Expecter) Validators(input interface{}, format interface{}) *MockGenerator_Validators_Call {
	return &MockGenerator_Validators_Call{Call: _e.mock.On("Validators", input, format)}
}

func (_c *MockGenerator_Validators_Call) Run(run func(input manifestdata.ValidatorInput, format manifestdata.OutputFormat)) *MockGenerator_Validators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.ValidatorInput
		if args[0] != nil {
			arg0 = args[0].(manifestdata.ValidatorInput)
		}
		var arg1 manifestdata.OutputFormat
		if args[1] != nil {
			arg1 = args[1].(manifestdata.OutputFormat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerator_Validators_Call) Return(stringToBytes map[string][]byte, err error) *MockGenerator_Validators_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockGenerator_Validators_Call) RunAndReturn(run func(input manifestdata.ValidatorInput, format manifestdata.OutputFormat) (map[string][]byte, error)) *MockGenerator_Validators_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateRenderer creates a new instance of MockTemplateRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateRenderer is an autogenerated mock type for the TemplateRenderer type
type MockTemplateRenderer struct {
	mock.Mock
}

type MockTemplateRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateRenderer) EXPECT() *MockTemplateRenderer_Expecter {
	return &MockTemplateRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockTemplateRenderer
func (_mock *MockTemplateRenderer) Render(name string, template []byte, format manifestdata.OutputFormat, data any) ([][]byte, error) {
	ret := _mock.Called(name, template, format, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, manifestdata.OutputFormat, any) ([][]byte, error)); ok {
		return returnFunc(name, template, format, data)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, manifestdata.OutputFormat, any) [][]byte); ok {
		r0 = returnFunc(name, template, format, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, manifestdata.OutputFormat, any) error); ok {
		r1 = returnFunc(name, template, format, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockTemplateRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - name string
//   - template []byte
//   - format manifestdata.OutputFormat
//   - data any
func (_e *MockTemplateRenderer_Expecter) Render(name interface{}, template interface{}, format interface{}, data interface{}) *MockTemplateRenderer_Render_Call {
	return &MockTemplateRenderer_Render_Call{Call: _e.mock.On("Render", name, template, format, data)}
}

func (_c *MockTemplateRenderer_Render_Call) Run(run func(name string, template []byte, format manifestdata.OutputFormat, data any)) *MockTemplateRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 manifestdata.OutputFormat
		if args[2] != nil {
			arg2 = args[2].(manifestdata.OutputFormat)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTemplateRenderer_Render_Call) Return(bytess [][]byte, err error) *MockTemplateRenderer_Render_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockTemplateRenderer_Render_Call) RunAndReturn(run func(name string, template []byte, format manifestdata.OutputFormat, data any) ([][]byte, error)) *MockTemplateRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTemplateProvider creates a new instance of MockTemplateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTemplateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTemplateProvider {
	mock := &MockTemplateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTemplateProvider is an autogenerated mock type for the TemplateProvider type
type MockTemplateProvider struct {
	mock.Mock
}

type MockTemplateProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTemplateProvider) EXPECT() *MockTemplateProvider_Expecter {
	return &MockTemplateProvider_Expecter{mock: &_m.Mock}
}

// GetAllConnections provides a mock function for the type MockTemplateProvider
func (_mock *MockTemplateProvider) GetAllConnections() (map[manifestdata.Connection][]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllConnections")
	}

	var r0 map[manifestdata.Connection][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[manifestdata.Connection][]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[manifestdata.Connection][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[manifestdata.Connection][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateProvider_GetAllConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConnections'
type MockTemplateProvider_GetAllConnections_Call struct {
	*mock.Call
}

// GetAllConnections is a helper method to define mock.On call
func (_e *MockTemplateProvider_Expecter) GetAllConnections() *MockTemplateProvider_GetAllConnections_Call {
	return &MockTemplateProvider_GetAllConnections_Call{Call: _e.mock.On("GetAllConnections")}
}

func (_c *MockTemplateProvider_GetAllConnections_Call) Run(run func()) *MockTemplateProvider_GetAllConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateProvider_GetAllConnections_Call) Return(connectionToBytes map[manifestdata.Connection][]byte, err error) *MockTemplateProvider_GetAllConnections_Call {
	_c.Call.Return(connectionToBytes, err)
	return _c
}

func (_c *MockTemplateProvider_GetAllConnections_Call) RunAndReturn(run func() (map[manifestdata.Connection][]byte, error)) *MockTemplateProvider_GetAllConnections_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllValidators provides a mock function for the type MockTemplateProvider
func (_mock *MockTemplateProvider) GetAllValidators() (map[manifestdata.Validator][]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllValidators")
	}

	var r0 map[manifestdata.Validator][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[manifestdata.Validator][]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[manifestdata.Validator][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[manifestdata.Validator][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateProvider_GetAllValidators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllValidators'
type MockTemplateProvider_GetAllValidators_Call struct {
	*mock.Call
}

// GetAllValidators is a helper method to define mock.On call
func (_e *MockTemplateProvider_Expecter) GetAllValidators() *MockTemplateProvider_GetAllValidators_Call {
	return &MockTemplateProvider_GetAllValidators_Call{Call: _e.mock.On("GetAllValidators")}
}

func (_c *MockTemplateProvider_GetAllValidators_Call) Run(run func()) *MockTemplateProvider_GetAllValidators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTemplateProvider_GetAllValidators_Call) Return(validatorToBytes map[manifestdata.Validator][]byte, err error) *MockTemplateProvider_GetAllValidators_Call {
	_c.Call.Return(validatorToBytes, err)
	return _c
}

func (_c *MockTemplateProvider_GetAllValidators_Call) RunAndReturn(run func() (map[manifestdata.Validator][]byte, error)) *MockTemplateProvider_GetAllValidators_Call {
	_c.Call.Return(run)
	return _c
}

// GetApp provides a mock function for the type MockTemplateProvider
func (_mock *MockTemplateProvider) GetApp(app manifestdata.App) ([]byte, error) {
	ret := _mock.Called(app)

	if len(ret) == 0 {
		panic("no return value specified for GetApp")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(manifestdata.App) ([]byte, error)); ok {
		return returnFunc(app)
	}
	if returnFunc, ok := ret.Get(0).(func(manifestdata.App) []byte); ok {
		r0 = returnFunc(app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(manifestdata.App) error); ok {
		r1 = returnFunc(app)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateProvider_GetApp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApp'
type MockTemplateProvider_GetApp_Call struct {
	*mock.Call
}

// GetApp is a helper method to define mock.On call
//   - app manifestdata.App
func (_e *MockTemplateProvider_Expecter) GetApp(app interface{}) *MockTemplateProvider_GetApp_Call {
	return &MockTemplateProvider_GetApp_Call{Call: _e.mock.On("GetApp", app)}
}

func (_c *MockTemplateProvider_GetApp_Call) Run(run func(app manifestdata.App)) *MockTemplateProvider_GetApp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.App
		if args[0] != nil {
			arg0 = args[0].(manifestdata.App)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTemplateProvider_GetApp_Call) Return(bytes1 []byte, err error) *MockTemplateProvider_GetApp_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockTemplateProvider_GetApp_Call) RunAndReturn(run func(app manifestdata.App) ([]byte, error)) *MockTemplateProvider_GetApp_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnection provides a mock function for the type MockTemplateProvider
func (_mock *MockTemplateProvider) GetConnection(conn manifestdata.Connection) ([]byte, error) {
	ret := _mock.Called(conn)

	if len(ret) == 0 {
		panic("no return value specified for GetConnection")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(manifestdata.Connection) ([]byte, error)); ok {
		return returnFunc(conn)
	}
	if returnFunc, ok := ret.Get(0).(func(manifestdata.Connection) []byte); ok {
		r0 = returnFunc(conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(manifestdata.Connection) error); ok {
		r1 = returnFunc(conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateProvider_GetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnection'
type MockTemplateProvider_GetConnection_Call struct {
	*mock.Call
}

// GetConnection is a helper method to define mock.On call
//   - conn manifestdata.Connection
func (_e *MockTemplateProvider_Expecter) GetConnection(conn interface{}) *MockTemplateProvider_GetConnection_Call {
	return &MockTemplateProvider_GetConnection_Call{Call: _e.mock.On("GetConnection", conn)}
}

func (_c *MockTemplateProvider_GetConnection_Call) Run(run func(conn manifestdata.Connection)) *MockTemplateProvider_GetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.Connection
		if args[0] != nil {
			arg0 = args[0].(manifestdata.Connection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTemplateProvider_GetConnection_Call) Return(bytes1 []byte, err error) *MockTemplateProvider_GetConnection_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockTemplateProvider_GetConnection_Call) RunAndReturn(run func(conn manifestdata.Connection) ([]byte, error)) *MockTemplateProvider_GetConnection_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidator provides a mock function for the type MockTemplateProvider
func (_mock *MockTemplateProvider) GetValidator(validator manifestdata.Validator) ([]byte, error) {
	ret := _mock.Called(validator)

	if len(ret) == 0 {
		panic("no return value specified for GetValidator")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(manifestdata.Validator) ([]byte, error)); ok {
		return returnFunc(validator)
	}
	if returnFunc, ok := ret.Get(0).(func(manifestdata.Validator) []byte); ok {
		r0 = returnFunc(validator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(manifestdata.Validator) error); ok {
		r1 = returnFunc(validator)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTemplateProvider_GetValidator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidator'
type MockTemplateProvider_GetValidator_Call struct {
	*mock.Call
}

// GetValidator is a helper method to define mock.On call
//   - validator manifestdata.Validator
func (_e *MockTemplateProvider_Expecter) GetValidator(validator interface{}) *MockTemplateProvider_GetValidator_Call {
	return &MockTemplateProvider_GetValidator_Call{Call: _e.mock.On("GetValidator", validator)}
}

func (_c *MockTemplateProvider_GetValidator_Call) Run(run func(validator manifestdata.Validator)) *MockTemplateProvider_GetValidator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.Validator
		if args[0] != nil {
			arg0 = args[0].(manifestdata.Validator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTemplateProvider_GetValidator_Call) Return(bytes1 []byte, err error) *MockTemplateProvider_GetValidator_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockTemplateProvider_GetValidator_Call) RunAndReturn(run func(validator manifestdata.Validator) ([]byte, error)) *MockTemplateProvider_GetValidator_Call {
	_c.Call.Return(run)
	return _c
}
