// Code generated by "enumer -type=App -addprefix=app- -transform=lower -text"; DO NOT EDIT.

package manifestdata

import (
	"fmt"
	"strings"
)

const _AppName = "app-mdaiapp-certapp-connectionapp-validator"

var _AppIndex = [...]uint8{0, 8, 16, 30, 43}

const _AppLowerName = "app-mdaiapp-certapp-connectionapp-validator"

func (i App) String() string {
	if i < 0 || i >= App(len(_AppIndex)-1) {
		return fmt.Sprintf("App(%d)", i)
	}
	return _AppName[_AppIndex[i]:_AppIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AppNoOp() {
	var x [1]struct{}
	_ = x[MDAI-(0)]
	_ = x[CERT-(1)]
	_ = x[CONNECTION-(2)]
	_ = x[VALIDATOR-(3)]
}

var _AppValues = []App{MDAI, CERT, CONNECTION, VALIDATOR}

var _AppNameToValueMap = map[string]App{
	_AppName[0:8]:        MDAI,
	_AppLowerName[0:8]:   MDAI,
	_AppName[8:16]:       CERT,
	_AppLowerName[8:16]:  CERT,
	_AppName[16:30]:      CONNECTION,
	_AppLowerName[16:30]: CONNECTION,
	_AppName[30:43]:      VALIDATOR,
	_AppLowerName[30:43]: VALIDATOR,
}

var _AppNames = []string{
	_AppName[0:8],
	_AppName[8:16],
	_AppName[16:30],
	_AppName[30:43],
}

// AppString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AppString(s string) (App, error) {
	if val, ok := _AppNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AppNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to App values", s)
}

// AppValues returns all values of the enum
func AppValues() []App {
	return _AppValues
}

// AppStrings returns a slice of all String values of the enum
func AppStrings() []string {
	strs := make([]string, len(_AppNames))
	copy(strs, _AppNames)
	return strs
}

// IsAApp returns "true" if the value is listed in the enum definition. "false" otherwise
func (i App) IsAApp() bool {
	for _, v := range _AppValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for App
func (i App) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for App
func (i *App) UnmarshalText(text []byte) error {
	var err error
	*i, err = AppString(string(text))
	return err
}
