// Code generated by "enumer -type=Connection -addprefix=connection- -transform=lower -text"; DO NOT EDIT.

package manfiestdata

import (
	"fmt"
	"strings"
)

const _ConnectionName = "connection-hubconnection-observerconnection-roleconnection-secretconnection-collectorlbconnection-collectorlogconnection-collectortrace"

var _ConnectionIndex = [...]uint8{0, 14, 33, 48, 65, 87, 110, 135}

const _ConnectionLowerName = "connection-hubconnection-observerconnection-roleconnection-secretconnection-collectorlbconnection-collectorlogconnection-collectortrace"

func (i Connection) String() string {
	if i < 0 || i >= Connection(len(_ConnectionIndex)-1) {
		return fmt.Sprintf("Connection(%d)", i)
	}
	return _ConnectionName[_ConnectionIndex[i]:_ConnectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ConnectionNoOp() {
	var x [1]struct{}
	_ = x[HUB-(0)]
	_ = x[OBSERVER-(1)]
	_ = x[ROLE-(2)]
	_ = x[SECRET-(3)]
	_ = x[COLLECTORLB-(4)]
	_ = x[COLLECTORLOG-(5)]
	_ = x[COLLECTORTRACE-(6)]
}

var _ConnectionValues = []Connection{HUB, OBSERVER, ROLE, SECRET, COLLECTORLB, COLLECTORLOG, COLLECTORTRACE}

var _ConnectionNameToValueMap = map[string]Connection{
	_ConnectionName[0:14]:         HUB,
	_ConnectionLowerName[0:14]:    HUB,
	_ConnectionName[14:33]:        OBSERVER,
	_ConnectionLowerName[14:33]:   OBSERVER,
	_ConnectionName[33:48]:        ROLE,
	_ConnectionLowerName[33:48]:   ROLE,
	_ConnectionName[48:65]:        SECRET,
	_ConnectionLowerName[48:65]:   SECRET,
	_ConnectionName[65:87]:        COLLECTORLB,
	_ConnectionLowerName[65:87]:   COLLECTORLB,
	_ConnectionName[87:110]:       COLLECTORLOG,
	_ConnectionLowerName[87:110]:  COLLECTORLOG,
	_ConnectionName[110:135]:      COLLECTORTRACE,
	_ConnectionLowerName[110:135]: COLLECTORTRACE,
}

var _ConnectionNames = []string{
	_ConnectionName[0:14],
	_ConnectionName[14:33],
	_ConnectionName[33:48],
	_ConnectionName[48:65],
	_ConnectionName[65:87],
	_ConnectionName[87:110],
	_ConnectionName[110:135],
}

// ConnectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ConnectionString(s string) (Connection, error) {
	if val, ok := _ConnectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ConnectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Connection values", s)
}

// ConnectionValues returns all values of the enum
func ConnectionValues() []Connection {
	return _ConnectionValues
}

// ConnectionStrings returns a slice of all String values of the enum
func ConnectionStrings() []string {
	strs := make([]string, len(_ConnectionNames))
	copy(strs, _ConnectionNames)
	return strs
}

// IsAConnection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Connection) IsAConnection() bool {
	for _, v := range _ConnectionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Connection
func (i Connection) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Connection
func (i *Connection) UnmarshalText(text []byte) error {
	var err error
	*i, err = ConnectionString(string(text))
	return err
}
