// Code generated by "enumer -type=DestinationType -transform=lower -text"; DO NOT EDIT.

package manifestdata

import (
	"fmt"
	"strings"
)

const _DestinationTypeName = "datadog"

var _DestinationTypeIndex = [...]uint8{0, 7}

const _DestinationTypeLowerName = "datadog"

func (i DestinationType) String() string {
	if i < 0 || i >= DestinationType(len(_DestinationTypeIndex)-1) {
		return fmt.Sprintf("DestinationType(%d)", i)
	}
	return _DestinationTypeName[_DestinationTypeIndex[i]:_DestinationTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DestinationTypeNoOp() {
	var x [1]struct{}
	_ = x[DATADOG-(0)]
}

var _DestinationTypeValues = []DestinationType{DATADOG}

var _DestinationTypeNameToValueMap = map[string]DestinationType{
	_DestinationTypeName[0:7]:      DATADOG,
	_DestinationTypeLowerName[0:7]: DATADOG,
}

var _DestinationTypeNames = []string{
	_DestinationTypeName[0:7],
}

// DestinationTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DestinationTypeString(s string) (DestinationType, error) {
	if val, ok := _DestinationTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DestinationTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DestinationType values", s)
}

// DestinationTypeValues returns all values of the enum
func DestinationTypeValues() []DestinationType {
	return _DestinationTypeValues
}

// DestinationTypeStrings returns a slice of all String values of the enum
func DestinationTypeStrings() []string {
	strs := make([]string, len(_DestinationTypeNames))
	copy(strs, _DestinationTypeNames)
	return strs
}

// IsADestinationType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DestinationType) IsADestinationType() bool {
	for _, v := range _DestinationTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for DestinationType
func (i DestinationType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DestinationType
func (i *DestinationType) UnmarshalText(text []byte) error {
	var err error
	*i, err = DestinationTypeString(string(text))
	return err
}
