// Code generated by "enumer -type=OutputFormat -transform=lower -text"; DO NOT EDIT.

package manfiestdata

import (
	"fmt"
	"strings"
)

const _OutputFormatName = "yamljson"

var _OutputFormatIndex = [...]uint8{0, 4, 8}

const _OutputFormatLowerName = "yamljson"

func (i OutputFormat) String() string {
	if i < 0 || i >= OutputFormat(len(_OutputFormatIndex)-1) {
		return fmt.Sprintf("OutputFormat(%d)", i)
	}
	return _OutputFormatName[_OutputFormatIndex[i]:_OutputFormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OutputFormatNoOp() {
	var x [1]struct{}
	_ = x[YAML-(0)]
	_ = x[JSON-(1)]
}

var _OutputFormatValues = []OutputFormat{YAML, JSON}

var _OutputFormatNameToValueMap = map[string]OutputFormat{
	_OutputFormatName[0:4]:      YAML,
	_OutputFormatLowerName[0:4]: YAML,
	_OutputFormatName[4:8]:      JSON,
	_OutputFormatLowerName[4:8]: JSON,
}

var _OutputFormatNames = []string{
	_OutputFormatName[0:4],
	_OutputFormatName[4:8],
}

// OutputFormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OutputFormatString(s string) (OutputFormat, error) {
	if val, ok := _OutputFormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OutputFormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OutputFormat values", s)
}

// OutputFormatValues returns all values of the enum
func OutputFormatValues() []OutputFormat {
	return _OutputFormatValues
}

// OutputFormatStrings returns a slice of all String values of the enum
func OutputFormatStrings() []string {
	strs := make([]string, len(_OutputFormatNames))
	copy(strs, _OutputFormatNames)
	return strs
}

// IsAOutputFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OutputFormat) IsAOutputFormat() bool {
	for _, v := range _OutputFormatValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for OutputFormat
func (i OutputFormat) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OutputFormat
func (i *OutputFormat) UnmarshalText(text []byte) error {
	var err error
	*i, err = OutputFormatString(string(text))
	return err
}
