// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connectionmock

import (
	"context"

	octantv1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/mydecisive/octant/internal/connection"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection[T] {
	mock := &MockConnection[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection[T any] struct {
	mock.Mock
}

type MockConnection_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConnection[T]) EXPECT() *MockConnection_Expecter[T] {
	return &MockConnection_Expecter[T]{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) DeleteConnection(ctx context.Context, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockConnection_DeleteConnection_Call[T any] struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) DeleteConnection(ctx interface{}, input interface{}) *MockConnection_DeleteConnection_Call[T] {
	return &MockConnection_DeleteConnection_Call[T]{Call: _e.mock.On("DeleteConnection", ctx, input)}
}

func (_c *MockConnection_DeleteConnection_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) Return(err error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteConnectionValidator provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) DeleteConnectionValidator(ctx context.Context, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnectionValidator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_DeleteConnectionValidator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnectionValidator'
type MockConnection_DeleteConnectionValidator_Call[T any] struct {
	*mock.Call
}

// DeleteConnectionValidator is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) DeleteConnectionValidator(ctx interface{}, input interface{}) *MockConnection_DeleteConnectionValidator_Call[T] {
	return &MockConnection_DeleteConnectionValidator_Call[T]{Call: _e.mock.On("DeleteConnectionValidator", ctx, input)}
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) Return(err error) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) error) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionByName provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionByName(ctx context.Context, input connection.ConnectionCRUDInput) (*T, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionByName")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) (*T, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) *T); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionByName'
type MockConnection_GetConnectionByName_Call[T any] struct {
	*mock.Call
}

// GetConnectionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnectionByName(ctx interface{}, input interface{}) *MockConnection_GetConnectionByName_Call[T] {
	return &MockConnection_GetConnectionByName_Call[T]{Call: _e.mock.On("GetConnectionByName", ctx, input)}
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Return(v *T, err error) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) (*T, error)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionStatus provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionStatus(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string) (*octantv1alpha.GetConnectionStatusResponse, error) {
	ret := _mock.Called(ctx, input, validatorRunID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStatus")
	}

	var r0 *octantv1alpha.GetConnectionStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput, string) (*octantv1alpha.GetConnectionStatusResponse, error)); ok {
		return returnFunc(ctx, input, validatorRunID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput, string) *octantv1alpha.GetConnectionStatusResponse); ok {
		r0 = returnFunc(ctx, input, validatorRunID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*octantv1alpha.GetConnectionStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput, string) error); ok {
		r1 = returnFunc(ctx, input, validatorRunID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStatus'
type MockConnection_GetConnectionStatus_Call[T any] struct {
	*mock.Call
}

// GetConnectionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
//   - validatorRunID string
func (_e *MockConnection_Expecter[T]) GetConnectionStatus(ctx interface{}, input interface{}, validatorRunID interface{}) *MockConnection_GetConnectionStatus_Call[T] {
	return &MockConnection_GetConnectionStatus_Call[T]{Call: _e.mock.On("GetConnectionStatus", ctx, input, validatorRunID)}
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Return(getConnectionStatusResponse *octantv1alpha.GetConnectionStatusResponse, err error) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(getConnectionStatusResponse, err)
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string) (*octantv1alpha.GetConnectionStatusResponse, error)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionValidatorRuns provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionValidatorRuns(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionValidatorRuns")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) ([]string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) []string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionValidatorRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionValidatorRuns'
type MockConnection_GetConnectionValidatorRuns_Call[T any] struct {
	*mock.Call
}

// GetConnectionValidatorRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnectionValidatorRuns(ctx interface{}, input interface{}) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	return &MockConnection_GetConnectionValidatorRuns_Call[T]{Call: _e.mock.On("GetConnectionValidatorRuns", ctx, input)}
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) Return(strings []string, err error) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error)) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnections provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnections(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnections")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) ([]string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) []string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnections'
type MockConnection_GetConnections_Call[T any] struct {
	*mock.Call
}

// GetConnections is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnections(ctx interface{}, input interface{}) *MockConnection_GetConnections_Call[T] {
	return &MockConnection_GetConnections_Call[T]{Call: _e.mock.On("GetConnections", ctx, input)}
}

func (_c *MockConnection_GetConnections_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnections_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnections_Call[T]) Return(strings []string, err error) *MockConnection_GetConnections_Call[T] {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnection_GetConnections_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error)) *MockConnection_GetConnections_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PutConnectionValidatorRun provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) PutConnectionValidatorRun(ctx context.Context, input connection.ConnectionCRUDInput) (string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutConnectionValidatorRun")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) (string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_PutConnectionValidatorRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutConnectionValidatorRun'
type MockConnection_PutConnectionValidatorRun_Call[T any] struct {
	*mock.Call
}

// PutConnectionValidatorRun is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) PutConnectionValidatorRun(ctx interface{}, input interface{}) *MockConnection_PutConnectionValidatorRun_Call[T] {
	return &MockConnection_PutConnectionValidatorRun_Call[T]{Call: _e.mock.On("PutConnectionValidatorRun", ctx, input)}
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) Return(s string, err error) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) (string, error)) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) SaveConnection(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, connection1, input)

	if len(ret) == 0 {
		panic("no return value specified for SaveConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, connection1, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_SaveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConnection'
type MockConnection_SaveConnection_Call[T any] struct {
	*mock.Call
}

// SaveConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connection1 T
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) SaveConnection(ctx interface{}, connection1 interface{}, input interface{}) *MockConnection_SaveConnection_Call[T] {
	return &MockConnection_SaveConnection_Call[T]{Call: _e.mock.On("SaveConnection", ctx, connection1, input)}
}

func (_c *MockConnection_SaveConnection_Call[T]) Run(run func(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput)) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 connection.ConnectionCRUDInput
		if args[2] != nil {
			arg2 = args[2].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) Return(err error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) RunAndReturn(run func(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput) error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}
