// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connectionmock

import (
	"bytes"
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/mydecisive/octant/internal/connection"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection[T] {
	mock := &MockConnection[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection[T any] struct {
	mock.Mock
}

type MockConnection_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConnection[T]) EXPECT() *MockConnection_Expecter[T] {
	return &MockConnection_Expecter[T]{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) DeleteConnection(ctx context.Context, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockConnection_DeleteConnection_Call[T any] struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) DeleteConnection(ctx interface{}, input interface{}) *MockConnection_DeleteConnection_Call[T] {
	return &MockConnection_DeleteConnection_Call[T]{Call: _e.mock.On("DeleteConnection", ctx, input)}
}

func (_c *MockConnection_DeleteConnection_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) Return(err error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteConnectionValidator provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) DeleteConnectionValidator(ctx context.Context, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnectionValidator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_DeleteConnectionValidator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnectionValidator'
type MockConnection_DeleteConnectionValidator_Call[T any] struct {
	*mock.Call
}

// DeleteConnectionValidator is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) DeleteConnectionValidator(ctx interface{}, input interface{}) *MockConnection_DeleteConnectionValidator_Call[T] {
	return &MockConnection_DeleteConnectionValidator_Call[T]{Call: _e.mock.On("DeleteConnectionValidator", ctx, input)}
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) Return(err error) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_DeleteConnectionValidator_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) error) *MockConnection_DeleteConnectionValidator_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionByName provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionByName(ctx context.Context, input connection.ConnectionCRUDInput) (*T, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionByName")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) (*T, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) *T); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionByName'
type MockConnection_GetConnectionByName_Call[T any] struct {
	*mock.Call
}

// GetConnectionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnectionByName(ctx interface{}, input interface{}) *MockConnection_GetConnectionByName_Call[T] {
	return &MockConnection_GetConnectionByName_Call[T]{Call: _e.mock.On("GetConnectionByName", ctx, input)}
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Return(v *T, err error) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) (*T, error)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionStatus provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionStatus(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string) (*octantv1alpha.GetConnectionStatusResponse, error) {
	ret := _mock.Called(ctx, input, validatorRunID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStatus")
	}

	var r0 *octantv1alpha.GetConnectionStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput, string) (*octantv1alpha.GetConnectionStatusResponse, error)); ok {
		return returnFunc(ctx, input, validatorRunID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput, string) *octantv1alpha.GetConnectionStatusResponse); ok {
		r0 = returnFunc(ctx, input, validatorRunID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*octantv1alpha.GetConnectionStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput, string) error); ok {
		r1 = returnFunc(ctx, input, validatorRunID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStatus'
type MockConnection_GetConnectionStatus_Call[T any] struct {
	*mock.Call
}

// GetConnectionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
//   - validatorRunID string
func (_e *MockConnection_Expecter[T]) GetConnectionStatus(ctx interface{}, input interface{}, validatorRunID interface{}) *MockConnection_GetConnectionStatus_Call[T] {
	return &MockConnection_GetConnectionStatus_Call[T]{Call: _e.mock.On("GetConnectionStatus", ctx, input, validatorRunID)}
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Return(getConnectionStatusResponse *octantv1alpha.GetConnectionStatusResponse, err error) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(getConnectionStatusResponse, err)
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput, validatorRunID string) (*octantv1alpha.GetConnectionStatusResponse, error)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionValidatorRuns provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionValidatorRuns(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionValidatorRuns")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) ([]string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) []string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionValidatorRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionValidatorRuns'
type MockConnection_GetConnectionValidatorRuns_Call[T any] struct {
	*mock.Call
}

// GetConnectionValidatorRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnectionValidatorRuns(ctx interface{}, input interface{}) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	return &MockConnection_GetConnectionValidatorRuns_Call[T]{Call: _e.mock.On("GetConnectionValidatorRuns", ctx, input)}
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) Return(strings []string, err error) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnection_GetConnectionValidatorRuns_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error)) *MockConnection_GetConnectionValidatorRuns_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnections provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnections(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetConnections")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) ([]string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) []string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnections'
type MockConnection_GetConnections_Call[T any] struct {
	*mock.Call
}

// GetConnections is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) GetConnections(ctx interface{}, input interface{}) *MockConnection_GetConnections_Call[T] {
	return &MockConnection_GetConnections_Call[T]{Call: _e.mock.On("GetConnections", ctx, input)}
}

func (_c *MockConnection_GetConnections_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_GetConnections_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnections_Call[T]) Return(strings []string, err error) *MockConnection_GetConnections_Call[T] {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnection_GetConnections_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) ([]string, error)) *MockConnection_GetConnections_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PutConnectionValidatorRun provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) PutConnectionValidatorRun(ctx context.Context, input connection.ConnectionCRUDInput) (string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutConnectionValidatorRun")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) (string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.ConnectionCRUDInput) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.ConnectionCRUDInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_PutConnectionValidatorRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutConnectionValidatorRun'
type MockConnection_PutConnectionValidatorRun_Call[T any] struct {
	*mock.Call
}

// PutConnectionValidatorRun is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) PutConnectionValidatorRun(ctx interface{}, input interface{}) *MockConnection_PutConnectionValidatorRun_Call[T] {
	return &MockConnection_PutConnectionValidatorRun_Call[T]{Call: _e.mock.On("PutConnectionValidatorRun", ctx, input)}
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) Run(run func(ctx context.Context, input connection.ConnectionCRUDInput)) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.ConnectionCRUDInput
		if args[1] != nil {
			arg1 = args[1].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) Return(s string, err error) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnection_PutConnectionValidatorRun_Call[T]) RunAndReturn(run func(ctx context.Context, input connection.ConnectionCRUDInput) (string, error)) *MockConnection_PutConnectionValidatorRun_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) SaveConnection(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput) error {
	ret := _mock.Called(ctx, connection1, input)

	if len(ret) == 0 {
		panic("no return value specified for SaveConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, connection.ConnectionCRUDInput) error); ok {
		r0 = returnFunc(ctx, connection1, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_SaveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConnection'
type MockConnection_SaveConnection_Call[T any] struct {
	*mock.Call
}

// SaveConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connection1 T
//   - input connection.ConnectionCRUDInput
func (_e *MockConnection_Expecter[T]) SaveConnection(ctx interface{}, connection1 interface{}, input interface{}) *MockConnection_SaveConnection_Call[T] {
	return &MockConnection_SaveConnection_Call[T]{Call: _e.mock.On("SaveConnection", ctx, connection1, input)}
}

func (_c *MockConnection_SaveConnection_Call[T]) Run(run func(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput)) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 connection.ConnectionCRUDInput
		if args[2] != nil {
			arg2 = args[2].(connection.ConnectionCRUDInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) Return(err error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) RunAndReturn(run func(ctx context.Context, connection1 T, input connection.ConnectionCRUDInput) error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockManifestCompressor creates a new instance of MockManifestCompressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifestCompressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifestCompressor {
	mock := &MockManifestCompressor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifestCompressor is an autogenerated mock type for the ManifestCompressor type
type MockManifestCompressor struct {
	mock.Mock
}

type MockManifestCompressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifestCompressor) EXPECT() *MockManifestCompressor_Expecter {
	return &MockManifestCompressor_Expecter{mock: &_m.Mock}
}

// CreateCompressed provides a mock function for the type MockManifestCompressor
func (_mock *MockManifestCompressor) CreateCompressed(ctx context.Context, input connection.CompressionInput) (*bytes.Buffer, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompressed")
	}

	var r0 *bytes.Buffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.CompressionInput) (*bytes.Buffer, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, connection.CompressionInput) *bytes.Buffer); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, connection.CompressionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestCompressor_CreateCompressed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompressed'
type MockManifestCompressor_CreateCompressed_Call struct {
	*mock.Call
}

// CreateCompressed is a helper method to define mock.On call
//   - ctx context.Context
//   - input connection.CompressionInput
func (_e *MockManifestCompressor_Expecter) CreateCompressed(ctx interface{}, input interface{}) *MockManifestCompressor_CreateCompressed_Call {
	return &MockManifestCompressor_CreateCompressed_Call{Call: _e.mock.On("CreateCompressed", ctx, input)}
}

func (_c *MockManifestCompressor_CreateCompressed_Call) Run(run func(ctx context.Context, input connection.CompressionInput)) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 connection.CompressionInput
		if args[1] != nil {
			arg1 = args[1].(connection.CompressionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestCompressor_CreateCompressed_Call) Return(buffer *bytes.Buffer, err error) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Return(buffer, err)
	return _c
}

func (_c *MockManifestCompressor_CreateCompressed_Call) RunAndReturn(run func(ctx context.Context, input connection.CompressionInput) (*bytes.Buffer, error)) *MockManifestCompressor_CreateCompressed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManifestGenerator creates a new instance of MockManifestGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManifestGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManifestGenerator {
	mock := &MockManifestGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManifestGenerator is an autogenerated mock type for the ManifestGenerator type
type MockManifestGenerator struct {
	mock.Mock
}

type MockManifestGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManifestGenerator) EXPECT() *MockManifestGenerator_Expecter {
	return &MockManifestGenerator_Expecter{mock: &_m.Mock}
}

// CreateExportableArgoManifests provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) CreateExportableArgoManifests(input connection.CompressionInput, connection1 connection.OctantConnectionData) (map[string][]byte, error) {
	ret := _mock.Called(input, connection1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExportableArgoManifests")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(connection.CompressionInput, connection.OctantConnectionData) (map[string][]byte, error)); ok {
		return returnFunc(input, connection1)
	}
	if returnFunc, ok := ret.Get(0).(func(connection.CompressionInput, connection.OctantConnectionData) map[string][]byte); ok {
		r0 = returnFunc(input, connection1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(connection.CompressionInput, connection.OctantConnectionData) error); ok {
		r1 = returnFunc(input, connection1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_CreateExportableArgoManifests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExportableArgoManifests'
type MockManifestGenerator_CreateExportableArgoManifests_Call struct {
	*mock.Call
}

// CreateExportableArgoManifests is a helper method to define mock.On call
//   - input connection.CompressionInput
//   - connection1 connection.OctantConnectionData
func (_e *MockManifestGenerator_Expecter) CreateExportableArgoManifests(input interface{}, connection1 interface{}) *MockManifestGenerator_CreateExportableArgoManifests_Call {
	return &MockManifestGenerator_CreateExportableArgoManifests_Call{Call: _e.mock.On("CreateExportableArgoManifests", input, connection1)}
}

func (_c *MockManifestGenerator_CreateExportableArgoManifests_Call) Run(run func(input connection.CompressionInput, connection1 connection.OctantConnectionData)) *MockManifestGenerator_CreateExportableArgoManifests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 connection.CompressionInput
		if args[0] != nil {
			arg0 = args[0].(connection.CompressionInput)
		}
		var arg1 connection.OctantConnectionData
		if args[1] != nil {
			arg1 = args[1].(connection.OctantConnectionData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_CreateExportableArgoManifests_Call) Return(stringToBytes map[string][]byte, err error) *MockManifestGenerator_CreateExportableArgoManifests_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockManifestGenerator_CreateExportableArgoManifests_Call) RunAndReturn(run func(input connection.CompressionInput, connection1 connection.OctantConnectionData) (map[string][]byte, error)) *MockManifestGenerator_CreateExportableArgoManifests_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExportableTemplateData provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) CreateExportableTemplateData(name string, connection1 connection.OctantConnectionData) (*connection.ArgoConnectionTemplateData, error) {
	ret := _mock.Called(name, connection1)

	if len(ret) == 0 {
		panic("no return value specified for CreateExportableTemplateData")
	}

	var r0 *connection.ArgoConnectionTemplateData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, connection.OctantConnectionData) (*connection.ArgoConnectionTemplateData, error)); ok {
		return returnFunc(name, connection1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, connection.OctantConnectionData) *connection.ArgoConnectionTemplateData); ok {
		r0 = returnFunc(name, connection1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connection.ArgoConnectionTemplateData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, connection.OctantConnectionData) error); ok {
		r1 = returnFunc(name, connection1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_CreateExportableTemplateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExportableTemplateData'
type MockManifestGenerator_CreateExportableTemplateData_Call struct {
	*mock.Call
}

// CreateExportableTemplateData is a helper method to define mock.On call
//   - name string
//   - connection1 connection.OctantConnectionData
func (_e *MockManifestGenerator_Expecter) CreateExportableTemplateData(name interface{}, connection1 interface{}) *MockManifestGenerator_CreateExportableTemplateData_Call {
	return &MockManifestGenerator_CreateExportableTemplateData_Call{Call: _e.mock.On("CreateExportableTemplateData", name, connection1)}
}

func (_c *MockManifestGenerator_CreateExportableTemplateData_Call) Run(run func(name string, connection1 connection.OctantConnectionData)) *MockManifestGenerator_CreateExportableTemplateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 connection.OctantConnectionData
		if args[1] != nil {
			arg1 = args[1].(connection.OctantConnectionData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_CreateExportableTemplateData_Call) Return(argoConnectionTemplateData *connection.ArgoConnectionTemplateData, err error) *MockManifestGenerator_CreateExportableTemplateData_Call {
	_c.Call.Return(argoConnectionTemplateData, err)
	return _c
}

func (_c *MockManifestGenerator_CreateExportableTemplateData_Call) RunAndReturn(run func(name string, connection1 connection.OctantConnectionData) (*connection.ArgoConnectionTemplateData, error)) *MockManifestGenerator_CreateExportableTemplateData_Call {
	_c.Call.Return(run)
	return _c
}

// RenderArgoAppManifest provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) RenderArgoAppManifest(templateData *connection.ArgoConnectionTemplateData, outputFormat connection.ManifestOutputFormat) ([]byte, error) {
	ret := _mock.Called(templateData, outputFormat)

	if len(ret) == 0 {
		panic("no return value specified for RenderArgoAppManifest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoConnectionTemplateData, connection.ManifestOutputFormat) ([]byte, error)); ok {
		return returnFunc(templateData, outputFormat)
	}
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoConnectionTemplateData, connection.ManifestOutputFormat) []byte); ok {
		r0 = returnFunc(templateData, outputFormat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*connection.ArgoConnectionTemplateData, connection.ManifestOutputFormat) error); ok {
		r1 = returnFunc(templateData, outputFormat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_RenderArgoAppManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderArgoAppManifest'
type MockManifestGenerator_RenderArgoAppManifest_Call struct {
	*mock.Call
}

// RenderArgoAppManifest is a helper method to define mock.On call
//   - templateData *connection.ArgoConnectionTemplateData
//   - outputFormat connection.ManifestOutputFormat
func (_e *MockManifestGenerator_Expecter) RenderArgoAppManifest(templateData interface{}, outputFormat interface{}) *MockManifestGenerator_RenderArgoAppManifest_Call {
	return &MockManifestGenerator_RenderArgoAppManifest_Call{Call: _e.mock.On("RenderArgoAppManifest", templateData, outputFormat)}
}

func (_c *MockManifestGenerator_RenderArgoAppManifest_Call) Run(run func(templateData *connection.ArgoConnectionTemplateData, outputFormat connection.ManifestOutputFormat)) *MockManifestGenerator_RenderArgoAppManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *connection.ArgoConnectionTemplateData
		if args[0] != nil {
			arg0 = args[0].(*connection.ArgoConnectionTemplateData)
		}
		var arg1 connection.ManifestOutputFormat
		if args[1] != nil {
			arg1 = args[1].(connection.ManifestOutputFormat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_RenderArgoAppManifest_Call) Return(bytes1 []byte, err error) *MockManifestGenerator_RenderArgoAppManifest_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockManifestGenerator_RenderArgoAppManifest_Call) RunAndReturn(run func(templateData *connection.ArgoConnectionTemplateData, outputFormat connection.ManifestOutputFormat) ([]byte, error)) *MockManifestGenerator_RenderArgoAppManifest_Call {
	_c.Call.Return(run)
	return _c
}

// RenderCollectorDeploymentManifests provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) RenderCollectorDeploymentManifests(templateData *connection.ArgoConnectionTemplateData, manifestTemplates map[string]string, outputFormat connection.ManifestOutputFormat) (map[string][]byte, error) {
	ret := _mock.Called(templateData, manifestTemplates, outputFormat)

	if len(ret) == 0 {
		panic("no return value specified for RenderCollectorDeploymentManifests")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoConnectionTemplateData, map[string]string, connection.ManifestOutputFormat) (map[string][]byte, error)); ok {
		return returnFunc(templateData, manifestTemplates, outputFormat)
	}
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoConnectionTemplateData, map[string]string, connection.ManifestOutputFormat) map[string][]byte); ok {
		r0 = returnFunc(templateData, manifestTemplates, outputFormat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*connection.ArgoConnectionTemplateData, map[string]string, connection.ManifestOutputFormat) error); ok {
		r1 = returnFunc(templateData, manifestTemplates, outputFormat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_RenderCollectorDeploymentManifests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderCollectorDeploymentManifests'
type MockManifestGenerator_RenderCollectorDeploymentManifests_Call struct {
	*mock.Call
}

// RenderCollectorDeploymentManifests is a helper method to define mock.On call
//   - templateData *connection.ArgoConnectionTemplateData
//   - manifestTemplates map[string]string
//   - outputFormat connection.ManifestOutputFormat
func (_e *MockManifestGenerator_Expecter) RenderCollectorDeploymentManifests(templateData interface{}, manifestTemplates interface{}, outputFormat interface{}) *MockManifestGenerator_RenderCollectorDeploymentManifests_Call {
	return &MockManifestGenerator_RenderCollectorDeploymentManifests_Call{Call: _e.mock.On("RenderCollectorDeploymentManifests", templateData, manifestTemplates, outputFormat)}
}

func (_c *MockManifestGenerator_RenderCollectorDeploymentManifests_Call) Run(run func(templateData *connection.ArgoConnectionTemplateData, manifestTemplates map[string]string, outputFormat connection.ManifestOutputFormat)) *MockManifestGenerator_RenderCollectorDeploymentManifests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *connection.ArgoConnectionTemplateData
		if args[0] != nil {
			arg0 = args[0].(*connection.ArgoConnectionTemplateData)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 connection.ManifestOutputFormat
		if args[2] != nil {
			arg2 = args[2].(connection.ManifestOutputFormat)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_RenderCollectorDeploymentManifests_Call) Return(stringToBytes map[string][]byte, err error) *MockManifestGenerator_RenderCollectorDeploymentManifests_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockManifestGenerator_RenderCollectorDeploymentManifests_Call) RunAndReturn(run func(templateData *connection.ArgoConnectionTemplateData, manifestTemplates map[string]string, outputFormat connection.ManifestOutputFormat) (map[string][]byte, error)) *MockManifestGenerator_RenderCollectorDeploymentManifests_Call {
	_c.Call.Return(run)
	return _c
}

// RenderMdaiAppManifest provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) RenderMdaiAppManifest(mdaiVersion string, namespace string) ([]byte, error) {
	ret := _mock.Called(mdaiVersion, namespace)

	if len(ret) == 0 {
		panic("no return value specified for RenderMdaiAppManifest")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return returnFunc(mdaiVersion, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = returnFunc(mdaiVersion, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(mdaiVersion, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_RenderMdaiAppManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderMdaiAppManifest'
type MockManifestGenerator_RenderMdaiAppManifest_Call struct {
	*mock.Call
}

// RenderMdaiAppManifest is a helper method to define mock.On call
//   - mdaiVersion string
//   - namespace string
func (_e *MockManifestGenerator_Expecter) RenderMdaiAppManifest(mdaiVersion interface{}, namespace interface{}) *MockManifestGenerator_RenderMdaiAppManifest_Call {
	return &MockManifestGenerator_RenderMdaiAppManifest_Call{Call: _e.mock.On("RenderMdaiAppManifest", mdaiVersion, namespace)}
}

func (_c *MockManifestGenerator_RenderMdaiAppManifest_Call) Run(run func(mdaiVersion string, namespace string)) *MockManifestGenerator_RenderMdaiAppManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_RenderMdaiAppManifest_Call) Return(bytes1 []byte, err error) *MockManifestGenerator_RenderMdaiAppManifest_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockManifestGenerator_RenderMdaiAppManifest_Call) RunAndReturn(run func(mdaiVersion string, namespace string) ([]byte, error)) *MockManifestGenerator_RenderMdaiAppManifest_Call {
	_c.Call.Return(run)
	return _c
}

// RenderValidatorManifestForConnection provides a mock function for the type MockManifestGenerator
func (_mock *MockManifestGenerator) RenderValidatorManifestForConnection(templateData *connection.ArgoValidatorTemplateData, outputFormat connection.ManifestOutputFormat) ([]byte, error) {
	ret := _mock.Called(templateData, outputFormat)

	if len(ret) == 0 {
		panic("no return value specified for RenderValidatorManifestForConnection")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoValidatorTemplateData, connection.ManifestOutputFormat) ([]byte, error)); ok {
		return returnFunc(templateData, outputFormat)
	}
	if returnFunc, ok := ret.Get(0).(func(*connection.ArgoValidatorTemplateData, connection.ManifestOutputFormat) []byte); ok {
		r0 = returnFunc(templateData, outputFormat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*connection.ArgoValidatorTemplateData, connection.ManifestOutputFormat) error); ok {
		r1 = returnFunc(templateData, outputFormat)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManifestGenerator_RenderValidatorManifestForConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenderValidatorManifestForConnection'
type MockManifestGenerator_RenderValidatorManifestForConnection_Call struct {
	*mock.Call
}

// RenderValidatorManifestForConnection is a helper method to define mock.On call
//   - templateData *connection.ArgoValidatorTemplateData
//   - outputFormat connection.ManifestOutputFormat
func (_e *MockManifestGenerator_Expecter) RenderValidatorManifestForConnection(templateData interface{}, outputFormat interface{}) *MockManifestGenerator_RenderValidatorManifestForConnection_Call {
	return &MockManifestGenerator_RenderValidatorManifestForConnection_Call{Call: _e.mock.On("RenderValidatorManifestForConnection", templateData, outputFormat)}
}

func (_c *MockManifestGenerator_RenderValidatorManifestForConnection_Call) Run(run func(templateData *connection.ArgoValidatorTemplateData, outputFormat connection.ManifestOutputFormat)) *MockManifestGenerator_RenderValidatorManifestForConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *connection.ArgoValidatorTemplateData
		if args[0] != nil {
			arg0 = args[0].(*connection.ArgoValidatorTemplateData)
		}
		var arg1 connection.ManifestOutputFormat
		if args[1] != nil {
			arg1 = args[1].(connection.ManifestOutputFormat)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManifestGenerator_RenderValidatorManifestForConnection_Call) Return(bytes1 []byte, err error) *MockManifestGenerator_RenderValidatorManifestForConnection_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockManifestGenerator_RenderValidatorManifestForConnection_Call) RunAndReturn(run func(templateData *connection.ArgoValidatorTemplateData, outputFormat connection.ManifestOutputFormat) ([]byte, error)) *MockManifestGenerator_RenderValidatorManifestForConnection_Call {
	_c.Call.Return(run)
	return _c
}
