// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connectionmock

import (
	"context"

	"github.com/mydecisive/mdai-gateway/internal/connection"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection[T] {
	mock := &MockConnection[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection[T any] struct {
	mock.Mock
}

type MockConnection_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockConnection[T]) EXPECT() *MockConnection_Expecter[T] {
	return &MockConnection_Expecter[T]{mock: &_m.Mock}
}

// DeleteConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) DeleteConnection(ctx context.Context, namespace string, connectionName string) error {
	ret := _mock.Called(ctx, namespace, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, connectionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_DeleteConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConnection'
type MockConnection_DeleteConnection_Call[T any] struct {
	*mock.Call
}

// DeleteConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connectionName string
func (_e *MockConnection_Expecter[T]) DeleteConnection(ctx interface{}, namespace interface{}, connectionName interface{}) *MockConnection_DeleteConnection_Call[T] {
	return &MockConnection_DeleteConnection_Call[T]{Call: _e.mock.On("DeleteConnection", ctx, namespace, connectionName)}
}

func (_c *MockConnection_DeleteConnection_Call[T]) Run(run func(ctx context.Context, namespace string, connectionName string)) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) Return(err error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_DeleteConnection_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string, connectionName string) error) *MockConnection_DeleteConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionByName provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionByName(ctx context.Context, namespace string, name string) (*T, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionByName")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*T, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *T); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionByName'
type MockConnection_GetConnectionByName_Call[T any] struct {
	*mock.Call
}

// GetConnectionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockConnection_Expecter[T]) GetConnectionByName(ctx interface{}, namespace interface{}, name interface{}) *MockConnection_GetConnectionByName_Call[T] {
	return &MockConnection_GetConnectionByName_Call[T]{Call: _e.mock.On("GetConnectionByName", ctx, namespace, name)}
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Run(run func(ctx context.Context, namespace string, name string)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) Return(v *T, err error) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockConnection_GetConnectionByName_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*T, error)) *MockConnection_GetConnectionByName_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetConnectionStatus provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) GetConnectionStatus(ctx context.Context, namespace string, connectionName string) (*connection.Status, error) {
	ret := _mock.Called(ctx, namespace, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStatus")
	}

	var r0 *connection.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*connection.Status, error)); ok {
		return returnFunc(ctx, namespace, connectionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *connection.Status); ok {
		r0 = returnFunc(ctx, namespace, connectionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connection.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, connectionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnection_GetConnectionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStatus'
type MockConnection_GetConnectionStatus_Call[T any] struct {
	*mock.Call
}

// GetConnectionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connectionName string
func (_e *MockConnection_Expecter[T]) GetConnectionStatus(ctx interface{}, namespace interface{}, connectionName interface{}) *MockConnection_GetConnectionStatus_Call[T] {
	return &MockConnection_GetConnectionStatus_Call[T]{Call: _e.mock.On("GetConnectionStatus", ctx, namespace, connectionName)}
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Run(run func(ctx context.Context, namespace string, connectionName string)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) Return(status *connection.Status, err error) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockConnection_GetConnectionStatus_Call[T]) RunAndReturn(run func(ctx context.Context, namespace string, connectionName string) (*connection.Status, error)) *MockConnection_GetConnectionStatus_Call[T] {
	_c.Call.Return(run)
	return _c
}

// SaveConnection provides a mock function for the type MockConnection
func (_mock *MockConnection[T]) SaveConnection(ctx context.Context, connection1 T, namespace string, connectionName string) error {
	ret := _mock.Called(ctx, connection1, namespace, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for SaveConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, string, string) error); ok {
		r0 = returnFunc(ctx, connection1, namespace, connectionName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnection_SaveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConnection'
type MockConnection_SaveConnection_Call[T any] struct {
	*mock.Call
}

// SaveConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connection1 T
//   - namespace string
//   - connectionName string
func (_e *MockConnection_Expecter[T]) SaveConnection(ctx interface{}, connection1 interface{}, namespace interface{}, connectionName interface{}) *MockConnection_SaveConnection_Call[T] {
	return &MockConnection_SaveConnection_Call[T]{Call: _e.mock.On("SaveConnection", ctx, connection1, namespace, connectionName)}
}

func (_c *MockConnection_SaveConnection_Call[T]) Run(run func(ctx context.Context, connection1 T, namespace string, connectionName string)) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) Return(err error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnection_SaveConnection_Call[T]) RunAndReturn(run func(ctx context.Context, connection1 T, namespace string, connectionName string) error) *MockConnection_SaveConnection_Call[T] {
	_c.Call.Return(run)
	return _c
}
