// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kubeappsv1mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	v12 "k8s.io/api/apps/v1"
	v14 "k8s.io/api/autoscaling/v1"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	v10 "k8s.io/client-go/applyconfigurations/apps/v1"
	v13 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
	"k8s.io/client-go/kubernetes/typed/apps/v1"
	"k8s.io/client-go/rest"
)

// NewMockAppsV1Interface creates a new instance of MockAppsV1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppsV1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppsV1Interface {
	mock := &MockAppsV1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppsV1Interface is an autogenerated mock type for the AppsV1Interface type
type MockAppsV1Interface struct {
	mock.Mock
}

type MockAppsV1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppsV1Interface) EXPECT() *MockAppsV1Interface_Expecter {
	return &MockAppsV1Interface_Expecter{mock: &_m.Mock}
}

// ControllerRevisions provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) ControllerRevisions(namespace string) v1.ControllerRevisionInterface {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ControllerRevisions")
	}

	var r0 v1.ControllerRevisionInterface
	if returnFunc, ok := ret.Get(0).(func(string) v1.ControllerRevisionInterface); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ControllerRevisionInterface)
		}
	}
	return r0
}

// MockAppsV1Interface_ControllerRevisions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ControllerRevisions'
type MockAppsV1Interface_ControllerRevisions_Call struct {
	*mock.Call
}

// ControllerRevisions is a helper method to define mock.On call
//   - namespace string
func (_e *MockAppsV1Interface_Expecter) ControllerRevisions(namespace interface{}) *MockAppsV1Interface_ControllerRevisions_Call {
	return &MockAppsV1Interface_ControllerRevisions_Call{Call: _e.mock.On("ControllerRevisions", namespace)}
}

func (_c *MockAppsV1Interface_ControllerRevisions_Call) Run(run func(namespace string)) *MockAppsV1Interface_ControllerRevisions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppsV1Interface_ControllerRevisions_Call) Return(controllerRevisionInterface v1.ControllerRevisionInterface) *MockAppsV1Interface_ControllerRevisions_Call {
	_c.Call.Return(controllerRevisionInterface)
	return _c
}

func (_c *MockAppsV1Interface_ControllerRevisions_Call) RunAndReturn(run func(namespace string) v1.ControllerRevisionInterface) *MockAppsV1Interface_ControllerRevisions_Call {
	_c.Call.Return(run)
	return _c
}

// DaemonSets provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) DaemonSets(namespace string) v1.DaemonSetInterface {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DaemonSets")
	}

	var r0 v1.DaemonSetInterface
	if returnFunc, ok := ret.Get(0).(func(string) v1.DaemonSetInterface); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DaemonSetInterface)
		}
	}
	return r0
}

// MockAppsV1Interface_DaemonSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DaemonSets'
type MockAppsV1Interface_DaemonSets_Call struct {
	*mock.Call
}

// DaemonSets is a helper method to define mock.On call
//   - namespace string
func (_e *MockAppsV1Interface_Expecter) DaemonSets(namespace interface{}) *MockAppsV1Interface_DaemonSets_Call {
	return &MockAppsV1Interface_DaemonSets_Call{Call: _e.mock.On("DaemonSets", namespace)}
}

func (_c *MockAppsV1Interface_DaemonSets_Call) Run(run func(namespace string)) *MockAppsV1Interface_DaemonSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppsV1Interface_DaemonSets_Call) Return(daemonSetInterface v1.DaemonSetInterface) *MockAppsV1Interface_DaemonSets_Call {
	_c.Call.Return(daemonSetInterface)
	return _c
}

func (_c *MockAppsV1Interface_DaemonSets_Call) RunAndReturn(run func(namespace string) v1.DaemonSetInterface) *MockAppsV1Interface_DaemonSets_Call {
	_c.Call.Return(run)
	return _c
}

// Deployments provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) Deployments(namespace string) v1.DeploymentInterface {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 v1.DeploymentInterface
	if returnFunc, ok := ret.Get(0).(func(string) v1.DeploymentInterface); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.DeploymentInterface)
		}
	}
	return r0
}

// MockAppsV1Interface_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type MockAppsV1Interface_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - namespace string
func (_e *MockAppsV1Interface_Expecter) Deployments(namespace interface{}) *MockAppsV1Interface_Deployments_Call {
	return &MockAppsV1Interface_Deployments_Call{Call: _e.mock.On("Deployments", namespace)}
}

func (_c *MockAppsV1Interface_Deployments_Call) Run(run func(namespace string)) *MockAppsV1Interface_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppsV1Interface_Deployments_Call) Return(deploymentInterface v1.DeploymentInterface) *MockAppsV1Interface_Deployments_Call {
	_c.Call.Return(deploymentInterface)
	return _c
}

func (_c *MockAppsV1Interface_Deployments_Call) RunAndReturn(run func(namespace string) v1.DeploymentInterface) *MockAppsV1Interface_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// RESTClient provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) RESTClient() rest.Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTClient")
	}

	var r0 rest.Interface
	if returnFunc, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}
	return r0
}

// MockAppsV1Interface_RESTClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTClient'
type MockAppsV1Interface_RESTClient_Call struct {
	*mock.Call
}

// RESTClient is a helper method to define mock.On call
func (_e *MockAppsV1Interface_Expecter) RESTClient() *MockAppsV1Interface_RESTClient_Call {
	return &MockAppsV1Interface_RESTClient_Call{Call: _e.mock.On("RESTClient")}
}

func (_c *MockAppsV1Interface_RESTClient_Call) Run(run func()) *MockAppsV1Interface_RESTClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAppsV1Interface_RESTClient_Call) Return(interfaceParam rest.Interface) *MockAppsV1Interface_RESTClient_Call {
	_c.Call.Return(interfaceParam)
	return _c
}

func (_c *MockAppsV1Interface_RESTClient_Call) RunAndReturn(run func() rest.Interface) *MockAppsV1Interface_RESTClient_Call {
	_c.Call.Return(run)
	return _c
}

// ReplicaSets provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) ReplicaSets(namespace string) v1.ReplicaSetInterface {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for ReplicaSets")
	}

	var r0 v1.ReplicaSetInterface
	if returnFunc, ok := ret.Get(0).(func(string) v1.ReplicaSetInterface); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.ReplicaSetInterface)
		}
	}
	return r0
}

// MockAppsV1Interface_ReplicaSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplicaSets'
type MockAppsV1Interface_ReplicaSets_Call struct {
	*mock.Call
}

// ReplicaSets is a helper method to define mock.On call
//   - namespace string
func (_e *MockAppsV1Interface_Expecter) ReplicaSets(namespace interface{}) *MockAppsV1Interface_ReplicaSets_Call {
	return &MockAppsV1Interface_ReplicaSets_Call{Call: _e.mock.On("ReplicaSets", namespace)}
}

func (_c *MockAppsV1Interface_ReplicaSets_Call) Run(run func(namespace string)) *MockAppsV1Interface_ReplicaSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppsV1Interface_ReplicaSets_Call) Return(replicaSetInterface v1.ReplicaSetInterface) *MockAppsV1Interface_ReplicaSets_Call {
	_c.Call.Return(replicaSetInterface)
	return _c
}

func (_c *MockAppsV1Interface_ReplicaSets_Call) RunAndReturn(run func(namespace string) v1.ReplicaSetInterface) *MockAppsV1Interface_ReplicaSets_Call {
	_c.Call.Return(run)
	return _c
}

// StatefulSets provides a mock function for the type MockAppsV1Interface
func (_mock *MockAppsV1Interface) StatefulSets(namespace string) v1.StatefulSetInterface {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for StatefulSets")
	}

	var r0 v1.StatefulSetInterface
	if returnFunc, ok := ret.Get(0).(func(string) v1.StatefulSetInterface); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.StatefulSetInterface)
		}
	}
	return r0
}

// MockAppsV1Interface_StatefulSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatefulSets'
type MockAppsV1Interface_StatefulSets_Call struct {
	*mock.Call
}

// StatefulSets is a helper method to define mock.On call
//   - namespace string
func (_e *MockAppsV1Interface_Expecter) StatefulSets(namespace interface{}) *MockAppsV1Interface_StatefulSets_Call {
	return &MockAppsV1Interface_StatefulSets_Call{Call: _e.mock.On("StatefulSets", namespace)}
}

func (_c *MockAppsV1Interface_StatefulSets_Call) Run(run func(namespace string)) *MockAppsV1Interface_StatefulSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppsV1Interface_StatefulSets_Call) Return(statefulSetInterface v1.StatefulSetInterface) *MockAppsV1Interface_StatefulSets_Call {
	_c.Call.Return(statefulSetInterface)
	return _c
}

func (_c *MockAppsV1Interface_StatefulSets_Call) RunAndReturn(run func(namespace string) v1.StatefulSetInterface) *MockAppsV1Interface_StatefulSets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeploymentInterface creates a new instance of MockDeploymentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentInterface {
	mock := &MockDeploymentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploymentInterface is an autogenerated mock type for the DeploymentInterface type
type MockDeploymentInterface struct {
	mock.Mock
}

type MockDeploymentInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentInterface) EXPECT() *MockDeploymentInterface_Expecter {
	return &MockDeploymentInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Apply(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, deployment, opts)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, deployment, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, deployment, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, deployment, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockDeploymentInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v10.DeploymentApplyConfiguration
//   - opts v11.ApplyOptions
func (_e *MockDeploymentInterface_Expecter) Apply(ctx interface{}, deployment interface{}, opts interface{}) *MockDeploymentInterface_Apply_Call {
	return &MockDeploymentInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, deployment, opts)}
}

func (_c *MockDeploymentInterface_Apply_Call) Run(run func(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions)) *MockDeploymentInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v10.DeploymentApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v10.DeploymentApplyConfiguration)
		}
		var arg2 v11.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v11.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Apply_Call) Return(result *v12.Deployment, err error) *MockDeploymentInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDeploymentInterface_Apply_Call) RunAndReturn(run func(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions) (*v12.Deployment, error)) *MockDeploymentInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyScale provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) ApplyScale(ctx context.Context, deploymentName string, scale *v13.ScaleApplyConfiguration, opts v11.ApplyOptions) (*v14.Scale, error) {
	ret := _mock.Called(ctx, deploymentName, scale, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyScale")
	}

	var r0 *v14.Scale
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v13.ScaleApplyConfiguration, v11.ApplyOptions) (*v14.Scale, error)); ok {
		return returnFunc(ctx, deploymentName, scale, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v13.ScaleApplyConfiguration, v11.ApplyOptions) *v14.Scale); ok {
		r0 = returnFunc(ctx, deploymentName, scale, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v14.Scale)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v13.ScaleApplyConfiguration, v11.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, deploymentName, scale, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_ApplyScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyScale'
type MockDeploymentInterface_ApplyScale_Call struct {
	*mock.Call
}

// ApplyScale is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentName string
//   - scale *v13.ScaleApplyConfiguration
//   - opts v11.ApplyOptions
func (_e *MockDeploymentInterface_Expecter) ApplyScale(ctx interface{}, deploymentName interface{}, scale interface{}, opts interface{}) *MockDeploymentInterface_ApplyScale_Call {
	return &MockDeploymentInterface_ApplyScale_Call{Call: _e.mock.On("ApplyScale", ctx, deploymentName, scale, opts)}
}

func (_c *MockDeploymentInterface_ApplyScale_Call) Run(run func(ctx context.Context, deploymentName string, scale *v13.ScaleApplyConfiguration, opts v11.ApplyOptions)) *MockDeploymentInterface_ApplyScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v13.ScaleApplyConfiguration
		if args[2] != nil {
			arg2 = args[2].(*v13.ScaleApplyConfiguration)
		}
		var arg3 v11.ApplyOptions
		if args[3] != nil {
			arg3 = args[3].(v11.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_ApplyScale_Call) Return(scale1 *v14.Scale, err error) *MockDeploymentInterface_ApplyScale_Call {
	_c.Call.Return(scale1, err)
	return _c
}

func (_c *MockDeploymentInterface_ApplyScale_Call) RunAndReturn(run func(ctx context.Context, deploymentName string, scale *v13.ScaleApplyConfiguration, opts v11.ApplyOptions) (*v14.Scale, error)) *MockDeploymentInterface_ApplyScale_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) ApplyStatus(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, deployment, opts)

	if len(ret) == 0 {
		panic("no return value specified for ApplyStatus")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, deployment, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, deployment, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v10.DeploymentApplyConfiguration, v11.ApplyOptions) error); ok {
		r1 = returnFunc(ctx, deployment, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type MockDeploymentInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v10.DeploymentApplyConfiguration
//   - opts v11.ApplyOptions
func (_e *MockDeploymentInterface_Expecter) ApplyStatus(ctx interface{}, deployment interface{}, opts interface{}) *MockDeploymentInterface_ApplyStatus_Call {
	return &MockDeploymentInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, deployment, opts)}
}

func (_c *MockDeploymentInterface_ApplyStatus_Call) Run(run func(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions)) *MockDeploymentInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v10.DeploymentApplyConfiguration
		if args[1] != nil {
			arg1 = args[1].(*v10.DeploymentApplyConfiguration)
		}
		var arg2 v11.ApplyOptions
		if args[2] != nil {
			arg2 = args[2].(v11.ApplyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_ApplyStatus_Call) Return(result *v12.Deployment, err error) *MockDeploymentInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDeploymentInterface_ApplyStatus_Call) RunAndReturn(run func(ctx context.Context, deployment *v10.DeploymentApplyConfiguration, opts v11.ApplyOptions) (*v12.Deployment, error)) *MockDeploymentInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Create(ctx context.Context, deployment *v12.Deployment, opts v11.CreateOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, deployment, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.CreateOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, deployment, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.CreateOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, deployment, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v12.Deployment, v11.CreateOptions) error); ok {
		r1 = returnFunc(ctx, deployment, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeploymentInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v12.Deployment
//   - opts v11.CreateOptions
func (_e *MockDeploymentInterface_Expecter) Create(ctx interface{}, deployment interface{}, opts interface{}) *MockDeploymentInterface_Create_Call {
	return &MockDeploymentInterface_Create_Call{Call: _e.mock.On("Create", ctx, deployment, opts)}
}

func (_c *MockDeploymentInterface_Create_Call) Run(run func(ctx context.Context, deployment *v12.Deployment, opts v11.CreateOptions)) *MockDeploymentInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v12.Deployment
		if args[1] != nil {
			arg1 = args[1].(*v12.Deployment)
		}
		var arg2 v11.CreateOptions
		if args[2] != nil {
			arg2 = args[2].(v11.CreateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Create_Call) Return(deployment1 *v12.Deployment, err error) *MockDeploymentInterface_Create_Call {
	_c.Call.Return(deployment1, err)
	return _c
}

func (_c *MockDeploymentInterface_Create_Call) RunAndReturn(run func(ctx context.Context, deployment *v12.Deployment, opts v11.CreateOptions) (*v12.Deployment, error)) *MockDeploymentInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Delete(ctx context.Context, name string, opts v11.DeleteOptions) error {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v11.DeleteOptions) error); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeploymentInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v11.DeleteOptions
func (_e *MockDeploymentInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *MockDeploymentInterface_Delete_Call {
	return &MockDeploymentInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *MockDeploymentInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts v11.DeleteOptions)) *MockDeploymentInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v11.DeleteOptions
		if args[2] != nil {
			arg2 = args[2].(v11.DeleteOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Delete_Call) Return(err error) *MockDeploymentInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, name string, opts v11.DeleteOptions) error) *MockDeploymentInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) DeleteCollection(ctx context.Context, opts v11.DeleteOptions, listOpts v11.ListOptions) error {
	ret := _mock.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v11.DeleteOptions, v11.ListOptions) error); ok {
		r0 = returnFunc(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockDeploymentInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v11.DeleteOptions
//   - listOpts v11.ListOptions
func (_e *MockDeploymentInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *MockDeploymentInterface_DeleteCollection_Call {
	return &MockDeploymentInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *MockDeploymentInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts v11.DeleteOptions, listOpts v11.ListOptions)) *MockDeploymentInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v11.DeleteOptions
		if args[1] != nil {
			arg1 = args[1].(v11.DeleteOptions)
		}
		var arg2 v11.ListOptions
		if args[2] != nil {
			arg2 = args[2].(v11.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_DeleteCollection_Call) Return(err error) *MockDeploymentInterface_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentInterface_DeleteCollection_Call) RunAndReturn(run func(ctx context.Context, opts v11.DeleteOptions, listOpts v11.ListOptions) error) *MockDeploymentInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Get(ctx context.Context, name string, opts v11.GetOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v11.GetOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, name, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v11.GetOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v11.GetOptions) error); ok {
		r1 = returnFunc(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeploymentInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v11.GetOptions
func (_e *MockDeploymentInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *MockDeploymentInterface_Get_Call {
	return &MockDeploymentInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *MockDeploymentInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v11.GetOptions)) *MockDeploymentInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v11.GetOptions
		if args[2] != nil {
			arg2 = args[2].(v11.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Get_Call) Return(deployment *v12.Deployment, err error) *MockDeploymentInterface_Get_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *MockDeploymentInterface_Get_Call) RunAndReturn(run func(ctx context.Context, name string, opts v11.GetOptions) (*v12.Deployment, error)) *MockDeploymentInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetScale provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) GetScale(ctx context.Context, deploymentName string, options v11.GetOptions) (*v14.Scale, error) {
	ret := _mock.Called(ctx, deploymentName, options)

	if len(ret) == 0 {
		panic("no return value specified for GetScale")
	}

	var r0 *v14.Scale
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v11.GetOptions) (*v14.Scale, error)); ok {
		return returnFunc(ctx, deploymentName, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v11.GetOptions) *v14.Scale); ok {
		r0 = returnFunc(ctx, deploymentName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v14.Scale)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v11.GetOptions) error); ok {
		r1 = returnFunc(ctx, deploymentName, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_GetScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScale'
type MockDeploymentInterface_GetScale_Call struct {
	*mock.Call
}

// GetScale is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentName string
//   - options v11.GetOptions
func (_e *MockDeploymentInterface_Expecter) GetScale(ctx interface{}, deploymentName interface{}, options interface{}) *MockDeploymentInterface_GetScale_Call {
	return &MockDeploymentInterface_GetScale_Call{Call: _e.mock.On("GetScale", ctx, deploymentName, options)}
}

func (_c *MockDeploymentInterface_GetScale_Call) Run(run func(ctx context.Context, deploymentName string, options v11.GetOptions)) *MockDeploymentInterface_GetScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v11.GetOptions
		if args[2] != nil {
			arg2 = args[2].(v11.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_GetScale_Call) Return(scale *v14.Scale, err error) *MockDeploymentInterface_GetScale_Call {
	_c.Call.Return(scale, err)
	return _c
}

func (_c *MockDeploymentInterface_GetScale_Call) RunAndReturn(run func(ctx context.Context, deploymentName string, options v11.GetOptions) (*v14.Scale, error)) *MockDeploymentInterface_GetScale_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) List(ctx context.Context, opts v11.ListOptions) (*v12.DeploymentList, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v12.DeploymentList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v11.ListOptions) (*v12.DeploymentList, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v11.ListOptions) *v12.DeploymentList); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.DeploymentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v11.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDeploymentInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v11.ListOptions
func (_e *MockDeploymentInterface_Expecter) List(ctx interface{}, opts interface{}) *MockDeploymentInterface_List_Call {
	return &MockDeploymentInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockDeploymentInterface_List_Call) Run(run func(ctx context.Context, opts v11.ListOptions)) *MockDeploymentInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v11.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v11.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_List_Call) Return(deploymentList *v12.DeploymentList, err error) *MockDeploymentInterface_List_Call {
	_c.Call.Return(deploymentList, err)
	return _c
}

func (_c *MockDeploymentInterface_List_Call) RunAndReturn(run func(ctx context.Context, opts v11.ListOptions) (*v12.DeploymentList, error)) *MockDeploymentInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v11.PatchOptions, subresources ...string) (*v12.Deployment, error) {
	var tmpRet mock.Arguments
	if len(subresources) > 0 {
		tmpRet = _mock.Called(ctx, name, pt, data, opts, subresources)
	} else {
		tmpRet = _mock.Called(ctx, name, pt, data, opts)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v11.PatchOptions, ...string) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, name, pt, data, opts, subresources...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, v11.PatchOptions, ...string) *v12.Deployment); ok {
		r0 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, v11.PatchOptions, ...string) error); ok {
		r1 = returnFunc(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockDeploymentInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts v11.PatchOptions
//   - subresources ...string
func (_e *MockDeploymentInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *MockDeploymentInterface_Patch_Call {
	return &MockDeploymentInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *MockDeploymentInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v11.PatchOptions, subresources ...string)) *MockDeploymentInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.PatchType
		if args[2] != nil {
			arg2 = args[2].(types.PatchType)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 v11.PatchOptions
		if args[4] != nil {
			arg4 = args[4].(v11.PatchOptions)
		}
		var arg5 []string
		var variadicArgs []string
		if len(args) > 5 {
			variadicArgs = args[5].([]string)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Patch_Call) Return(result *v12.Deployment, err error) *MockDeploymentInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDeploymentInterface_Patch_Call) RunAndReturn(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts v11.PatchOptions, subresources ...string) (*v12.Deployment, error)) *MockDeploymentInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Update(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, deployment, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.UpdateOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, deployment, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.UpdateOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, deployment, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v12.Deployment, v11.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, deployment, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDeploymentInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v12.Deployment
//   - opts v11.UpdateOptions
func (_e *MockDeploymentInterface_Expecter) Update(ctx interface{}, deployment interface{}, opts interface{}) *MockDeploymentInterface_Update_Call {
	return &MockDeploymentInterface_Update_Call{Call: _e.mock.On("Update", ctx, deployment, opts)}
}

func (_c *MockDeploymentInterface_Update_Call) Run(run func(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions)) *MockDeploymentInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v12.Deployment
		if args[1] != nil {
			arg1 = args[1].(*v12.Deployment)
		}
		var arg2 v11.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v11.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Update_Call) Return(deployment1 *v12.Deployment, err error) *MockDeploymentInterface_Update_Call {
	_c.Call.Return(deployment1, err)
	return _c
}

func (_c *MockDeploymentInterface_Update_Call) RunAndReturn(run func(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions) (*v12.Deployment, error)) *MockDeploymentInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateScale provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) UpdateScale(ctx context.Context, deploymentName string, scale *v14.Scale, opts v11.UpdateOptions) (*v14.Scale, error) {
	ret := _mock.Called(ctx, deploymentName, scale, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScale")
	}

	var r0 *v14.Scale
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v14.Scale, v11.UpdateOptions) (*v14.Scale, error)); ok {
		return returnFunc(ctx, deploymentName, scale, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v14.Scale, v11.UpdateOptions) *v14.Scale); ok {
		r0 = returnFunc(ctx, deploymentName, scale, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v14.Scale)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v14.Scale, v11.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, deploymentName, scale, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_UpdateScale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateScale'
type MockDeploymentInterface_UpdateScale_Call struct {
	*mock.Call
}

// UpdateScale is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentName string
//   - scale *v14.Scale
//   - opts v11.UpdateOptions
func (_e *MockDeploymentInterface_Expecter) UpdateScale(ctx interface{}, deploymentName interface{}, scale interface{}, opts interface{}) *MockDeploymentInterface_UpdateScale_Call {
	return &MockDeploymentInterface_UpdateScale_Call{Call: _e.mock.On("UpdateScale", ctx, deploymentName, scale, opts)}
}

func (_c *MockDeploymentInterface_UpdateScale_Call) Run(run func(ctx context.Context, deploymentName string, scale *v14.Scale, opts v11.UpdateOptions)) *MockDeploymentInterface_UpdateScale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v14.Scale
		if args[2] != nil {
			arg2 = args[2].(*v14.Scale)
		}
		var arg3 v11.UpdateOptions
		if args[3] != nil {
			arg3 = args[3].(v11.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_UpdateScale_Call) Return(scale1 *v14.Scale, err error) *MockDeploymentInterface_UpdateScale_Call {
	_c.Call.Return(scale1, err)
	return _c
}

func (_c *MockDeploymentInterface_UpdateScale_Call) RunAndReturn(run func(ctx context.Context, deploymentName string, scale *v14.Scale, opts v11.UpdateOptions) (*v14.Scale, error)) *MockDeploymentInterface_UpdateScale_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) UpdateStatus(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions) (*v12.Deployment, error) {
	ret := _mock.Called(ctx, deployment, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v12.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.UpdateOptions) (*v12.Deployment, error)); ok {
		return returnFunc(ctx, deployment, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v12.Deployment, v11.UpdateOptions) *v12.Deployment); ok {
		r0 = returnFunc(ctx, deployment, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v12.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v12.Deployment, v11.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, deployment, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockDeploymentInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *v12.Deployment
//   - opts v11.UpdateOptions
func (_e *MockDeploymentInterface_Expecter) UpdateStatus(ctx interface{}, deployment interface{}, opts interface{}) *MockDeploymentInterface_UpdateStatus_Call {
	return &MockDeploymentInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, deployment, opts)}
}

func (_c *MockDeploymentInterface_UpdateStatus_Call) Run(run func(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions)) *MockDeploymentInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v12.Deployment
		if args[1] != nil {
			arg1 = args[1].(*v12.Deployment)
		}
		var arg2 v11.UpdateOptions
		if args[2] != nil {
			arg2 = args[2].(v11.UpdateOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_UpdateStatus_Call) Return(deployment1 *v12.Deployment, err error) *MockDeploymentInterface_UpdateStatus_Call {
	_c.Call.Return(deployment1, err)
	return _c
}

func (_c *MockDeploymentInterface_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, deployment *v12.Deployment, opts v11.UpdateOptions) (*v12.Deployment, error)) *MockDeploymentInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockDeploymentInterface
func (_mock *MockDeploymentInterface) Watch(ctx context.Context, opts v11.ListOptions) (watch.Interface, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v11.ListOptions) (watch.Interface, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v11.ListOptions) watch.Interface); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v11.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockDeploymentInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v11.ListOptions
func (_e *MockDeploymentInterface_Expecter) Watch(ctx interface{}, opts interface{}) *MockDeploymentInterface_Watch_Call {
	return &MockDeploymentInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *MockDeploymentInterface_Watch_Call) Run(run func(ctx context.Context, opts v11.ListOptions)) *MockDeploymentInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v11.ListOptions
		if args[1] != nil {
			arg1 = args[1].(v11.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentInterface_Watch_Call) Return(interfaceParam watch.Interface, err error) *MockDeploymentInterface_Watch_Call {
	_c.Call.Return(interfaceParam, err)
	return _c
}

func (_c *MockDeploymentInterface_Watch_Call) RunAndReturn(run func(ctx context.Context, opts v11.ListOptions) (watch.Interface, error)) *MockDeploymentInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}
