// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package installlogmock

import (
	"context"

	"github.com/mydecisive/octant/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInstallLogStore creates a new instance of MockInstallLogStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallLogStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallLogStore {
	mock := &MockInstallLogStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallLogStore is an autogenerated mock type for the InstallLogStore type
type MockInstallLogStore struct {
	mock.Mock
}

type MockInstallLogStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallLogStore) EXPECT() *MockInstallLogStore_Expecter {
	return &MockInstallLogStore_Expecter{mock: &_m.Mock}
}

// AddInstallLogEvent provides a mock function for the type MockInstallLogStore
func (_mock *MockInstallLogStore) AddInstallLogEvent(ctx context.Context, entry *v1.OctantInstallEvent) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for AddInstallLogEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.OctantInstallEvent) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallLogStore_AddInstallLogEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddInstallLogEvent'
type MockInstallLogStore_AddInstallLogEvent_Call struct {
	*mock.Call
}

// AddInstallLogEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *v1.OctantInstallEvent
func (_e *MockInstallLogStore_Expecter) AddInstallLogEvent(ctx interface{}, entry interface{}) *MockInstallLogStore_AddInstallLogEvent_Call {
	return &MockInstallLogStore_AddInstallLogEvent_Call{Call: _e.mock.On("AddInstallLogEvent", ctx, entry)}
}

func (_c *MockInstallLogStore_AddInstallLogEvent_Call) Run(run func(ctx context.Context, entry *v1.OctantInstallEvent)) *MockInstallLogStore_AddInstallLogEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.OctantInstallEvent
		if args[1] != nil {
			arg1 = args[1].(*v1.OctantInstallEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallLogStore_AddInstallLogEvent_Call) Return(err error) *MockInstallLogStore_AddInstallLogEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallLogStore_AddInstallLogEvent_Call) RunAndReturn(run func(ctx context.Context, entry *v1.OctantInstallEvent) error) *MockInstallLogStore_AddInstallLogEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallLog provides a mock function for the type MockInstallLogStore
func (_mock *MockInstallLogStore) GetInstallLog(ctx context.Context) (*v1.OctantInstallLogSpec, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallLog")
	}

	var r0 *v1.OctantInstallLogSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v1.OctantInstallLogSpec, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v1.OctantInstallLogSpec); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.OctantInstallLogSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstallLogStore_GetInstallLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallLog'
type MockInstallLogStore_GetInstallLog_Call struct {
	*mock.Call
}

// GetInstallLog is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInstallLogStore_Expecter) GetInstallLog(ctx interface{}) *MockInstallLogStore_GetInstallLog_Call {
	return &MockInstallLogStore_GetInstallLog_Call{Call: _e.mock.On("GetInstallLog", ctx)}
}

func (_c *MockInstallLogStore_GetInstallLog_Call) Run(run func(ctx context.Context)) *MockInstallLogStore_GetInstallLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallLogStore_GetInstallLog_Call) Return(octantInstallLogSpec *v1.OctantInstallLogSpec, err error) *MockInstallLogStore_GetInstallLog_Call {
	_c.Call.Return(octantInstallLogSpec, err)
	return _c
}

func (_c *MockInstallLogStore_GetInstallLog_Call) RunAndReturn(run func(ctx context.Context) (*v1.OctantInstallLogSpec, error)) *MockInstallLogStore_GetInstallLog_Call {
	_c.Call.Return(run)
	return _c
}
