// Code generated by "enumer -type=Environment -text"; DO NOT EDIT.

package config

import (
	"fmt"
	"strings"
)

const _EnvironmentName = "DevCIProd"

var _EnvironmentIndex = [...]uint8{0, 3, 5, 9}

const _EnvironmentLowerName = "devciprod"

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_EnvironmentIndex)-1) {
		return fmt.Sprintf("Environment(%d)", i)
	}
	return _EnvironmentName[_EnvironmentIndex[i]:_EnvironmentIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _EnvironmentNoOp() {
	var x [1]struct{}
	_ = x[Dev-(0)]
	_ = x[CI-(1)]
	_ = x[Prod-(2)]
}

var _EnvironmentValues = []Environment{Dev, CI, Prod}

var _EnvironmentNameToValueMap = map[string]Environment{
	_EnvironmentName[0:3]:      Dev,
	_EnvironmentLowerName[0:3]: Dev,
	_EnvironmentName[3:5]:      CI,
	_EnvironmentLowerName[3:5]: CI,
	_EnvironmentName[5:9]:      Prod,
	_EnvironmentLowerName[5:9]: Prod,
}

var _EnvironmentNames = []string{
	_EnvironmentName[0:3],
	_EnvironmentName[3:5],
	_EnvironmentName[5:9],
}

// EnvironmentString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EnvironmentString(s string) (Environment, error) {
	if val, ok := _EnvironmentNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _EnvironmentNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Environment values", s)
}

// EnvironmentValues returns all values of the enum
func EnvironmentValues() []Environment {
	return _EnvironmentValues
}

// EnvironmentStrings returns a slice of all String values of the enum
func EnvironmentStrings() []string {
	strs := make([]string, len(_EnvironmentNames))
	copy(strs, _EnvironmentNames)
	return strs
}

// IsAEnvironment returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Environment) IsAEnvironment() bool {
	for _, v := range _EnvironmentValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Environment
func (i Environment) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Environment
func (i *Environment) UnmarshalText(text []byte) error {
	var err error
	*i, err = EnvironmentString(string(text))
	return err
}
