// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package settingmock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/mydecisive/octant/internal/setting"
	mock "github.com/stretchr/testify/mock"
	"go.uber.org/zap"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockManager
func (_mock *MockManager) Apply(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockManager_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Apply(ctx interface{}) *MockManager_Apply_Call {
	return &MockManager_Apply_Call{Call: _e.mock.On("Apply", ctx)}
}

func (_c *MockManager_Apply_Call) Run(run func(ctx context.Context)) *MockManager_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Apply_Call) Return(err error) *MockManager_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Apply_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// DeployAndWait provides a mock function for the type MockManager
func (_mock *MockManager) DeployAndWait(ctx context.Context, out chan setting.SettingUpdateResult) {
	_mock.Called(ctx, out)
	return
}

// MockManager_DeployAndWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployAndWait'
type MockManager_DeployAndWait_Call struct {
	*mock.Call
}

// DeployAndWait is a helper method to define mock.On call
//   - ctx context.Context
//   - out chan setting.SettingUpdateResult
func (_e *MockManager_Expecter) DeployAndWait(ctx interface{}, out interface{}) *MockManager_DeployAndWait_Call {
	return &MockManager_DeployAndWait_Call{Call: _e.mock.On("DeployAndWait", ctx, out)}
}

func (_c *MockManager_DeployAndWait_Call) Run(run func(ctx context.Context, out chan setting.SettingUpdateResult)) *MockManager_DeployAndWait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan setting.SettingUpdateResult
		if args[1] != nil {
			arg1 = args[1].(chan setting.SettingUpdateResult)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_DeployAndWait_Call) Return() *MockManager_DeployAndWait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_DeployAndWait_Call) RunAndReturn(run func(ctx context.Context, out chan setting.SettingUpdateResult)) *MockManager_DeployAndWait_Call {
	_c.Run(run)
	return _c
}

// SetDatadogAPIKey provides a mock function for the type MockManager
func (_mock *MockManager) SetDatadogAPIKey(key string) setting.Manager {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for SetDatadogAPIKey")
	}

	var r0 setting.Manager
	if returnFunc, ok := ret.Get(0).(func(string) setting.Manager); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(setting.Manager)
		}
	}
	return r0
}

// MockManager_SetDatadogAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDatadogAPIKey'
type MockManager_SetDatadogAPIKey_Call struct {
	*mock.Call
}

// SetDatadogAPIKey is a helper method to define mock.On call
//   - key string
func (_e *MockManager_Expecter) SetDatadogAPIKey(key interface{}) *MockManager_SetDatadogAPIKey_Call {
	return &MockManager_SetDatadogAPIKey_Call{Call: _e.mock.On("SetDatadogAPIKey", key)}
}

func (_c *MockManager_SetDatadogAPIKey_Call) Run(run func(key string)) *MockManager_SetDatadogAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetDatadogAPIKey_Call) Return(manager setting.Manager) *MockManager_SetDatadogAPIKey_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetDatadogAPIKey_Call) RunAndReturn(run func(key string) setting.Manager) *MockManager_SetDatadogAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetDatadogURL provides a mock function for the type MockManager
func (_mock *MockManager) SetDatadogURL(url string) setting.Manager {
	ret := _mock.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for SetDatadogURL")
	}

	var r0 setting.Manager
	if returnFunc, ok := ret.Get(0).(func(string) setting.Manager); ok {
		r0 = returnFunc(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(setting.Manager)
		}
	}
	return r0
}

// MockManager_SetDatadogURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDatadogURL'
type MockManager_SetDatadogURL_Call struct {
	*mock.Call
}

// SetDatadogURL is a helper method to define mock.On call
//   - url string
func (_e *MockManager_Expecter) SetDatadogURL(url interface{}) *MockManager_SetDatadogURL_Call {
	return &MockManager_SetDatadogURL_Call{Call: _e.mock.On("SetDatadogURL", url)}
}

func (_c *MockManager_SetDatadogURL_Call) Run(run func(url string)) *MockManager_SetDatadogURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetDatadogURL_Call) Return(manager setting.Manager) *MockManager_SetDatadogURL_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetDatadogURL_Call) RunAndReturn(run func(url string) setting.Manager) *MockManager_SetDatadogURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetTelemetryTypes provides a mock function for the type MockManager
func (_mock *MockManager) SetTelemetryTypes(types []octantv1alpha.MLTType) setting.Manager {
	ret := _mock.Called(types)

	if len(ret) == 0 {
		panic("no return value specified for SetTelemetryTypes")
	}

	var r0 setting.Manager
	if returnFunc, ok := ret.Get(0).(func([]octantv1alpha.MLTType) setting.Manager); ok {
		r0 = returnFunc(types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(setting.Manager)
		}
	}
	return r0
}

// MockManager_SetTelemetryTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTelemetryTypes'
type MockManager_SetTelemetryTypes_Call struct {
	*mock.Call
}

// SetTelemetryTypes is a helper method to define mock.On call
//   - types []octantv1alpha.MLTType
func (_e *MockManager_Expecter) SetTelemetryTypes(types interface{}) *MockManager_SetTelemetryTypes_Call {
	return &MockManager_SetTelemetryTypes_Call{Call: _e.mock.On("SetTelemetryTypes", types)}
}

func (_c *MockManager_SetTelemetryTypes_Call) Run(run func(types []octantv1alpha.MLTType)) *MockManager_SetTelemetryTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []octantv1alpha.MLTType
		if args[0] != nil {
			arg0 = args[0].([]octantv1alpha.MLTType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetTelemetryTypes_Call) Return(manager setting.Manager) *MockManager_SetTelemetryTypes_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTelemetryTypes_Call) RunAndReturn(run func(types []octantv1alpha.MLTType) setting.Manager) *MockManager_SetTelemetryTypes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManagerBuilder creates a new instance of MockManagerBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerBuilder {
	mock := &MockManagerBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagerBuilder is an autogenerated mock type for the ManagerBuilder type
type MockManagerBuilder struct {
	mock.Mock
}

type MockManagerBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerBuilder) EXPECT() *MockManagerBuilder_Expecter {
	return &MockManagerBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockManagerBuilder
func (_mock *MockManagerBuilder) Build(ctx context.Context, namespace string, connectionName string, logger *zap.Logger) (setting.Manager, error) {
	ret := _mock.Called(ctx, namespace, connectionName, logger)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 setting.Manager
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *zap.Logger) (setting.Manager, error)); ok {
		return returnFunc(ctx, namespace, connectionName, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *zap.Logger) setting.Manager); ok {
		r0 = returnFunc(ctx, namespace, connectionName, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(setting.Manager)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *zap.Logger) error); ok {
		r1 = returnFunc(ctx, namespace, connectionName, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockManagerBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connectionName string
//   - logger *zap.Logger
func (_e *MockManagerBuilder_Expecter) Build(ctx interface{}, namespace interface{}, connectionName interface{}, logger interface{}) *MockManagerBuilder_Build_Call {
	return &MockManagerBuilder_Build_Call{Call: _e.mock.On("Build", ctx, namespace, connectionName, logger)}
}

func (_c *MockManagerBuilder_Build_Call) Run(run func(ctx context.Context, namespace string, connectionName string, logger *zap.Logger)) *MockManagerBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *zap.Logger
		if args[3] != nil {
			arg3 = args[3].(*zap.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManagerBuilder_Build_Call) Return(manager setting.Manager, err error) *MockManagerBuilder_Build_Call {
	_c.Call.Return(manager, err)
	return _c
}

func (_c *MockManagerBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, namespace string, connectionName string, logger *zap.Logger) (setting.Manager, error)) *MockManagerBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
