// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package manifestdatamock

import (
	"context"

	"github.com/mydecisive/octant/internal/connection/manifest/data"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMapper creates a new instance of MockMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMapper {
	mock := &MockMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMapper is an autogenerated mock type for the Mapper type
type MockMapper struct {
	mock.Mock
}

type MockMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMapper) EXPECT() *MockMapper_Expecter {
	return &MockMapper_Expecter{mock: &_m.Mock}
}

// AppTemplateData provides a mock function for the type MockMapper
func (_mock *MockMapper) AppTemplateData(app manifestdata.App, mdaiVersion string, connectionName string, namespace string) manifestdata.AppTemplateData {
	ret := _mock.Called(app, mdaiVersion, connectionName, namespace)

	if len(ret) == 0 {
		panic("no return value specified for AppTemplateData")
	}

	var r0 manifestdata.AppTemplateData
	if returnFunc, ok := ret.Get(0).(func(manifestdata.App, string, string, string) manifestdata.AppTemplateData); ok {
		r0 = returnFunc(app, mdaiVersion, connectionName, namespace)
	} else {
		r0 = ret.Get(0).(manifestdata.AppTemplateData)
	}
	return r0
}

// MockMapper_AppTemplateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppTemplateData'
type MockMapper_AppTemplateData_Call struct {
	*mock.Call
}

// AppTemplateData is a helper method to define mock.On call
//   - app manifestdata.App
//   - mdaiVersion string
//   - connectionName string
//   - namespace string
func (_e *MockMapper_Expecter) AppTemplateData(app interface{}, mdaiVersion interface{}, connectionName interface{}, namespace interface{}) *MockMapper_AppTemplateData_Call {
	return &MockMapper_AppTemplateData_Call{Call: _e.mock.On("AppTemplateData", app, mdaiVersion, connectionName, namespace)}
}

func (_c *MockMapper_AppTemplateData_Call) Run(run func(app manifestdata.App, mdaiVersion string, connectionName string, namespace string)) *MockMapper_AppTemplateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.App
		if args[0] != nil {
			arg0 = args[0].(manifestdata.App)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMapper_AppTemplateData_Call) Return(appTemplateData manifestdata.AppTemplateData) *MockMapper_AppTemplateData_Call {
	_c.Call.Return(appTemplateData)
	return _c
}

func (_c *MockMapper_AppTemplateData_Call) RunAndReturn(run func(app manifestdata.App, mdaiVersion string, connectionName string, namespace string) manifestdata.AppTemplateData) *MockMapper_AppTemplateData_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectionTemplateData provides a mock function for the type MockMapper
func (_mock *MockMapper) ConnectionTemplateData(ctx context.Context, input manifestdata.ConnectionInput) (*manifestdata.ConnectionTemplateData, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ConnectionTemplateData")
	}

	var r0 *manifestdata.ConnectionTemplateData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ConnectionInput) (*manifestdata.ConnectionTemplateData, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, manifestdata.ConnectionInput) *manifestdata.ConnectionTemplateData); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manifestdata.ConnectionTemplateData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, manifestdata.ConnectionInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMapper_ConnectionTemplateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionTemplateData'
type MockMapper_ConnectionTemplateData_Call struct {
	*mock.Call
}

// ConnectionTemplateData is a helper method to define mock.On call
//   - ctx context.Context
//   - input manifestdata.ConnectionInput
func (_e *MockMapper_Expecter) ConnectionTemplateData(ctx interface{}, input interface{}) *MockMapper_ConnectionTemplateData_Call {
	return &MockMapper_ConnectionTemplateData_Call{Call: _e.mock.On("ConnectionTemplateData", ctx, input)}
}

func (_c *MockMapper_ConnectionTemplateData_Call) Run(run func(ctx context.Context, input manifestdata.ConnectionInput)) *MockMapper_ConnectionTemplateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 manifestdata.ConnectionInput
		if args[1] != nil {
			arg1 = args[1].(manifestdata.ConnectionInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMapper_ConnectionTemplateData_Call) Return(connectionTemplateData *manifestdata.ConnectionTemplateData, err error) *MockMapper_ConnectionTemplateData_Call {
	_c.Call.Return(connectionTemplateData, err)
	return _c
}

func (_c *MockMapper_ConnectionTemplateData_Call) RunAndReturn(run func(ctx context.Context, input manifestdata.ConnectionInput) (*manifestdata.ConnectionTemplateData, error)) *MockMapper_ConnectionTemplateData_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatorTemplateData provides a mock function for the type MockMapper
func (_mock *MockMapper) ValidatorTemplateData(input manifestdata.ValidatorInput) manifestdata.ValidatorTemplateData {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ValidatorTemplateData")
	}

	var r0 manifestdata.ValidatorTemplateData
	if returnFunc, ok := ret.Get(0).(func(manifestdata.ValidatorInput) manifestdata.ValidatorTemplateData); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(manifestdata.ValidatorTemplateData)
	}
	return r0
}

// MockMapper_ValidatorTemplateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorTemplateData'
type MockMapper_ValidatorTemplateData_Call struct {
	*mock.Call
}

// ValidatorTemplateData is a helper method to define mock.On call
//   - input manifestdata.ValidatorInput
func (_e *MockMapper_Expecter) ValidatorTemplateData(input interface{}) *MockMapper_ValidatorTemplateData_Call {
	return &MockMapper_ValidatorTemplateData_Call{Call: _e.mock.On("ValidatorTemplateData", input)}
}

func (_c *MockMapper_ValidatorTemplateData_Call) Run(run func(input manifestdata.ValidatorInput)) *MockMapper_ValidatorTemplateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 manifestdata.ValidatorInput
		if args[0] != nil {
			arg0 = args[0].(manifestdata.ValidatorInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMapper_ValidatorTemplateData_Call) Return(validatorTemplateData manifestdata.ValidatorTemplateData) *MockMapper_ValidatorTemplateData_Call {
	_c.Call.Return(validatorTemplateData)
	return _c
}

func (_c *MockMapper_ValidatorTemplateData_Call) RunAndReturn(run func(input manifestdata.ValidatorInput) manifestdata.ValidatorTemplateData) *MockMapper_ValidatorTemplateData_Call {
	_c.Call.Return(run)
	return _c
}
