// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetdatamock

import (
	"github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	"github.com/mydecisive/octant/internal/budget/data"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricDataRetriever creates a new instance of MockMetricDataRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricDataRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricDataRetriever {
	mock := &MockMetricDataRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricDataRetriever is an autogenerated mock type for the MetricDataRetriever type
type MockMetricDataRetriever struct {
	mock.Mock
}

type MockMetricDataRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricDataRetriever) EXPECT() *MockMetricDataRetriever_Expecter {
	return &MockMetricDataRetriever_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function for the type MockMetricDataRetriever
func (_mock *MockMetricDataRetriever) GetLogs(input budgetdata.MetricDataInput) ([]budgetdata.Log, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []budgetdata.Log
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetdata.MetricDataInput) ([]budgetdata.Log, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetdata.MetricDataInput) []budgetdata.Log); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]budgetdata.Log)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(budgetdata.MetricDataInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricDataRetriever_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockMetricDataRetriever_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - input budgetdata.MetricDataInput
func (_e *MockMetricDataRetriever_Expecter) GetLogs(input interface{}) *MockMetricDataRetriever_GetLogs_Call {
	return &MockMetricDataRetriever_GetLogs_Call{Call: _e.mock.On("GetLogs", input)}
}

func (_c *MockMetricDataRetriever_GetLogs_Call) Run(run func(input budgetdata.MetricDataInput)) *MockMetricDataRetriever_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetdata.MetricDataInput
		if args[0] != nil {
			arg0 = args[0].(budgetdata.MetricDataInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricDataRetriever_GetLogs_Call) Return(logs []budgetdata.Log, err error) *MockMetricDataRetriever_GetLogs_Call {
	_c.Call.Return(logs, err)
	return _c
}

func (_c *MockMetricDataRetriever_GetLogs_Call) RunAndReturn(run func(input budgetdata.MetricDataInput) ([]budgetdata.Log, error)) *MockMetricDataRetriever_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverall provides a mock function for the type MockMetricDataRetriever
func (_mock *MockMetricDataRetriever) GetOverall(timeframe budgetv1alpha.Timeframe, namespace string) (*budgetdata.Overall, error) {
	ret := _mock.Called(timeframe, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetOverall")
	}

	var r0 *budgetdata.Overall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.Timeframe, string) (*budgetdata.Overall, error)); ok {
		return returnFunc(timeframe, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.Timeframe, string) *budgetdata.Overall); ok {
		r0 = returnFunc(timeframe, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*budgetdata.Overall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(budgetv1alpha.Timeframe, string) error); ok {
		r1 = returnFunc(timeframe, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricDataRetriever_GetOverall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverall'
type MockMetricDataRetriever_GetOverall_Call struct {
	*mock.Call
}

// GetOverall is a helper method to define mock.On call
//   - timeframe budgetv1alpha.Timeframe
//   - namespace string
func (_e *MockMetricDataRetriever_Expecter) GetOverall(timeframe interface{}, namespace interface{}) *MockMetricDataRetriever_GetOverall_Call {
	return &MockMetricDataRetriever_GetOverall_Call{Call: _e.mock.On("GetOverall", timeframe, namespace)}
}

func (_c *MockMetricDataRetriever_GetOverall_Call) Run(run func(timeframe budgetv1alpha.Timeframe, namespace string)) *MockMetricDataRetriever_GetOverall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetv1alpha.Timeframe
		if args[0] != nil {
			arg0 = args[0].(budgetv1alpha.Timeframe)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricDataRetriever_GetOverall_Call) Return(overall *budgetdata.Overall, err error) *MockMetricDataRetriever_GetOverall_Call {
	_c.Call.Return(overall, err)
	return _c
}

func (_c *MockMetricDataRetriever_GetOverall_Call) RunAndReturn(run func(timeframe budgetv1alpha.Timeframe, namespace string) (*budgetdata.Overall, error)) *MockMetricDataRetriever_GetOverall_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootSpans provides a mock function for the type MockMetricDataRetriever
func (_mock *MockMetricDataRetriever) GetRootSpans(input budgetdata.MetricDataInput) ([]budgetdata.RootSpan, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetRootSpans")
	}

	var r0 []budgetdata.RootSpan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetdata.MetricDataInput) ([]budgetdata.RootSpan, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetdata.MetricDataInput) []budgetdata.RootSpan); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]budgetdata.RootSpan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(budgetdata.MetricDataInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricDataRetriever_GetRootSpans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootSpans'
type MockMetricDataRetriever_GetRootSpans_Call struct {
	*mock.Call
}

// GetRootSpans is a helper method to define mock.On call
//   - input budgetdata.MetricDataInput
func (_e *MockMetricDataRetriever_Expecter) GetRootSpans(input interface{}) *MockMetricDataRetriever_GetRootSpans_Call {
	return &MockMetricDataRetriever_GetRootSpans_Call{Call: _e.mock.On("GetRootSpans", input)}
}

func (_c *MockMetricDataRetriever_GetRootSpans_Call) Run(run func(input budgetdata.MetricDataInput)) *MockMetricDataRetriever_GetRootSpans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetdata.MetricDataInput
		if args[0] != nil {
			arg0 = args[0].(budgetdata.MetricDataInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricDataRetriever_GetRootSpans_Call) Return(rootSpans []budgetdata.RootSpan, err error) *MockMetricDataRetriever_GetRootSpans_Call {
	_c.Call.Return(rootSpans, err)
	return _c
}

func (_c *MockMetricDataRetriever_GetRootSpans_Call) RunAndReturn(run func(input budgetdata.MetricDataInput) ([]budgetdata.RootSpan, error)) *MockMetricDataRetriever_GetRootSpans_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalLog provides a mock function for the type MockMetricDataRetriever
func (_mock *MockMetricDataRetriever) GetTotalLog(timeframe budgetv1alpha.Timeframe, namespace string) (uint64, error) {
	ret := _mock.Called(timeframe, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalLog")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.Timeframe, string) (uint64, error)); ok {
		return returnFunc(timeframe, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(budgetv1alpha.Timeframe, string) uint64); ok {
		r0 = returnFunc(timeframe, namespace)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(budgetv1alpha.Timeframe, string) error); ok {
		r1 = returnFunc(timeframe, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricDataRetriever_GetTotalLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalLog'
type MockMetricDataRetriever_GetTotalLog_Call struct {
	*mock.Call
}

// GetTotalLog is a helper method to define mock.On call
//   - timeframe budgetv1alpha.Timeframe
//   - namespace string
func (_e *MockMetricDataRetriever_Expecter) GetTotalLog(timeframe interface{}, namespace interface{}) *MockMetricDataRetriever_GetTotalLog_Call {
	return &MockMetricDataRetriever_GetTotalLog_Call{Call: _e.mock.On("GetTotalLog", timeframe, namespace)}
}

func (_c *MockMetricDataRetriever_GetTotalLog_Call) Run(run func(timeframe budgetv1alpha.Timeframe, namespace string)) *MockMetricDataRetriever_GetTotalLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 budgetv1alpha.Timeframe
		if args[0] != nil {
			arg0 = args[0].(budgetv1alpha.Timeframe)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricDataRetriever_GetTotalLog_Call) Return(v uint64, err error) *MockMetricDataRetriever_GetTotalLog_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockMetricDataRetriever_GetTotalLog_Call) RunAndReturn(run func(timeframe budgetv1alpha.Timeframe, namespace string) (uint64, error)) *MockMetricDataRetriever_GetTotalLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVariableAccessor creates a new instance of MockVariableAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVariableAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVariableAccessor {
	mock := &MockVariableAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVariableAccessor is an autogenerated mock type for the VariableAccessor type
type MockVariableAccessor struct {
	mock.Mock
}

type MockVariableAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVariableAccessor) EXPECT() *MockVariableAccessor_Expecter {
	return &MockVariableAccessor_Expecter{mock: &_m.Mock}
}

// GetVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) GetVariable(namespace string, hubName string, varName string) (string, error) {
	ret := _mock.Called(namespace, hubName, varName)

	if len(ret) == 0 {
		panic("no return value specified for GetVariable")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(namespace, hubName, varName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(namespace, hubName, varName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(namespace, hubName, varName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableAccessor_GetVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariable'
type MockVariableAccessor_GetVariable_Call struct {
	*mock.Call
}

// GetVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
func (_e *MockVariableAccessor_Expecter) GetVariable(namespace interface{}, hubName interface{}, varName interface{}) *MockVariableAccessor_GetVariable_Call {
	return &MockVariableAccessor_GetVariable_Call{Call: _e.mock.On("GetVariable", namespace, hubName, varName)}
}

func (_c *MockVariableAccessor_GetVariable_Call) Run(run func(namespace string, hubName string, varName string)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) Return(s string, err error) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string) (string, error)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) UpdateVariable(namespace string, hubName string, varName string, value any) error {
	ret := _mock.Called(namespace, hubName, varName, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, any) error); ok {
		r0 = returnFunc(namespace, hubName, varName, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVariableAccessor_UpdateVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariable'
type MockVariableAccessor_UpdateVariable_Call struct {
	*mock.Call
}

// UpdateVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
//   - value any
func (_e *MockVariableAccessor_Expecter) UpdateVariable(namespace interface{}, hubName interface{}, varName interface{}, value interface{}) *MockVariableAccessor_UpdateVariable_Call {
	return &MockVariableAccessor_UpdateVariable_Call{Call: _e.mock.On("UpdateVariable", namespace, hubName, varName, value)}
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Run(run func(namespace string, hubName string, varName string, value any)) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Return(err error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string, value any) error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(run)
	return _c
}
