// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package budgetdatamock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVariableAccessor creates a new instance of MockVariableAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVariableAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVariableAccessor {
	mock := &MockVariableAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVariableAccessor is an autogenerated mock type for the VariableAccessor type
type MockVariableAccessor struct {
	mock.Mock
}

type MockVariableAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVariableAccessor) EXPECT() *MockVariableAccessor_Expecter {
	return &MockVariableAccessor_Expecter{mock: &_m.Mock}
}

// GetVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) GetVariable(namespace string, hubName string, varName string) (string, error) {
	ret := _mock.Called(namespace, hubName, varName)

	if len(ret) == 0 {
		panic("no return value specified for GetVariable")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(namespace, hubName, varName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(namespace, hubName, varName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(namespace, hubName, varName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVariableAccessor_GetVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVariable'
type MockVariableAccessor_GetVariable_Call struct {
	*mock.Call
}

// GetVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
func (_e *MockVariableAccessor_Expecter) GetVariable(namespace interface{}, hubName interface{}, varName interface{}) *MockVariableAccessor_GetVariable_Call {
	return &MockVariableAccessor_GetVariable_Call{Call: _e.mock.On("GetVariable", namespace, hubName, varName)}
}

func (_c *MockVariableAccessor_GetVariable_Call) Run(run func(namespace string, hubName string, varName string)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) Return(s string, err error) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockVariableAccessor_GetVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string) (string, error)) *MockVariableAccessor_GetVariable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariable provides a mock function for the type MockVariableAccessor
func (_mock *MockVariableAccessor) UpdateVariable(namespace string, hubName string, varName string, value any) error {
	ret := _mock.Called(namespace, hubName, varName, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, any) error); ok {
		r0 = returnFunc(namespace, hubName, varName, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVariableAccessor_UpdateVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariable'
type MockVariableAccessor_UpdateVariable_Call struct {
	*mock.Call
}

// UpdateVariable is a helper method to define mock.On call
//   - namespace string
//   - hubName string
//   - varName string
//   - value any
func (_e *MockVariableAccessor_Expecter) UpdateVariable(namespace interface{}, hubName interface{}, varName interface{}, value interface{}) *MockVariableAccessor_UpdateVariable_Call {
	return &MockVariableAccessor_UpdateVariable_Call{Call: _e.mock.On("UpdateVariable", namespace, hubName, varName, value)}
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Run(run func(namespace string, hubName string, varName string, value any)) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) Return(err error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVariableAccessor_UpdateVariable_Call) RunAndReturn(run func(namespace string, hubName string, varName string, value any) error) *MockVariableAccessor_UpdateVariable_Call {
	_c.Call.Return(run)
	return _c
}
