name: Chores

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint & Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Cache Go mod and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: |
          go mod download

      - name: Check module tidiness
        run: |
          make tidy-check

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          install-mode: "binary"
          version: v2.8

      - name: Running Tests
        run: |
          CGO_ENABLED=0 go test -cover -coverprofile=coverage.txt -v -count=1 ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
