name: Docker push for main branch

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker-push:
    uses: MyDecisive/ci/.github/workflows/docker-ghcr.yaml@main
    with:
      build_contexts: "ui-repo=https://github.com/MyDecisive/octant-ui.git#main"
    secrets: inherit # pass all secrets