// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metricsmock

import (
	"context"

	"github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	"github.com/mydecisive/octant/internal/telemetry"
	"github.com/prometheus/client_golang/api/prometheus/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionStatus creates a new instance of MockConnectionStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionStatus {
	mock := &MockConnectionStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionStatus is an autogenerated mock type for the ConnectionStatus type
type MockConnectionStatus struct {
	mock.Mock
}

type MockConnectionStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionStatus) EXPECT() *MockConnectionStatus_Expecter {
	return &MockConnectionStatus_Expecter{mock: &_m.Mock}
}

// GetConnectionStatus provides a mock function for the type MockConnectionStatus
func (_mock *MockConnectionStatus) GetConnectionStatus(ctx context.Context, namespace string, connectionName string, telemetryTypes []telemetry.MLT) (*octantv1alpha.GetConnectionStatusResponse, error) {
	ret := _mock.Called(ctx, namespace, connectionName, telemetryTypes)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionStatus")
	}

	var r0 *octantv1alpha.GetConnectionStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []telemetry.MLT) (*octantv1alpha.GetConnectionStatusResponse, error)); ok {
		return returnFunc(ctx, namespace, connectionName, telemetryTypes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []telemetry.MLT) *octantv1alpha.GetConnectionStatusResponse); ok {
		r0 = returnFunc(ctx, namespace, connectionName, telemetryTypes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*octantv1alpha.GetConnectionStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []telemetry.MLT) error); ok {
		r1 = returnFunc(ctx, namespace, connectionName, telemetryTypes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStatus_GetConnectionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionStatus'
type MockConnectionStatus_GetConnectionStatus_Call struct {
	*mock.Call
}

// GetConnectionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connectionName string
//   - telemetryTypes []telemetry.MLT
func (_e *MockConnectionStatus_Expecter) GetConnectionStatus(ctx interface{}, namespace interface{}, connectionName interface{}, telemetryTypes interface{}) *MockConnectionStatus_GetConnectionStatus_Call {
	return &MockConnectionStatus_GetConnectionStatus_Call{Call: _e.mock.On("GetConnectionStatus", ctx, namespace, connectionName, telemetryTypes)}
}

func (_c *MockConnectionStatus_GetConnectionStatus_Call) Run(run func(ctx context.Context, namespace string, connectionName string, telemetryTypes []telemetry.MLT)) *MockConnectionStatus_GetConnectionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []telemetry.MLT
		if args[3] != nil {
			arg3 = args[3].([]telemetry.MLT)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnectionStatus_GetConnectionStatus_Call) Return(getConnectionStatusResponse *octantv1alpha.GetConnectionStatusResponse, err error) *MockConnectionStatus_GetConnectionStatus_Call {
	_c.Call.Return(getConnectionStatusResponse, err)
	return _c
}

func (_c *MockConnectionStatus_GetConnectionStatus_Call) RunAndReturn(run func(ctx context.Context, namespace string, connectionName string, telemetryTypes []telemetry.MLT) (*octantv1alpha.GetConnectionStatusResponse, error)) *MockConnectionStatus_GetConnectionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionValidatorRuns provides a mock function for the type MockConnectionStatus
func (_mock *MockConnectionStatus) GetConnectionValidatorRuns(ctx context.Context, namespace string, connectionName string) ([]string, error) {
	ret := _mock.Called(ctx, namespace, connectionName)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionValidatorRuns")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, namespace, connectionName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, namespace, connectionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, connectionName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionStatus_GetConnectionValidatorRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionValidatorRuns'
type MockConnectionStatus_GetConnectionValidatorRuns_Call struct {
	*mock.Call
}

// GetConnectionValidatorRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - connectionName string
func (_e *MockConnectionStatus_Expecter) GetConnectionValidatorRuns(ctx interface{}, namespace interface{}, connectionName interface{}) *MockConnectionStatus_GetConnectionValidatorRuns_Call {
	return &MockConnectionStatus_GetConnectionValidatorRuns_Call{Call: _e.mock.On("GetConnectionValidatorRuns", ctx, namespace, connectionName)}
}

func (_c *MockConnectionStatus_GetConnectionValidatorRuns_Call) Run(run func(ctx context.Context, namespace string, connectionName string)) *MockConnectionStatus_GetConnectionValidatorRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnectionStatus_GetConnectionValidatorRuns_Call) Return(strings []string, err error) *MockConnectionStatus_GetConnectionValidatorRuns_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConnectionStatus_GetConnectionValidatorRuns_Call) RunAndReturn(run func(ctx context.Context, namespace string, connectionName string) ([]string, error)) *MockConnectionStatus_GetConnectionValidatorRuns_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPromClientFactory creates a new instance of MockPromClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromClientFactory {
	mock := &MockPromClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPromClientFactory is an autogenerated mock type for the PromClientFactory type
type MockPromClientFactory struct {
	mock.Mock
}

type MockPromClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromClientFactory) EXPECT() *MockPromClientFactory_Expecter {
	return &MockPromClientFactory_Expecter{mock: &_m.Mock}
}

// GetPromClient provides a mock function for the type MockPromClientFactory
func (_mock *MockPromClientFactory) GetPromClient(namespace string) (v1.API, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetPromClient")
	}

	var r0 v1.API
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (v1.API, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) v1.API); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.API)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPromClientFactory_GetPromClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPromClient'
type MockPromClientFactory_GetPromClient_Call struct {
	*mock.Call
}

// GetPromClient is a helper method to define mock.On call
//   - namespace string
func (_e *MockPromClientFactory_Expecter) GetPromClient(namespace interface{}) *MockPromClientFactory_GetPromClient_Call {
	return &MockPromClientFactory_GetPromClient_Call{Call: _e.mock.On("GetPromClient", namespace)}
}

func (_c *MockPromClientFactory_GetPromClient_Call) Run(run func(namespace string)) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPromClientFactory_GetPromClient_Call) Return(aPI v1.API, err error) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Return(aPI, err)
	return _c
}

func (_c *MockPromClientFactory_GetPromClient_Call) RunAndReturn(run func(namespace string) (v1.API, error)) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Return(run)
	return _c
}
