// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metricsmock

import (
	"github.com/prometheus/client_golang/api/prometheus/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPromClientFactory creates a new instance of MockPromClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPromClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPromClientFactory {
	mock := &MockPromClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPromClientFactory is an autogenerated mock type for the PromClientFactory type
type MockPromClientFactory struct {
	mock.Mock
}

type MockPromClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPromClientFactory) EXPECT() *MockPromClientFactory_Expecter {
	return &MockPromClientFactory_Expecter{mock: &_m.Mock}
}

// GetPromClient provides a mock function for the type MockPromClientFactory
func (_mock *MockPromClientFactory) GetPromClient(namespace string) (v1.API, error) {
	ret := _mock.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetPromClient")
	}

	var r0 v1.API
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (v1.API, error)); ok {
		return returnFunc(namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(string) v1.API); ok {
		r0 = returnFunc(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.API)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPromClientFactory_GetPromClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPromClient'
type MockPromClientFactory_GetPromClient_Call struct {
	*mock.Call
}

// GetPromClient is a helper method to define mock.On call
//   - namespace string
func (_e *MockPromClientFactory_Expecter) GetPromClient(namespace interface{}) *MockPromClientFactory_GetPromClient_Call {
	return &MockPromClientFactory_GetPromClient_Call{Call: _e.mock.On("GetPromClient", namespace)}
}

func (_c *MockPromClientFactory_GetPromClient_Call) Run(run func(namespace string)) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPromClientFactory_GetPromClient_Call) Return(aPI v1.API, err error) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Return(aPI, err)
	return _c
}

func (_c *MockPromClientFactory_GetPromClient_Call) RunAndReturn(run func(namespace string) (v1.API, error)) *MockPromClientFactory_GetPromClient_Call {
	_c.Call.Return(run)
	return _c
}
